<h2>
    <?= $this->translate( 'Purchase of equipment' ) ?>
</h2>
<select class="order-by">
    <option>Order by</option>
    <option>Manufacturer, A-Z</option>
    <option>Model, A-Z</option>
</select>
<br/>
<h3>
    <?= $this->translate( 'Our Equipment' ) ?>
</h3>
<span class="see-more">
    <a href="#">
        Click to see all
    </a>
</span>
<div class="device-horizontal-list">
    <div>
        <img src="/media/catalog/product/device-00.png" alt="Device 00">
        <span class="manufacturer">Manufacturer: Zeiss</span>
        <span class="name">Product name: Microscop</span>
        <a href="#"><span>View details</span></a>
    </div>
    <div>
        <img src="/media/catalog/product/device-01.png" alt="Device 01">
        <span class="manufacturer">Manufacturer: Zeiss</span>
        <span class="name">Product name: Microscop</span>
        <a href="#"><span>View details</span></a>
    </div>
    <div>
        <img src="/media/catalog/product/device-00.png" alt="Device 00">
        <span class="manufacturer">Manufacturer: Zeiss</span>
        <span class="name">Product name: Microscop</span>
        <a href="#"><span>View details</span></a>
    </div>
    <div>
        <img src="/media/catalog/product/device-01.png" alt="Device 01">
        <span class="manufacturer">Manufacturer: Zeiss</span>
        <span class="name">Product name: Microscop</span>
        <a href="#"><span>View details</span></a>
    </div>
</div>

