<h2>
    <?= $this->translate( 'Purchase of equipment' ) ?>
</h2>
<?= $this->formOrder ?>
<br/>
<h3>
    <?= $this->translate( 'Our Equipment' ) ?>
</h3>
<span class="see-more">
    <a href="#">
        Click to see all
    </a>
</span>
<div class="device-horizontal-list">
    <?php foreach ( $this->productos as $producto ): ?>

        <div>
            <a href="
            <?=
            $this->url( array( 'module' => 'default' ,
                'controller' => 'equipo' ,
                'action' => 'ver' ,
                'id' => $producto->id ) , null , true )
            ?>
               ">

                <img src="/media/catalog/product/device-00.png" 


                     alt="<?= $producto->nombre ?>">
            </a>

            <span class="manufacturer">
                <?= $this->translate( 'Manufacturer' ) ?> : 
                <?= $producto->fabricante ?>
            </span>
            <span class="name">
                <?= $this->translate( 'Product name' ) ?>: 
                <?= $producto->nombre ?>
            </span>

            <a href="
            <?=
            $this->url( array( 'module' => 'default' ,
                'controller' => 'equipo' ,
                'action' => 'ver' ,
                'id' => $producto->id ) , null , true )
            ?>
               ">
                <span>
                    <?= $this->translate( 'View details' ) ?>
                </span>
            </a>
        </div>

    <?php endforeach; ?>
</div>

<?=
$this->paginationControl(
        $this->productos , 'Sliding' , 'equipo/_pag.phtml'
);
?>

