<span class="breadcrumb">
    <a href="
    <?=
    $this->url( array(
        'module' => 'default' ,
        'controller' => 'equipo' ,
        'action' => 'index'
            ) , 'default' , true )
    ?>">
           <?= $this->translate( 'Home' ) ?>
    </a>

    >
    <a href="
    <?=
    $this->url( array(
        'module' => 'default' ,
        'controller' => 'categoria' ,
        'action' => 'index' ,
        'id' => $this->producto->categoria_id
            ) , 'default' , true )
    ?>">
           <?= $this->producto->categoria ?>
    </a>
    >
    <?= $this->producto->nombre ?>
</span>

<h2>
    <?= $this->producto->nombre ?>
</h2>

<div id="dialog" title="An Image!" style="display: none;">
    <img id="image" src=""/>
</div>

<div id="search" style="display: none;">
    <?= $this->formSearch ?>
</div>

<div id="device-foto-galery">
    <!--Producto -->
    <?php
    $url = (is_null($this->producto->imagen)) ?
            '/media/catalog/product/product/no_image.png' :
            '/media/catalog/product/product/' . $this->producto->imagen
    ?>
    
    <a href="<?= $url ?>" 
       title="<?= $this->producto->nombre ?>" 
       class ="product">
        <img src="<?= $url ?>" 
         alt="<?= $this->producto->nombre ?>"
         title="<?= $this->producto->nombre ?>"
          />
    </a>
    <?php if(count($this->producto->imagenes) >1) :?>
    <?php foreach($this->producto->imagenes as $imagen) :?>
    <!--Producto-->
    <!--\media\catalog\product\thumb-->
    <a href="/media/catalog/product/product/<?= $imagen->imagen ?>" 
       title="<?= $this->producto->nombre ?>" 
       class ="img-thumb">
        <img src="/media/catalog/product/thumb/<?= $imagen->imagen ?>" alt="Device" />
    </a> 
    <?php endforeach;?>

    <!-- Fin de imagenes -->
    <!-- acciones -->
    
    <a href="#">
        <img src="/images/arrow-left.png" alt="">
    </a>
    <a href="#">
        <img src="/images/arrow-right.png" alt="">
    </a>
    <!-- fin de acciones-->
    <?php endif;?>
</div>
<div id="device-description">
    <a href="#" 
    <?=
    Zend_Auth::getInstance()->hasIdentity() ?
                    'id="searchForUser"' : 'id="searchEquipments"'
    ?>>
        <span class="advanced-search-tab">
            <?= $this->translate( 'Advanced Search' ) ?>
        </span>
    </a>

    <span class="device-description-field">
        <?= $this->translate( 'Product name' ) ?>
    </span>
    <span>
        <?= $this->producto->nombre ?>
    </span>


    <?
    if ( Zend_Auth::getInstance()->hasIdentity() )
        {

        echo $this->render( 'equipo/user/deviceDescription.phtml' );
        }
    else
        {
        echo $this->render( 'equipo/guest/deviceDescription.phtml' );
        }
    ?>

</div>
<!---->

<div id="device-actions">
    <?
    if ( Zend_Auth::getInstance()->hasIdentity() )
        {
         if($this->producto->publicacionid == 
            Mtt_Models_Table_PublicacionEquipo::Activada)
             {
            echo $this->render( 'equipo/user/deviceActions.phtml' );
             }
        }
    ?>
    <a href="javascript:history.go(-1)">
        <span class="device-action-back">
            <?= $this->translate( 'Back' ) ?>
        </span>
    </a>
