<h1>Payment Gateway</h1><div class="clear"></div>
<h3>Edit PayPal Payment Details:</h3>
<form action="admin/payment/manager/" method="post">
	<input type="hidden" name="page" value="<?=$this->page?>" />
	<div style="color:green;padding:0 0 15px 0;"><?=$this->msg;?></div>
	<div class="field">
    	<label>API Username</label>
    	<input type="text" name="paypal[api][username]" value="<?=$this->paypal['api']['username']?>" />
    </div>
	<div class="field">
    	<label>API Password</label>
    	<input type="text" name="paypal[api][password]" value="<?=$this->paypal['api']['password']?>" />
    </div>
	<div class="field">
    	<label>API Signature</label>
    	<input type="text" name="paypal[api][signature]" value="<?=$this->paypal['api']['signature']?>" />
    </div>
	<div class="field">
    	<label>API Environment</label>
    	<input type="text" name="paypal[api][environment]" value="<?=$this->paypal['api']['environment']?>" />
    </div>
	<div class="field">
    	<label>Gateway Url</label>
    	<input type="text" name="paypal[url]" value="<?=$this->paypal['url']?>" />
    </div>
	<div class="field">
    	<label>Business</label>
    	<input type="text" name="paypal[business]" value="<?=$this->paypal['business']?>" />
    </div>
	<div class="clear"></div>
    <input type="submit" value="Update"/>
</form>
<br/>
<div class="clear"></div>
<h3>Payments</h3>
<table border="1" cellpadding="2" style="border-collapse: collapse">
	<thead style="background: #DDD;">
		<tr>
			<th>Dentist</th>
			<th>Profile Id</th>
			<th>Transaction Id</th>
			<th>Amount</th>
			<th>Entry Date</th>
		</tr>
	</thead>
	<tbody>
		<?php if(!empty($this->payments)): ?>
		<?php foreach($this->payments as $p):?>
		<tr>
			<td><?=$this->dentists[$p['dentist_id']]['business_name']?></td>
			<td><?=$p['profile_id']?></td>
			<td><?=$p['txn_id']?></td>
			<td><?=$p['amount']?></td>
			<td><?=$p['entry_date']?></td>
		</tr>
		<?php endforeach;?>
		<?php else:?>
		<tr>
			<td colspan="5" style="text-align: center">No payments received yet.</td>
		</tr>
		<?php endif;?>
	</tbody>
</table>
<div class="pages">
	<?php for($i=1; $i<=ceil($this->count/30);$i++):?>
	<a href="admin/payment/manager/?page=<?=$i?>"><?=$i?></a>
	<?php endfor; ?>
</div>