<?php 
    if(isset($_REQUEST['search'])) $s = $_REQUEST;
    else if (isset($this->session->search_event)) {$s=$this->session->search_event;}
    $arrow_up = '<img class="arrow" src="images/arrow_up.png" alt="ASC" title="ASC"/>';
    $arrow_down = '<img class="arrow" src="images/arrow_down.png" alt="DESC" title="DESC"/>';
?>
<h1>Ads Manager</h1>
<a href="admin/ads/add-ad" class="button">Add New</a>
<br /><br /><br />
<form method="post" action="admin/ads/manager">
    <div class="field">
    	<label>Target Country</label>
    	<select name="country_id">
           <option value="-1">All</option>
           <?php foreach ($this->countries as $key=>$c): ?>
           <option value="<?php echo $key;?>" <?php if(isset($s['country_id'])&& $s['country_id']==$key) echo 'selected=="selected"';?>><?php echo $c;?></option>
           <?php endforeach;?>
        </select>
    	<span class="explanation"></span>
    </div>
    <div class="field">
    	<label>Advertiser Name</label>
        <select name="dentist_id">
    	   <option value="-1">All</option> 
           <?php foreach ($this->dentists as $key=>$d): ?>
           <option value="<?php echo $key;?>" <?php if(isset($s['dentist_id'])&& $s['dentist_id']==$key) echo 'selected=="selected"';?>><?php echo $d;?></option>
           <?php endforeach;?>
        </select>
    	<span class="explanation"></span>
    </div>
    <div class="field">
    	<label>Page</label>
    	<select name="page" >
            <option value="0">All</option>
            <?php foreach ($this->pages as $p):?>
            <option value="<?php echo $p['code'];?>"><?php echo $p['title'];?></option>    
            <?php endforeach;?>
        </select>
    	<span class="explanation"></span>
    </div>
    <div class="field">
    	<label>Ad status</label>
        <select name="hidden">
    	   <option value="-1">All</option>
           <option value="0">Enabled</option>
           <option value="1">Disabled</option>
        </select>
    	<span class="explanation"></span>
    </div>
    <div class="field">
    	<label>Start Date</label>
    	<input type="text" class="date-picker" name="date_from" value="<?php echo (isset($s['date_from']))? $s['date_from'] : ""?>" />
    	<span class="explanation"></span>
    </div>
    <div class="clear"></div>
    <div class="field">
    	<label>End Date</label>
    	<input type="text" class="date-picker" name="date_to" value="<?php echo (isset($s['date_to']))? $s['date_to'] : ""?>" />
    	<span class="explanation"></span>
    </div>
    <div class="clear"></div>
    <input type="submit" name="search" value="Search"/>
</form>
<?php if (isset($this->errors)):?>
    <div id="errors">
        <ul>
        <?php foreach ($this->errors as $error):?>
            <li><?php echo $error;?></li>
        <?php endforeach?>
        </ul>
    </div>
<?php endif;?>

<form method="post" action="admin/ads/manager">
<select name="status">
    <option value="0">Enable</option>
    <option value="1">Disable</option>
</select>
<input type="submit" name="apply" value="Apply" class="small_button"/>
<?php 
if(!empty($this->ads)) : 
$count = count($this->ads);
$page= @$_REQUEST['p'];
$size=8;
$pages = $count/$size + ($count%$size>0?1:0);
if (!$page || $page>$pages) $page=1;
$aux = array_chunk($this->ads,$size);
$this->ads = $aux[$page-1];
?>
<br />
<a href="admin/ads/manager/?p=all">Reset Filters</a>&nbsp;
<?php for($i=1;$i<=$pages;$i++): if ($i!=$page):?>
<a href="admin/ads/manager/?p=<?php echo $i?>&amp;f=<?php echo isset($_REQUEST['f'])?$_REQUEST['f']:"date_from";?>&amp;o=<?php echo isset($_REQUEST['o'])?$_REQUEST['o']:"ASC";?>"><?php echo $i?></a> &nbsp;
<?php else:?>
<b><?php echo $i?></b> &nbsp;
<?php endif;endfor;?>
<br /><br />
<?php endif;?>
<table>
    <thead>
    <tr class="gray">
        <td class="check"><input type="checkbox" id="all" /></td>
        <td>
            Ad Type
            <span class="links">
            <a href="admin/ads/manager/?p=1&f=ad_type&o=asc"><?php echo $arrow_up;?></a>
            <a href="admin/ads/manager/?p=1&f=ad_type&o=desc"><?php echo $arrow_down;?></a>
            </span>
        </td>
        <td>
            Page Code
            <span class="links">
            <a href="admin/ads/manager/?p=1&f=page&o=asc"><?php echo $arrow_up;?></a>
            <a href="admin/ads/manager/?p=1&f=page&o=desc"><?php echo $arrow_down;?></a>
            </span>
        </td>
        <td>
            Dentist Name
            <span class="links">
            <a href="admin/ads/manager/?p=1&f=dentist_id&o=asc"><?php echo $arrow_up;?></a>
            <a href="admin/ads/manager/?p=1&f=dentist_id&o=desc"><?php echo $arrow_down;?></a>
            </span>
        </td>
        <td>
            Target country
            <span class="links">
            <a href="admin/ads/manager/?p=1&f=country_id&o=asc"><?php echo $arrow_up;?></a>
            <a href="admin/ads/manager/?p=1&f=country_id&o=desc"><?php echo $arrow_down;?></a>
            </span>
        </td>
        <td>
            Start Date
            <span class="links">
            <a href="admin/ads/manager/?p=1&f=display_from&o=asc"><?php echo $arrow_up;?></a>
            <a href="admin/ads/manager/?p=1&f=display_from&o=desc"><?php echo $arrow_down;?></a>
            </span>
        </td>
        <td>
            End Date
            <span class="links">
            <a href="admin/ads/manager/?p=1&f=display_to&o=asc"><?php echo $arrow_up;?></a>
            <a href="admin/ads/manager/?p=1&f=display_to&o=desc"><?php echo $arrow_down;?></a>
            </span>
        </td>
        <td>Status</td>
    </tr>
    </thead>
    <tbody>
    <?php if(!empty($this->ads)):?>
    <?php foreach($this->ads as $a):?>
    <tr>
        <td class="check"><input type="checkbox" name="ads[]" value="<?php echo $a['id'];?>" /></td>
        <td>
            <img src="images/ads/<?php echo $a['ad_image']?>" alt="<?php echo $a['alt_text'];?>" title="<?php echo $a['alt_text'];?>"/><?php echo $a['ad_type']==1 ? "Banner" : "Coupon";?><br />
            <a href="admin/ads/edit-ad?id=<?php echo $a['id'];?>">Edit</a>|<a href="admin/ads/switch-ad?id=<?php echo $a['id'];?>"><?php echo ($a['hidden'])?"Enable":"Disable";?></a>
        </td>
        <td><?php echo $a['page'];?></td>
        <td><?php echo $this->dentists[$a['dentist_id']];?></td>
        <td><?php echo $this->countries[$a['country_id']];?></td>
        <td><?php echo $a['date_from'];?></td>
        <td><?php echo $a['date_to'];?></td>
        <td><?php echo ($a['hidden']) ? "Inactive" : "Active";?></td>
    </tr>
    <?php endforeach;?>
    <?php endif;?>
    </tbody>
    <tr class="gray">
        <td class="check"><input type="checkbox" id="all_bottom" /></td>
        <td>Ad Type</td>
        <td>Page Code</td>
        <td>Dentist Name</td>
        <td>Target Country</td>
        <td>Start Date</td>
        <td>End Date</td>
        <td>Status</td>
    </tr>
</table>
<br />
<?php if(!empty($this->ads)):?>
<a href="admin/ads/manager/?p=all">Reset Filters</a>&nbsp;
<?php for($i=1;$i<=$pages;$i++): if ($i!=$page):?>
<a href="admin/ads/manager/?p=<?php echo $i?>&amp;f=<?php echo isset($_REQUEST['f'])?$_REQUEST['f']:"date_from";?>&amp;o=<?php echo isset($_REQUEST['o'])?$_REQUEST['o']:"ASC";?>"><?php echo $i?></a> &nbsp;
<?php else:?>
<b><?php echo $i?></b> &nbsp;
<?php endif;endfor;?>
<br /><br />
<?php endif;?>
</form>
