<?php 
    if(isset($_REQUEST['search'])) $s = $_REQUEST;
    else if (isset($this->session->search_event)) {$s=$this->session->search_event;}
    $arrow_up = '<img class="arrow" src="images/arrow_up.png" alt="ASC" title="ASC"/>';
    $arrow_down = '<img class="arrow" src="images/arrow_down.png" alt="DESC" title="DESC"/>';
?>
<h1>Banners/Coupons Performance Report</h1>
<br /><br /><br /><br />
<form method="post" action="admin/ads/performance-report">
    <div class="field">
    	<label>Target Country</label>
    	<select name="country_id">
           <option value="-1">All</option>
           <?php foreach ($this->countries as $key=>$c): ?>
           <option value="<?php echo $key;?>" <?php if(isset($s['country_id'])&& $s['country_id']==$key) echo 'selected=="selected"';?>><?php echo $c;?></option>
           <?php endforeach;?>
        </select>
    	<span class="explanation"></span>
    </div>
    <div class="field">
    	<label>Page</label>
    	<select name="page" >
            <option value="0">All</option>
            <?php foreach ($this->pages as $p):?>
            <option value="<?php echo $p['code'];?>"><?php echo $p['title'];?></option>    
            <?php endforeach;?>
        </select>
    	<span class="explanation"></span>
    </div>
    <div class="field">
    	<label>Start Date</label>
    	<input type="text" class="date-picker" name="date_from" value="<?php echo (isset($s['date_from']))? $s['date_from'] : ""?>" />
    	<span class="explanation"></span>
    </div>
    <div class="clear"></div>
    <div class="field">
    	<label>End Date</label>
    	<input type="text" class="date-picker" name="date_to" value="<?php echo (isset($s['date_to']))? $s['date_to'] : ""?>" />
    	<span class="explanation"></span>
    </div>
    <div class="clear"></div>
    <input type="submit" name="search" value="Search"/>
</form>
<?php if (isset($this->errors)):?>
    <div id="errors">
        <ul>
        <?php foreach ($this->errors as $error):?>
            <li><?php echo $error;?></li>
        <?php endforeach?>
        </ul>
    </div>
<?php endif;?>

<form method="post" action="admin/ads/performance-report">
<?php 
if(!empty($this->ads)) : 
$count = count($this->ads);
$page= @$_REQUEST['p'];
$size=8;
$pages = $count/$size + ($count%$size>0?1:0);
if (!$page || $page>$pages) $page=1;
$aux = array_chunk($this->ads,$size);
$this->ads = $aux[$page-1];
?>
<br />
<a href="admin/ads/performance-report/?p=all">Reset Filters</a>&nbsp;
<?php for($i=1;$i<=$pages;$i++): if ($i!=$page):?>
<a href="admin/ads/performance-report/?p=<?php echo $i?>&amp;f=<?php echo isset($_REQUEST['f'])?$_REQUEST['f']:"date_from";?>&amp;o=<?php echo isset($_REQUEST['o'])?$_REQUEST['o']:"ASC";?>"><?php echo $i?></a> &nbsp;
<?php else:?>
<b><?php echo $i?></b> &nbsp;
<?php endif;endfor;?>
<br /><br />
<?php endif;?>
<table>
    <thead>
    <tr class="gray">
        <td>
            Ad Type
            <span class="links">
            <a href="admin/ads/performance-report/?p=1&f=ad_type&o=asc"><?php echo $arrow_up;?></a>
            <a href="admin/ads/performance-report/?p=1&f=ad_type&o=desc"><?php echo $arrow_down;?></a>
            </span>
        </td>
        <td>
            Page Code
            <span class="links">
            <a href="admin/ads/performance-report/?p=1&f=page&o=asc"><?php echo $arrow_up;?></a>
            <a href="admin/ads/performance-report/?p=1&f=page&o=desc"><?php echo $arrow_down;?></a>
            </span>
        </td>
        <td>
            Target country
            <span class="links">
            <a href="admin/ads/performance-report/?p=1&f=country_id&o=asc"><?php echo $arrow_up;?></a>
            <a href="admin/ads/performance-report/?p=1&f=country_id&o=desc"><?php echo $arrow_down;?></a>
            </span>
        </td>
        <td>
            Start Date
            <span class="links">
            <a href="admin/ads/performance-report/?p=1&f=display_from&o=asc"><?php echo $arrow_up;?></a>
            <a href="admin/ads/performance-report/?p=1&f=display_from&o=desc"><?php echo $arrow_down;?></a>
            </span>
        </td>
        <td>
            End Date
            <span class="links">
            <a href="admin/ads/performance-report/?p=1&f=display_to&o=asc"><?php echo $arrow_up;?></a>
            <a href="admin/ads/performance-report/?p=1&f=display_to&o=desc"><?php echo $arrow_down;?></a>
            </span>
        </td>
        <td>
            Impressions
            <span class="links">
            <a href="admin/ads/performance-report/?p=1&f=impression_counter&o=asc"><?php echo $arrow_up;?></a>
            <a href="admin/ads/performance-report/?p=1&f=impression_counter&o=desc"><?php echo $arrow_down;?></a>
            </span>
        </td>
        <td>
            Clicks
            <span class="links">
            <a href="admin/ads/performance-report/?p=1&f=click_counter&o=asc"><?php echo $arrow_up;?></a>
            <a href="admin/ads/performance-report/?p=1&f=click_counter&o=desc"><?php echo $arrow_down;?></a>
            </span>
        </td>
        <td>CTR</td>
    </tr>
    </thead>
    <tbody>
    <?php if(!empty($this->ads)):?>
    <?php foreach($this->ads as $a):?>
    <tr>
        <td>
            <img src="images/ads/<?php echo $a['ad_image']?>" alt="<?php echo $a['alt_text'];?>" title="<?php echo $a['alt_text'];?>"/><?php echo $a['ad_type']==1 ? "Banner" : "Coupon";?><br />
        </td>
        <td><?php echo $a['page'];?></td>
        <td><?php echo $this->countries[$a['country_id']];?></td>
        <td><?php echo $a['date_from'];?></td>
        <td><?php echo $a['date_to'];?></td>
        <td><?php echo $a['impression_counter'];?></td>
        <td><?php echo $a['click_counter'];?></td>
        <td><?php 
            $ctr = ($a['impression_counter']?100.0*$a['click_counter']/$a['impression_counter'] : 0);
            $p = explode('.',$ctr);
            if(!isset($p[1])) $p[1]='00';
            else $p[1] = substr($p[1],0,2);
            $ctr = implode('.',$p);
            echo $ctr;?>
        </td>
    </tr>
    <?php endforeach;?>
    <?php endif;?>
    </tbody>
    <tr class="gray">
        <td>Ad Type</td>
        <td>Page Code</td>
        <td>Target Country</td>
        <td>Start Date</td>
        <td>End Date</td>
        <td>Impressions</td>
        <td>Clicks</td>
        <td>CTR</td>
    </tr>
</table>
<br />
<?php if(!empty($this->ads)):?>
<a href="admin/ads/performance-report/?p=all">Reset Filters</a>&nbsp;
<?php for($i=1;$i<=$pages;$i++): if ($i!=$page):?>
<a href="admin/ads/performance-report/?p=<?php echo $i?>&amp;f=<?php echo isset($_REQUEST['f'])?$_REQUEST['f']:"date_from";?>&amp;o=<?php echo isset($_REQUEST['o'])?$_REQUEST['o']:"ASC";?>"><?php echo $i?></a> &nbsp;
<?php else:?>
<b><?php echo $i?></b> &nbsp;
<?php endif;endfor;?>
<br /><br />
<?php endif;?>
</form>
