<div id="logo-top">
    <a href ="
    <?=
    $this->url(
            array( 'module' => 'default' ,
        'controller' => 'index' ,
        'action' => 'index' ) , 'default' , true
    )
    ?>
       ">
        <img src="/theme/default/image/logo-top.png">
    </a>
</div>
<div id="dataUser">
    <? if ( Zend_Auth::getInstance()->hasIdentity() ): ?>
        <div id="userData">
            <?= $this->translate( 'Bienvenido' ) . ' ' . $this->authUser ?>
            <a href="<?=
        $this->url( array(
            'module' => 'default' ,
            'controller' => 'usuario' ,
            'action' => 'logout' ) , 'default' , true )
            ?>">Logout</a>

        </div>
        <div id="formIdioma">
            <form action="<?= $this->escape( $this->formIdiomaPais->getAction() ) ?>"
                  method="<?= $this->escape( $this->formIdiomaPais->getMethod() ) ?>">

                <div id="pais">
                    <?= $this->formIdiomaPais->pais; ?>
                </div>
                <div id="idioma">
                    <?= $this->formIdiomaPais->idioma; ?>
                </div>
                <div id="recordar">
                    <?= $this->formIdiomaPais->recordar; ?>
                </div>
                <div id="button">
                    <?= $this->formIdiomaPais->submit; ?>
                </div>
            </form>
        </div>
    <? endif; ?>

</div>

