<div id="logo-top">
    <a href ="
    <?=
    $this->url(
            array( 'module' => 'default' ,
        'controller' => 'index' ,
        'action' => 'index' ) , 'default' , true
    )
    ?>
       ">
        <img src="/theme/default/image/logo-top.png">
    </a>

</div>

<div id="lang-selection-top">
    <!-- Get by PHP function -->
    <a href="
    <?=
    $this->url( array(
        'module' => 'default' ,
        'controller' => 'idioma' ,
        'action' => 'english' ) , 'default' , true )
    ?>
       ">
           <?= $this->translate( 'English' ) ?>
    </a> |
    <a href="
    <?=
    $this->url( array(
        'module' => 'default' ,
        'controller' => 'idioma' ,
        'action' => 'spanish' ) , 'default' , true )
    ?>
       ">
           <?= $this->translate( 'Spanish' ) ?>
    </a> |
    <a href="<?=
           $this->url( array(
               'module' => 'default' ,
               'controller' => 'idioma' ,
               'action' => 'aleman' ) , 'default' , true )
           ?>
       ">
           <?= $this->translate( 'Deutsch' ) ?>
    </a>
    |
    <a href="<?=
           $this->url( array(
               'module' => 'default' ,
               'controller' => 'idioma' ,
               'action' => 'polonia' ) , 'default' , true )
           ?>
       ">
           <?= $this->translate( 'Polish' ) ?>
    </a>
</div>

<div>
    Bienvenido 
    <?=
    Zend_Auth::getInstance()->hasIdentity() ? $this->authUser : $this->translate( 'Visitante' )
    ?>

    <? if ( Zend_Auth::getInstance()->hasIdentity() ): ?>
        <a href="<?=
    $this->url( array(
        'module' => 'default' ,
        'controller' => 'usuario' ,
        'action' => 'logout' ) , 'default' , true )
        ?>">Logout</a>
       <?php else: ?>
        <a href="<?=
       $this->url( array(
           'module' => 'default' ,
           'controller' => 'usuario' ,
           'action' => 'index' ) , 'default' , true )
           ?>">Login</a> |
       <? endif; ?>
</div>
