<ul>
    <?
    $objcategorias = new Mtt_Models_Bussines_Categoria();
    foreach ( $objcategorias->listar() as $categoria )
        {
        ?>
        <li>
            <a href="
            <?=
            $this->url(
                    array( 'controller' => 'categoria' ,
                'action' => 'index' ,
                'id' => $this->escape( $categoria->id ) ) , null , true
            )
            ?>">
                <span>
    <?= $this->escape( $categoria->title ) ?>
                </span>

            </a>
        </li>
        <?
        }
    ?>
</ul>