<?
$arrayCategorias = array(
    'others' => $this->translate( 'others' ) ,
    'apparatus-general-lab' => $this->translate( 'apparatus-general-lab' ) ,
    'cardio-devices' => $this->translate( 'cardio-devices' ) ,
    'balances' => $this->translate( 'balances' ) ,
    'centrifugues' => $this->translate( 'centrifugues' ) ,
    'respirators' => $this->translate( 'respirators' ) ,
    'endoscopy-devices' => $this->translate( 'endoscopy-devices' ) ,
    'microscopes' => $this->translate( 'microscopes' ) ,
    'imaging-systems' => $this->translate( 'imaging-systems' ) ,
    'chirurgical-devices' => $this->translate( 'chirurgical-devices' ) ,
    'monitoring-devices' => $this->translate( 'monitoring-devices' ) ,
    'perfusors-pumps' => $this->translate( 'perfusors-pumps' ) ,
    'ultrasound' => $this->translate( 'ultrasound' ) ,
    'incubators' => $this->translate( 'incubators' ) ,
    'autoclaves' => $this->translate( 'autoclaves' ) ,
    'coolers-freezers' => $this->translate( 'coolers-freezers' ) ,
    'medical-furnitures-beds' => $this->translate( 'medical-furnitures-beds' ) ,
    'x-ray' => $this->translate( 'x-ray' ) ,
    'neu-demoger-te' => $this->translate( 'neu-demoger-te' )
);
?>

<ul>
    <?
    $objcategorias = new Mtt_Models_Bussines_Categoria();
    foreach ( $objcategorias->listar() as $categoria )
        {
        ?>
        <li>
            <a href="
            <?=
            $this->url(
                    array(
                'slug' => $categoria->slug
                    )
                    , 'slugCategory' , true
            )
            ?>" title="<?= $categoria->slug ?>">
                <span>
                    <?= $arrayCategorias[$categoria->slug]; ?>
                </span>

            </a>
        </li>
        <?
        }
    ?>
</ul>