<div id="sections-buttons-top">
    <ul>
        <li class="selected">
            <span>
                <a href="
                <?= $this->url( array( 'controller' => 'index' ,
                    'action' => 'index' ) , null , true ) ?>">

                    <?= $this->translate( 'home' ); ?>
                </a>  
            </span>
        </li>
        <li>
            <span>

                <a href="
                <?= $this->url( array( 'controller' => 'equipo' ,
                    'action' => 'index' ) , null , true ) ?>">

                    <?= $this->translate( 'buy equipment' ); ?>
                </a>  
            </span>

        </li>
        <li>
            <span>

                <a href="
                <?= $this->url( array( 'controller' => 'vender' ,
                    'action' => 'index' ) , null , true ) ?>">
                       <?= $this->translate( 'sell/trade-in Equipment' ); ?>

                </a>  
            </span>

        </li>
        <li>
            <span>
                <a href="
                <?= $this->url( array( 'controller' => 'Servicios' ,
                    'action' => 'index' ) , null , true ) ?>">
                       <?= $this->translate( 'services' ); ?>
                </a>  
            </span>

        </li>
        <li>
            <span>
                <a href="
                <?= $this->url( array( 'controller' => 'contacto' ,
                    'action' => 'index' ) , null , true ) ?>">
                       <?= $this->translate( 'contact us' ); ?>

                </a>  
            </span>
        </li>
        <li>
            <span>
                <a href="
                <?= $this->url( array( 'controller' => 'usuario' ,
                    'action' => 'index' ) , null , true ) ?>">
                       <?= $this->translate( 'my account' ); ?>

                </a> 
            </span>
        </li>
    </ul> 

</div>