<div id="navegacion" class="container_16"> 
		<ul id="mainlevel">
            <li>
                <a href="#">Home</a>
            </li>
            <li>
                <a href="#">Buy Equipment</a>
            </li>
            <li>
                <a href="#">Sell / Trade-in Equipment</a>
            </li>
            <li>
                <a href="#">Services</a>
            </li>
            <li>
                <a href="#">Contact Us</a>
            </li>
            <li>
                <a href="#">My Account</a>
            </li>
        </ul> 
	</div> 