<div id="sections-buttons-top">
    <ul>
        <li  id ="1">
            <span>
                <a href="
                <?= $this->url( array( 'controller' => 'index' ,
                    'action' => 'index' ) , 'default' , true ) ?>">

                    <?= $this->translate( 'Home' ); ?>
                </a>  
            </span>
        </li>
        <li  id ="2" >
            <span>

                <a href="
                <?= $this->url( array( 'controller' => 'equipo' ,
                    'action' => 'index' ) , 'default' , true ) ?>">

                    <?= $this->translate( 'Buy equipment' ); ?>
                </a>  
            </span>

        </li>
        <li  id ="3" >
            <span>

                <a href="
                <?= $this->url( array( 'controller' => 'vender' ,
                    'action' => 'index' ) , 'default' , true ) ?>">
                       <?= $this->translate( 'Sell/trade-in Equipment' ); ?>

                </a>  
            </span>

        </li>
        
        <li  id ="4" >
            <span>
                <a href="
                <?= $this->url( array( 'controller' => 'contactus' ,
                    'action' => 'index' ) , 'default' , true ) ?>">
                       <?= $this->translate( 'Contact us' ); ?>

                </a>  
            </span>
        </li>
        <li  id ="5" onclick="funcion1(this.id)" >
            <span>
                <a href="
                <?= $this->url( array( 'controller' => 'usuario' ,
                    'action' => 'index' ) , 'default' , true ) ?>">
                       <?= $this->translate( 'my account' ); ?>

                </a> 
            </span>
        </li>
    </ul> 

</div>