<div id="leftcontainerBox" style="position:fixed; top:250px; left:10px; width: 100px;">


    <div class="buttons"> 

        <iframe src="http://www.facebook.com/plugins/like.php?app_id=204002202992819&amp;href=http%3A%2F%2Fwww.facebook.com%2Fpages%2FMedTechTrade%2F140425816037036%3Fsk%3Dapp_266146960078364&amp;send=false&amp;layout=box_count&amp;width=150&amp;show_faces=false&amp;action=like&amp;colorscheme=light&amp;font=verdana&amp;height=90" 
                scrolling="no" frameborder="0" 
                style="border:none; overflow:hidden; width:90px; height:62px;" 
                allowTransparency="true">

        </iframe>
    </div>
    <!--    <div class="buttons"> 
            <iframe src="http://platform.twitter.com/widgets/tweet_button.html#_=1314889403009&amp;count=vertical&amp;id=twitter_tweet_button_0&amp;lang=en&amp;original_referer=http%3A%2F%2Fwww.emenia.es%2Fcreando-un-menu-vertical-desplegable-con-jquery%2F&amp;text=Creando%20un%20men%C3%BA%20vertical%20desplegable%20con%20jQuery&amp;url=http%3A%2F%2Fwww.emenia.es%2Fcreando-un-menu-vertical-desplegable-con-jquery%2F&amp;via=JuanDBB_Emenia"
                    allowtransparency="true" 
                    frameborder="0" scrolling="no" 
                    class="twitter-share-button twitter-count-vertical" 
                    style="width: 55px; height: 62px; " title="Twitter For Websites: Tweet Button">
    
            </iframe>
        </div>-->

</div>