<div style="border-color: #20A1D2;
     border-bottom-width: 3px;
     border-style: solid;">
    <div style="border-color: #177FAD;
         border-bottom-width: 4px;
         border-style: solid;">
        <div id="wrap">
            <div id="userMenu">
                <ul id="nav-user">
                    <li><a href="#"><span>
                                <?= $this->translate( 'perfil' ) ?>
                            </span></a>
                        <ul>
                            <li><a href="#"><span>
                                        <?= $this->translate( 'mi perfil' ) ?>
                                    </span></a></li>
                            <li><a href="#"><span>
                                        <?= $this->translate( 'configuraciones' ) ?>
                                    </span></a></li>
                            <li><a href="#"><span>
                                        <?= $this->translate( 'alerta' ) ?>
                                    </span></a></li>

                        </ul>
                    </li>
                    <li>
                        <a href="#">
                            <span><?= $this->translate( 'compras' ) ?></span>
                        </a>
                        <ul>
                            <li>
                                <a href="#">
                                    <span>
                                        <?= $this->translate( 'reservas' ) ?>
                                    </span>
                                </a>
                            </li>
                            <li>
                                <a href="#">
                                    <span>
                                        <?= $this->translate( 'compras activas' ) ?>
                                    </span>
                                </a>
                            </li>
                            <li>
                                <a href="#">
                                    <span>
                                        <?= $this->translate( 'pagos' ) ?>
                                    </span>
                                </a>
                            </li>
                            <li>
                                <a href="#">
                                    <span>
                                        <?= $this->translate( 'preguntas' ) ?>
                                    </span>
                                </a>
                            </li>

                        </ul>
                    </li>
                    <li>
                        <a href="#">
                            <?= $this->translate( 'ventas' ) ?>
                        </a>
                        <ul>
                            <li>
                                <a href="#">
                                    <span>
                                        <?= $this->translate( 'ingresar nuevo equipo' ) ?>
                                    </span>
                                </a>
                            </li>
                            <li>
                                <a href="#">
                                    <span>
                                        <?= $this->translate( 'mis equipos' ) ?>
                                    </span>
                                </a>
                            </li>
                            <li>
                                <a href="#">
                                    <span>
                                        <?= $this->translate( 'equipos pendientes' ) ?>
                                    </span>
                                </a>
                            </li>
                            <li>
                                <a href="#">
                                    <span>
                                        <?= $this->translate( 'equipos activados' ) ?>
                                    </span>
                                </a>
                            </li>
                            <li>
                                <a href="#">
                                    <span>
                                        <?= $this->translate( 'equipos vendidos' ) ?>
                                    </span>
                                </a>
                            </li>
                            <li>
                                <a href="#">
                                    <span>
                                        <?= $this->translate( 'equipos no vendidos' ) ?>
                                    </span>
                                </a>
                            </li>

                        </ul>
                    </li>
                    <li>
                        <a href="#">
                            <?= $this->translate( 'herramientas' ) ?>
                        </a>
                        <ul>
                            <li>
                                <a href="#">
                                    <span>
                                        <?= $this->translate( 'busqueda' ) ?>
                                    </span>
                                </a>
                            </li>
                            <li>
                                <a href="#">
                                    <span>
                                        <?= $this->translate( 'mis busquedas guardadas' ) ?>
                                    </span>
                                </a>
                            </li>
                            <li>
                                <a href="#">
                                    <span>
                                        <?= $this->translate( 'favoritos' ) ?>
                                    </span>
                                </a>
                            </li>
                            <li>
                                <a href="#">
                                    <span>
                                        <?= $this->translate( 'contactar al admin' ) ?>
                                    </span>
                                </a>
                            </li>
                        </ul>
                    </li>
                    <li><a href="#"><?= $this->translate( 'salir' ) ?></a></li>


                </ul>
            </div>
            <div id="menuAction">

            </div>
        </div>

    </div>
</div>

