<?= $this->doctype(); ?>
<html>
    <head>
        <?= $this->headMeta() ?>        
        <?= $this->headTitle() ?> 
        <link href="/images/favicon.ico" rel="shortcut icon" type="image/x-icon" />
        <?= $this->headLink()->prependStylesheet( '/theme/default/css/reset.css' )
                ->headLink()->appendStylesheet( '/theme/default/css/default.css' ) ?> 
        
        <?= $this->headLink(); ?>
        <?= $this->jQuery() ?>
        <?= $this->headScript()->appendFile( 'https://apis.google.com/js/plusone.js' ); ?> 
        <?= $this->headScript() ?> 

    </head>
    <body>
        <?= $this->render( '_redes.phtml' ); ?>
        <div id="wrap-top" class="wrapper">
            <div id="section-top" class="section">
                <?= $this->render( '_header.phtml' ); ?>
                <?= $this->render( '_navegacion.phtml' ); ?>
            </div>
        </div>
        <div id="wrap-middle" class="wrapper">
            <div id="section-middle" class="section">
                <div id="section-middle-categories">
                    <?= $this->render( '_menucategories.phtml' ); ?>
                    <div id="section-middle-list">
                        <span id="section-middle-list-advice">
                            We are looking<br/>for this used<br/>medical<br/>equipment:<br/></span>
                        <br/>
                        <a href="#"><span>Link to the list</span></a>
                    </div>
                </div>
                <div id="section-middle-body">

                    <?= $this->render( '_messages.phtml' ); ?>

                    <?= $this->layout()->content ?>

                </div>
            </div>
        </div>
        <?= $this->render( '_footer.phtml' ) ?>
    </body>
</html>