<h2>
    <?= $this->translate( 'Dashboard' ); ?>
</h2>
<p class="user-index-welcome">

    <?= $this->translate( 'Welcome' ) ?>
    Mr./Ms. <?= $this->authUser; ?> 
    <?=
    $this->translate(
            'to MedTechTrade. Please find and administrate
                your medical equipment in this section.'
    );
    ?>
</p>

<div id="user-index-latest-equipment">
    <a href="#">
        <span>
            <?= $this->translate( 'Last uploaded devices' ); ?>
        </span>
    </a>
    <? Zend_Debug::dump( $this->lastequipos ); ?>

    <table>
        <thead>
        <td><?= $this->translate( 'imagen' ) ?></td>
        <td><?= $this->translate( 'manufacturer' ) ?></td>
        <td><?= $this->translate( 'categoria' ) ?></td>
        <td><?= $this->translate( 'equipo' ) ?></td>
        <td><?= $this->translate( 'modelo' ) ?></td>
        <td><?= $this->translate( 'fecha de manufacturacion' ) ?></td>
        <td><?= $this->translate( 'acciones' ) ?></td>
        </thead>
        <tbody>
            <? foreach ( $this->lastequipos as $equipo ): ?>
                <tr>
                    <td>

                    </td>
                    <td>
                        <?= $equipo->fabricante ?>
                    </td>
                    <td>
                        <?= $equipo->categoria ?>
                    </td>
                    <td>
                        <?= $equipo->nombre ?>
                    </td>
                    <td>
                        <?= $equipo->modelo ?>
                    </td>
                    <td>
                        <?= $equipo->fechafabricacion ?>
                    </td>
                    <td>
                        acciones
                    </td>
                </tr>
            <? endforeach; ?>


        </tbody>
    </table> 

    <ul>

        <li>
            Imagen 1
        </li>
        <li>
            Imagen 2
        </li>
    </ul>
</div>

<div id="user-index-favorites" >
    <a href="#">
        <span>
            My favorites 
        </span>
    </a>
</div>

<div id="user-index-latest-search" >
    <a href="#">
        <span>
            Latest search matches  
        </span>
    </a>
</div>
<div class="clear">

</div>


