<h2> <?= $this->translate('paises') ?>:
    <?php
    $link = $this->url(
            array(
        'module' => 'admin',
        'controller' => 'paises',
        'action' => 'nuevo'), null, true
            )
    ?>
    <a href="<?= $link?>"
       title="<?= $this->translate('nuevo'); ?>" >
        <img class ="imagen-new" />
    </a>
</h2>

<table border="1" class="listado">
    <thead>
        <tr>
            <th><?= $this->translate('pais') ?></th>
            <th><?= $this->translate('codigo') ?></th>
            <th><?= $this->translate('acciones') ?></th>
        </tr>
    </thead>
    <tbody>
        <?php foreach ($this->paises as $pais): ?>

    <?php $id = $pais->id; ?>
            <tr class="<?= $pais->active ? 'activo' : 'inactivo' ?>">

                <td>
    <?= $this->escape($pais->nombre) ?>
                </td>
                <td>
    <?= $this->escape($pais->code) ?>
                </td>
                <td>

                    <?php
                    $link = $this->url(
                            array(
                                'module' => 'admin',
                                'controller' => 'paises',
                                'action' => 'editar',
                                'id' => $id))
                    ?>
                    <a href="<?= $link ?>"
                       title="<?= $this->translate('editar') ?>">
                        <img class ="imagen-edit" />
                    </a>

                    <?php
                    $link = $this->url(
                            array(
                                'module' => 'admin',
                                'controller' => 'paises',
                                'action' => 'borrar',
                                'id' => $id)
                            )
                    ?>
                    <a href="<?= $link ?>" onclick="return confirm(
                       <?= $this->translate('¿Estás seguro?'); ?>
                        )"
                        title="<?= $this->translate('Borrar'); ?>">
                        <img class ="imagen-delete" />
    
                    </a>

                    <? if ($pais->active): ?>
                        <?
                        $link = $this->url(
                                array(
                                    'module' => 'admin',
                                    'controller' => 'paises',
                                    'action' => 'desactivar',
                                    'id' => $id))
                        ?>
                        <a href="<?= $link ?>"
                           title="<?= $this->translate('Desactivar'); ?>">
                        
                            <img class ="imagen-desactivar" />
                        </a>
                    <? else: ?>
                        <?
                        $link = $this->url(
                                array('module' => 'admin',
                                    'controller' => 'paises',
                                    'action' => 'activar',
                                    'id' => $id))
                        ?>
                        <a href="<?= $link ?>"
                           title="<?= $this->translate('Activar'); ?>">
                        
                            <img class ="imagen-activar" />
                        </a>
    <? endif; ?>

                </td>
            </tr>
<?php endforeach; ?>
    </tbody>
</table>
<br />
<?=
$this->paginationControl(
        $this->paises, 'Sliding', 'paises/_pag.phtml'
);
?>


