<h2>Compras de equipos activos</h2>
<table border="1" class="listado">
    <thead>
        <tr>
            <th></th>
            <th>Equipo</th>
            <th>Precio</th>
            <th>Fecha</th>
            <th>Nro Cuotas</th>
            <th>Forma de Pago</th>
        </tr>
    </thead>
    <tbody>
        <?php foreach ($this->operaciones as $operacion): ?>
            <tr>
                <td></td>
                <td>
                    <?= $this->escape($operacion->nombre) ?>
                </td>
                <td><?= $this->escape($operacion->precio) ?></td>
                <td><?= $this->escape($operacion->fecha) ?></td>
                <td><?= $this->escape($operacion->nrocuotas) ?></td>
                <td><?= $this->escape($operacion->formapago) ?></td>
                <td>
                     <?php
                    $link =
                            $this->url(
                            array(
                            'slug' => $operacion->slug
                            ), 'slugEquipment', true)
                    ?>

                    <a href="<?= $link ?>" >
                        <?= $this->translate('ver equipo') ?>
                    </a>
                </td>
            </tr>
        <?php endforeach; ?>
    </tbody>
</table>
<br />
