<br/>
<?php $u = $this->usu; ?>
<h3><?= $this->translate( 'Go to' ) ?></h3>
<div class="sidebar">
    <ul>
        <li>
            <a href="<?php echo $this->baseUrl( '/manufacturers/index' ) ?>" 
               class="sub <?php echo $this->v_manu; ?>" id = "navFact">
               <?php echo "Manufacturers" ?></a></li>
       
        <li>
            <a href="<?php echo $this->baseUrl( '/offices/index/status/A' ) ?>" 
               class="sub <?php echo $this->v_offi; ?>" id = "navBuild1">
               <?php echo "Suppliers" ?>
            </a>
        </li>
        <li>
            <a href="<?php echo $this->baseUrl( '/users/index/status/A' ) ?>" 
               class="sub <?php echo $this->v_user; ?>" id = "navUsers">
               <?php echo "Users" ?>
            </a>
        </li>
        <li>
            <a href="<?php echo $this->baseUrl( '/status/index/status/A' ) ?>" 
               class="sub <?php echo $this->v_status; ?>" id = "navStatus">
               <?php echo "Negotiation Status" ?>
            </a>
        </li>
    </ul>
</div>