<div id="nav">
            <ul>

                <li>
                    <a href="
                    <?=
                    $this->url( array(
                        'module' => 'admin' ,
                        'controller' => 'index' ,
                        'action' => 'index' ) , null , true )
                    ?>">
                           <?= $this->translate( 'Administration' ); ?>
                    </a>
                </li>
                <li>
                    <a href="
                    <?=
                    $this->url( array(
                        'module' => 'admin' ,
                        'controller' => 'index' ,
                        'action' => 'index' ) , null , true )
                    ?>">
                           <?= $this->translate( 'Administration' ); ?>
                    </a>
                </li>

            </ul>
        </div>