<?= $this->doctype() ?>
<head>
    <?= $this->headMeta() ?>        
    <?= $this->headTitle() ?> 
    <link href="/images/favicon.ico" rel="shortcut icon" type="image/x-icon" />
    <?
    $this->headLink()->appendStylesheet( '/theme/admin/css/reset-fonts-grids.css' )
            ->appendStylesheet( '/theme/admin/css/grids-min.css' )
            ->appendStylesheet( '/theme/admin/css/base-min.css' )
            ->appendStylesheet( '/theme/admin/css/style.css' );
    ?>
    <?= $this->headLink() ?>        
    <?= $this->jQuery() ?>        
    <?= $this->headScript() ?> 

</head>
<body>

    <div id="custom-doc" class="yui-t6">

        <div id="hd">

            <div id="util">			
                <div class="userIdentity">
                    <?= $this->authUser ?> |
                    <a href="
                    <?=
                    $this->url( array(
                        'module' => 'admin' ,
                        'controller' => 'login' ,
                        'action' => 'logout' ) , null , true )
                    ?>">
                           <?= $this->translate( 'Logout' ); ?>
                    </a>
                </div>
            </div>


            <h1>
                <img src="/theme/admin/image/logo-Medtechtrade.png" alt="Medtechtrade" />
                MedtechTrade
                <span class="slogan">Sourcing Management System</span>
            </h1>


        </div>

        <?= $this->render( '_navegacion.phtml' ); ?>
    </div>

    <div id="bd">
        <?= $this->layout()->content ?>

        <div class="yui-b">

            <div class="module">
                <div class="inner">
                    
                    <div class="sidebar">

                        

                    </div>

                </div>
            </div>

        </div>
    </div>

    <div id="ft">
        Medtechtrade
    </div>



</div>

</body>
</html>