<?php $r = $_REQUEST;?>
In progress
<form method="post">
    <div class="field">
        <label>Username or E-Mail:</label><br />
        <input type="text" name="username" value="<?php echo isset($r['username'])? $r['username']:''?>" />
    </div>
    <div class="button">
        <input type="submit" name="request" value="Send Me a New Password"/>
    </div>
</form>
<a href="admin">Login</a>
<?php if(isset($this->errors)):?>
    <div id="errors">
        <h1>Please correct the following error(s):</h1>
        <ul>
        <?php foreach($this->errors as $error):?>
            <li><?php echo $error;?></li>
        <?php endforeach;?>
        </ul>
    </div>
<?php endif;?>