<?php 
    $r=isset($_REQUEST['save']) ? $_REQUEST : $this->testimonial;
?>
<h1>Testimonial [Edit]</h1>
<br /><br /><br />
<?php if(isset($this->errors)):?>
    <?php $e = $this->errors;?>
<div id="errors">
    Please correct the errors. 
</div>
<?php endif;?>
<form method="post" action="admin/testimonial/edit-testimonial">
    <input type="hidden" name="id" value="<?php echo $r['id'];?>" />
    <div class="field">
    	<label>Business Name</label>
    	<input type="text" name="business" value="<?php echo $r['business']?>" readonly="readonly" />
    	<span class="explanation"></span>
    </div>
    <div class="field">
    	<label>Author Name</label>
    	<input type="text" name="author" value="<?php echo $r['author'];?>" />
    	<span class="explanation"></span>
    </div>
    <div class="field">
    	<label>Testimonial</label>
    	<textarea name="content" rows="5" cols="40" ><?php echo $r['content'];?></textarea>
    	<span class="explanation"></span>
    </div>
    <div class="field">
    	<label>Status</label>
    	<select name="status">
            <option value="0">Select a status...</option>
            <option value="1" <?php if($r['deleted']==-1) echo 'selected="selected"';?>>Pending</option>
            <option value="3" <?php if($r['deleted']==0 && $r['hidden']==0) echo 'selected="selected"';?>>Active</option>
            <option value="4" <?php if($r['deleted']==0 && $r['hidden']==1) echo 'selected="selected"';?>>Inactive</option>
        </select>
    	<span class="explanation"></span>
    </div>
    <div class="field">
    	<label>Creation Date</label>
    	<input type="text" name="creation_date" value="<?php echo $r['creation_date']?>" readonly="readonly"/>
    	<span class="explanation"></span>
    </div>
    <div class="field">
    	<label>Rating</label>
    	<select name="rating">
            <option value="1" <?php if($r['rating']==1) echo 'selected="selected"';?>>Unsatisfactory</option>
            <option value="2" <?php if($r['rating']==2) echo 'selected="selected"';?>>Fair</option>
            <option value="3" <?php if($r['rating']==3) echo 'selected="selected"';?>>Satisfactory</option>
            <option value="4" <?php if($r['rating']==4) echo 'selected="selected"';?>>Good</option>
            <option value="5" <?php if($r['rating']==5) echo 'selected="selected"';?>>Excellent</option>
        </select> 
    	<span class="explanation"></span>
    </div>
    <input type="submit" name="save" value="Save" />
</form>
