<?php $r=$_REQUEST;?>
<h1>Event [New]</h1>
<br /><br /><br />
<?php if(isset($this->errors)):?>
    <?php $e = $this->errors;?>
<div id="errors">
    Please correct the errors. 
</div>
<?php endif;?>
<form method="post" action="admin/event/add-event" enctype="multipart/form-data">
    <fieldset>
        <legend>Event Description</legend>
        <div class="field">
        	<label>Name</label>
        	<input type="text" name="name" value="<?php echo isset($r['name'])?$r['name']:"";?>" />
        	<span class="explanation"><?php echo isset($e['name'])?$e['name']:""?></span>
        </div>
        <div class="field">
        	<label>Subject</label>
        	<input type="text" name="subject" value="<?php echo isset($r['subject'])?$r['subject']:"";?>"/>
        	<span class="explanation"><?php echo isset($e['subject'])?$e['subject']:""?></span>
        </div>
        <div class="field">
        	<label>Event Type</label>
        	<select name="event_type">
                <option value="0">Please select...</option>
                <option value="Congress">Congress</option>
                <option value="Courses &amp; Seminars">Courses &amp; Seminars</option>
            </select>
        	<span class="explanation"><?php echo isset($e['event_type'])?$e['event_type']:""?></span>
        </div>
        <div class="field">
        	<label>Location</label>
        	<input type="text" name="location" value="<?php echo isset($r['location'])?$r['location']:"";?>" />
        	<span class="explanation"><?php echo isset($e['location'])?$e['location']:""?></span>
        </div>
        <div class="field">
        	<label>Start Date</label>
        	<input type="text" class="date-picker" name="date_from" value="<?php echo isset($r['date_from'])?$r['date_from']:"";?>" />
        	<span class="explanation"><?php echo isset($e['date_from'])?$e['date_from']:""?></span>
        </div>
        <div class="field">
        	<label>End Date</label>
        	<input type="text" class="date-picker" name="date_to" value="<?php echo isset($r['date_to'])?$r['date_to']:"";?>" />
        	<span class="explanation"><?php echo isset($e['date_to'])?$e['date_to']:""?></span>
        </div>
        <div class="field">
        	<label>Date Display</label>
        	<input type="text" name="date_display" value="<?php echo isset($r['date_display'])?$r['date_display']:"";?>" />
        	<span class="explanation"><?php echo isset($e['date_display'])?$e['date_display']:""?></span>
        </div>
    </fieldset>
    <fieldset>
        <legend>Upload an Event Logo</legend>
        <div class="field">
        	<label>Upload Event Logo</label>
        	<input type="file" name="logo" value="" />
        	<span class="explanation"><?php echo isset($e['logo'])?$e['logo']:""?></span>
        </div>
    </fieldset>
    <fieldset>
        <legend>Event Landing Page</legend>
        <div class="field">
        	<label>URL Address</label>
        	<input type="text" name="url" value="<?php echo isset($r['url'])?$r['url']:"";?>" />
        	<span class="explanation"></span>
        </div>
    </fieldset>
    <fieldset>
        <div class="field">
        	<label>Enable Event Display</label>
        	<input type="checkbox" name="hidden" value="0" <?php echo isset($r['hidden'])?'checked="checked"':"";?>/>
        	<span class="explanation"></span>
        </div>
    </fieldset>
    <input type="submit" name="save" value="Save" />
</form>
