<?php 
    if(isset($_REQUEST['search'])) $s = $_REQUEST;
    else if (isset($this->session->search_event)) {$s=$this->session->search_event;}
    $arrow_up = '<img class="arrow" src="images/arrow_up.png" alt="ASC" title="ASC"/>';
    $arrow_down = '<img class="arrow" src="images/arrow_down.png" alt="DESC" title="DESC"/>';
?>
<h1>Events Manager</h1>
<a href="admin/event/add-event" class="button">Add New</a>
<br /><br /><br />
<form method="post" action="admin/event/manager">
    <div class="field">
    	<label>Subject</label>
    	<input type="text" name="subject" value="<?php echo (isset($s['subject']))? $s['subject'] : ""?>" />
    	<span class="explanation"></span>
    </div>
    <div class="field">
    	<label>Event Type</label>
    	<select name="event_type">
           <option value="0">Please Select...</option> 
           <option value="Congress" <?php if(isset($s['event_type'])&& $s['event_type']=="Congress") echo 'selected=="selected"';?>>Congress</option>
           <option value="Courses &amp; Seminars" <?php if(isset($s['event_type'])&& $s['event_type']=="Courses & Seminars") echo 'selected=="selected"';?>>Courses &amp; Seminars</option>
        </select>
    	<span class="explanation"></span>
    </div>
    <div class="field">
    	<label>Event Name</label>
    	<input type="text" name="name" value="<?php echo (isset($s['name']))? $s['name'] : ""?>" />
    	<span class="explanation"></span>
    </div>
    <div class="field">
    	<label>Location</label>
    	<input type="text" name="location" value="<?php echo (isset($s['location']))? $s['location'] : ""?>" />
    	<span class="explanation"></span>
    </div>
    <div class="field">
    	<label>Start Date</label>
    	<input type="text" class="date-picker" name="date_from" value="<?php echo (isset($s['date_from']))? $s['date_from'] : ""?>" />
    	<span class="explanation"></span>
    </div>
    <div class="clear"></div>
    <div class="field">
    	<label>End Date</label>
    	<input type="text" class="date-picker" name="date_to" value="<?php echo (isset($s['date_to']))? $s['date_to'] : ""?>" />
    	<span class="explanation"></span>
    </div>
    <div class="clear"></div>
    <input type="submit" name="search" value="Search"/>
</form>
<?php if (isset($this->errors)):?>
    <div id="errors">
        <ul>
        <?php foreach ($this->errors as $error):?>
            <li><?php echo $error;?></li>
        <?php endforeach?>
        </ul>
    </div>
<?php endif;?>

<form method="post" action="admin/event/manager">
<select name="status">
    <option value="0">Activate</option>
    <option value="1">Inactivate</option>
</select>
<input type="submit" name="apply" value="Apply" class="small_button"/>
<?php 
if(!empty($this->events)) : 
$count = count($this->events);
$page= @$_REQUEST['p'];
$size=8;
$pages = $count/$size + ($count%$size>0?1:0);
if (!$page || $page>$pages) $page=1;
$aux = array_chunk($this->events,$size);
$this->events = $aux[$page-1];
?>
<br />
<a href="admin/event/manager/?p=all">Reset Filters</a>&nbsp;
<?php for($i=1;$i<=$pages;$i++): if ($i!=$page):?>
<a href="admin/event/manager/?p=<?php echo $i?>&amp;f=<?php echo isset($_REQUEST['f'])?$_REQUEST['f']:"date_from";?>&amp;o=<?php echo isset($_REQUEST['o'])?$_REQUEST['o']:"ASC";?>"><?php echo $i?></a> &nbsp;
<?php else:?>
<b><?php echo $i?></b> &nbsp;
<?php endif;endfor;?>
<br /><br />
<?php endif;?>
<table>
    <thead>
    <tr class="gray">
        <td class="check"><input type="checkbox" id="all" /></td>
        <td>
            Event Name
            <span class="links">
            <a href="admin/event/manager/?p=1&f=name&o=asc"><?php echo $arrow_up;?></a>
            <a href="admin/event/manager/?p=1&f=name&o=desc"><?php echo $arrow_down;?></a>
            </span>
        </td>
        <td>
            Location
            <span class="links">
            <a href="admin/event/manager/?p=1&f=location&o=asc"><?php echo $arrow_up;?></a>
            <a href="admin/event/manager/?p=1&f=location&o=desc"><?php echo $arrow_down;?></a>
            </span>
        </td>
        <td>
            Event Type
            <span class="links">
            <a href="admin/event/manager/?p=1&f=event_type&o=asc"><?php echo $arrow_up;?></a>
            <a href="admin/event/manager/?p=1&f=event_type&o=desc"><?php echo $arrow_down;?></a>
            </span>
        </td>
        <td>
            Subject
            <span class="links">
            <a href="admin/event/manager/?p=1&f=subject&o=asc"><?php echo $arrow_up;?></a>
            <a href="admin/event/manager/?p=1&f=subject&o=desc"><?php echo $arrow_down;?></a>
            </span>
        </td>
        <td>
            Start Date
            <span class="links">
            <a href="admin/event/manager/?p=1&f=date_from&o=asc"><?php echo $arrow_up;?></a>
            <a href="admin/event/manager/?p=1&f=date_from&o=desc"><?php echo $arrow_down;?></a>
            </span>
        </td>
        <td>
            End Date
            <span class="links">
            <a href="admin/event/manager/?p=1&f=date_to&o=asc"><?php echo $arrow_up;?></a>
            <a href="admin/event/manager/?p=1&f=date_to&o=desc"><?php echo $arrow_down;?></a>
            </span>
        </td>
        <td>Status</td>
    </tr>
    </thead>
    <tbody>
    <?php foreach($this->events as $e):?>
    <tr>
        <td class="check"><input type="checkbox" name="events[]" value="<?php echo $e['id'];?>" /></td>
        <td>
            <img src="images/eventlogos/<?php echo $e['logo']?>" alt=""/><?php echo $e['name']?><br />
            <a href="admin/event/edit-event?id=<?php echo $e['id'];?>">Edit</a>|<a href="admin/event/switch-event?id=<?php echo $e['id'];?>"><?php echo ($e['hidden'])?"Activate":"Inactivate";?></a>
        </td>
        <td><?php echo $e['location'];?></td>
        <td><?php echo $e['event_type'];?></td>
        <td><?php echo $e['subject'];?></td>
        <td><?php echo $e['date_from'];?></td>
        <td><?php echo $e['date_to'];?></td>
        <td><?php echo ($e['hidden']) ? "Inactive" : "Active";?></td>
    </tr>
    <?php endforeach;?>
    </tbody>
    <tr class="gray">
        <td class="check"><input type="checkbox" id="all_bottom" /></td>
        <td>Event Name</td>
        <td>Location</td>
        <td>Event Type</td>
        <td>Subject</td>
        <td>Start Date</td>
        <td>End Date</td>
        <td>Status</td>
    </tr>
</table>
<br />
<?php if(!empty($this->events)):?>
<a href="admin/event/manager/?p=all">Reset Filters</a>&nbsp;
<?php for($i=1;$i<=$pages;$i++): if ($i!=$page):?>
<a href="admin/event/manager/?p=<?php echo $i?>&amp;f=<?php echo isset($_REQUEST['f'])?$_REQUEST['f']:"date_from";?>&amp;o=<?php echo isset($_REQUEST['o'])?$_REQUEST['o']:"ASC";?>"><?php echo $i?></a> &nbsp;
<?php else:?>
<b><?php echo $i?></b> &nbsp;
<?php endif;endfor;?>
<br /><br />
<?php endif;?>
</form>