<div class="sub" style="width: 600px; opacity: 0; display: none; ">
    <ul>
        <li>
            <h2>
                <a href="#">
                    <?= $this->translate( 'My Purchases' ); ?>
                </a>
            </h2>
        </li>
        <li>
            <a href="
            <?=
            $this->url( array(
                'module' => 'admin' ,
                'controller' => 'equipo' ,
                'action' => 'index' ) , null , true )
            ?>">
                   <?= $this->translate( 'FAVORITOS' ) ?>
            </a>
        </li>
        <li>
            <a href="
            <?=
            $this->url( array(
                'module' => 'admin' ,
                'controller' => 'fabricante' ,
                'action' => 'index' ) , null , true )
            ?>">
                   <?= $this->translate( 'RESERVAS' ) ?>
            </a>
        </li>
        <li>
            <a href="
            <?=
            $this->url( array(
                'module' => 'admin' ,
                'controller' => 'fabricante' ,
                'action' => 'index' ) , null , true )
            ?>">
                   <?= $this->translate( 'COMPRAS ACTIVAS' ) ?>
            </a>
        </li>
        <li>
            <a href="
            <?=
            $this->url( array(
                'module' => 'admin' ,
                'controller' => 'fabricante' ,
                'action' => 'index' ) , null , true )
            ?>">
                   <?= $this->translate( 'MIS PREGUNTAS' ) ?>
            </a>
        </li>
        
        <li>
            <a href="
            <?=
            $this->url( array(
                'module' => 'admin' ,
                'controller' => 'fabricante' ,
                'action' => 'index' ) , null , true )
            ?>">
                   <?= $this->translate( 'MIS PAGOS' ) ?>
            </a>
        </li>
        <li>
            <a href="
            <?=
            $this->url( array(
                'module' => 'admin' ,
                'controller' => 'fabricante' ,
                'action' => 'index' ) , null , true )
            ?>">
                   <?= $this->translate( 'MIS Envios' ) ?>
            </a>
        </li>
        

    </ul>
</div>