<div class="row">
    <div class="fourcol">

        <img src="/theme/default/image/logo-top.png" alt="Medtechtrade" />

    </div>   
    <div class="eightcol last">

        <ul id="nav-admin">
            <li>
                Buscar: "Caja de Busqueda"
            </li>
            <li>
                <?= $this->translate( 'Welcome' ) ?>  :  <?= $this->authUser ?>
            </li>
            <li>
                <?= $this->translate( 'Date' ) ?>:  <?= Zend_Date::now() ?>
            </li>
            <li>
                <a href="<?=
                $this->Url(
                        array( 'module' => 'admin' ,
                            'controller' => 'login' ,
                            'action' => 'logout' )
                )
                ?>">
                       <?= $this->translate( 'Logout' ) ?>
                </a>
            </li>

        </ul>

    </div>   

</div>