<h2>Favoritos</h2>
<table border="1" class="listado">
    <tbody>
        <?php foreach ( $this->equipos as $equipo ): ?>

            <tr class="<?= $equipo->active
                            ? 'activo' : 'inactivo' ?>">
                <td >
                    <img src="/media/catalog/product/device-00.png" 
                    alt="<?= $equipo->equipo ?>">
                </td>
                <td>
                    <table>
                        <tr>
                            <td>
                                <?= $this->escape( $equipo->equipo ) ?>
                            </td>
                        </tr>
                        <tr>
                            <td>
                                <?= $this->escape( $equipo->preciocompra ) ?>
                            </td>
                        </tr>
                        <tr>
                            <td>
                                <?= $this->escape( $equipo->categoria ) ?>
                            </td>
                        </tr>
                        <tr>
                            <td>
                                <?= $this->escape( $equipo->estadoequipo ) ?>
                            </td>
                        </tr>
                        <tr>
                            <td>
                                <?= $this->escape( $equipo->fabricante ) ?>
                            </td>
                        </tr>
                        <tr>
                            <td>
                                <?= $this->escape( $equipo->calidad ) ?>
                            </td>
                        </tr>
                        <tr>
                            <td>
                                <?= $this->escape( $equipo->imageNombre ) ?>
                            </td>
                        </tr>
                    </table>
                </td>
               
            </tr>
        <?php endforeach; ?>
    </tbody>
</table>