<h2><?= $this->translate('equipos activos')?></h2>
<br />
<table border="1" class="listado">
    <thead>
        <tr>
            <th></th>
            <th><?= $this->translate('nombre') ?></th>
            <th><?= $this->translate('precio') ?></th>
            <th><?= $this->translate('categoria') ?></th>
            <th><?= $this->translate('estado') ?></th>
            <th><?= $this->translate('fabricante') ?></th>
            <th><?= $this->translate('calidad') ?></th>
            <th colspan ="2"><?= $this->translate('acciones') ?></th>
        </tr>
    </thead>
    <tbody>
        <?php foreach ($this->equipos as $equipo): ?>

            <tr class="<?= $equipo->active ? 'activo' : 'inactivo' ?>">
                <td>
                <?php
                $url = (is_null($equipo->image)) ?
                    '/theme/default/image/no_images.png' : 
                    '/media/catalog/product/'. $equipo->image
                ?>
                <img src="<?= $url?>" 
                     alt="<?= $equipo->equipo ?>"
                     width="24px" height="24px">
                </td>
                <td>
                    <?= $this->escape($equipo->equipo) ?>
                </td>
                <td>
                    <?= $this->escape($equipo->preciocompra) ?>
                </td>
                <td>
                    <?= $this->escape($equipo->categoria) ?>
                </td>
                <td>
                    <?= $this->escape($equipo->estadoequipo) ?>
                </td>
                <td>
                    <?= $this->escape($equipo->fabricante) ?>
                </td>
                <td>
                    <?= $this->escape($equipo->calidad) ?>
                </td>
                <td>
                    <?php
                    $link =
                            $this->url(
                            array(
                        'slug' => $equipo->slug
                            ), 'slugEquipment', true)
                    ?>

                    <a href="<?= $link ?>" 
                       title="<?= $this->translate('ver equipo') ?>" >
                   <img class ="imagen-see">
                    </a>
                </td>
                <td>
                    <?php
                    $link = $this->url(array('module' => 'user',
                        'controller' => 'equipo',
                        'action' => 'editar',
                        'id' => $equipo->id))
                    ?>
                    <a href="<?= $link ?>" 
                       title="<?= $this->translate('editar equipo')?>">
                        <img class ="imagen-edit">
                    </a>

                </td>

            </tr>
        <?php endforeach; ?>
    </tbody>
</table>
<?=
$this->paginationControl(
        $this->equipos , 'Sliding' , 'equipo/_pag.phtml'
);
?>