<h2><?= $this->translate('equipos activos')?></h2>
<br />
<table border="1" class="listado">
    <thead>
        <tr>
            <th><?= $this->translate('nombre') ?></th>
            <th><?= $this->translate('precio') ?></th>
            <th><?= $this->translate('categoria') ?></th>
            <th><?= $this->translate('estado') ?></th>
            <th><?= $this->translate('fabricante') ?></th>
            <th><?= $this->translate('calidad') ?></th>
            <th colspan ="2"><?= $this->translate('acciones') ?></th>
        </tr>
    </thead>
    <tbody>
        <?php foreach ($this->equipos as $equipo): ?>

            <tr class="<?= $equipo->active ? 'activo' : 'inactivo' ?>">

                <td>
                    <?= $this->escape($equipo->equipo) ?>
                </td>
                <td>
                    <?= $this->escape($equipo->preciocompra) ?>
                </td>
                <td>
                    <?= $this->escape($equipo->categoria) ?>
                </td>
                <td>
                    <?= $this->escape($equipo->estadoequipo) ?>
                </td>
                <td>
                    <?= $this->escape($equipo->fabricante) ?>
                </td>
                <td>
                    <?= $this->escape($equipo->calidad) ?>
                </td>
                <td>
                    <?php
                    $link =
                            $this->url(
                            array(
                        'slug' => $equipo->slug
                            ), 'slugEquipment', true)
                    ?>

                    <a href="<?= $link ?>" >
                        <?= $this->translate('ver equipo') ?>
                    </a>
                </td>
                <td>
                    <?php
                    $link = $this->url(array('module' => 'user',
                        'controller' => 'equipo',
                        'action' => 'editar',
                        'id' => $equipo->id))
                    ?>
                    <a href="<?= $link ?>">
                        <?= $this->translate('editar') ?>
                    </a>

                </td>

            </tr>
        <?php endforeach; ?>
    </tbody>
</table>
<?=
$this->paginationControl(
        $this->equipos , 'Sliding' , 'equipo/_pag.phtml'
);
?>