<h2> <?= $this->translate( 'equipos' ) ?>:</h2>

<!-- Filtrado -->
<?= $this->render( 'equipo/comp/_filter.phtml' ); ?>
<!-- fin del Filtrado -->

<!-- Aca Ira La Barra de Navegacion -->
<?= $this->render( 'equipo/comp/_nav.phtml' ); ?>
<!-- fin de la Barra de Navegacion -->

<table border="1" class="listado">
    <thead>
        <tr>
            <th><?= $this->translate( 'nombre' ) ?></th>
            <th><?= $this->translate( 'modelo' ) ?></th>
            <th><?= $this->translate( 'categoria' ) ?></th>
            <th><?= $this->translate( 'estado' ) ?></th>
            <th><?= $this->translate( 'usuario' ) ?></th>
            <th><?= $this->translate( 'fabricacion' ) ?></th>
            <th><?= $this->translate( 'publicacion' ) ?></th>
            <th><?= $this->translate( 'fabricante' ) ?></th>
            <th><?= $this->translate( 'pais' ) ?></th>
            <th><?= $this->translate( 'operaciones' ) ?></th>

        </tr>
    </thead>
    <tbody>
        <?php foreach ( $this->equipos as $equipo ): ?>

            <?php $id = $equipo->id; ?>
            <tr class="<?= $equipo->active
                            ? 'activo' : 'inactivo' ?>">

                <td>
                    <?= $this->escape( $equipo->equipo ) ?>
                </td>
                <td>
                    <?= $this->escape( $equipo->modelo ) ?>
                </td>
                <td>
                    <?= $this->escape( $equipo->categoria ) ?>
                </td>
                <td>
                    <?= $this->escape( $equipo->estadoequipo ) ?>
                </td>
                <td>
                    <?= $this->escape( $equipo->usuario ) ?>
                </td>
                <td>
                    <?= $this->escape( $equipo->fechafabricacion ) ?>
                </td>
                <td>
                    <?= $this->escape( $equipo->publishdate ) ?>
                </td>
                <td>
                    <?= $this->escape( $equipo->fabricante ) ?>
                </td>
                <td>
                    <?= $this->escape( $equipo->paises ) ?>
                </td>
                <td>


                    <? if ( !$equipo->topofers ): ?>

                        <?php
                        $link = $this->url(
                                array(
                                    'module' => 'admin' ,
                                    'controller' => 'equipo' ,
                                    'action' => 'addtopofers' ,
                                    'id' => $id ) )
                        ?>
                        <a href="<?= $link ?>">
                            <?= $this->translate( 'Add Ofers' ); ?> 
                        </a>
                    <? else: ?>
                        <?php
                        $link = $this->url(
                                array(
                                    'module' => 'admin' ,
                                    'controller' => 'equipo' ,
                                    'action' => 'quittopofers' ,
                                    'id' => $id ) )
                        ?>
                        <a href="<?= $link ?>">
                            <?= $this->translate( 'Quit Ofers' ); ?> 
                        </a>

                    <? endif; ?>

                    <?php
                    $link = $this->url(
                            array(
                                'module' => 'admin' ,
                                'controller' => 'equipo' ,
                                'action' => 'editar' ,
                                'id' => $id ) )
                    ?>
                    <a href="<?= $link ?>">
                        <?= $this->translate( 'Editar' ); ?> 
                    </a>

                    <?php
                    $link = $this->url(
                            array(
                                'module' => 'admin' ,
                                'controller' => 'equipo' ,
                                'action' => 'borrar' ,
                                'id' => $id )
                            )
                    ?>
                    <a href="<?= $link ?>" onclick="return confirm(
                       <?= $this->translate( '¿Estás seguro?' ); ?>
                           )">
                           <?= $this->translate( 'Borrar' ); ?>
                    </a>

                    <? if ( $equipo->active ): ?>
                        <?
                        $link = $this->url(
                                array(
                                    'module' => 'admin' ,
                                    'controller' => 'equipo' ,
                                    'action' => 'desactivar' ,
                                    'id' => $id ) )
                        ?>
                        <a href="<?= $link ?>">
                            <?= $this->translate( 'Desactivar' ); ?>
                        </a>
                    <? else: ?>
                        <?
                        $link = $this->url(
                                array( 'module' => 'admin' ,
                                    'controller' => 'equipo' ,
                                    'action' => 'activar' ,
                                    'id' => $id ) )
                        ?>
                        <a href="<?= $link ?>">
                            <?= $this->translate( 'Activar' ); ?>
                        </a>
                    <? endif; ?>

                </td>
            </tr>
        <?php endforeach; ?>
    </tbody>
</table>
<br />

<a href="<?=
        $this->url(
                array(
            'module' => 'admin' ,
            'controller' => 'equipo' ,
            'action' => 'nuevo' ) , null , true
        )
        ?>">Nuevo</a>

<?=
$this->paginationControl(
        $this->equipos , 'Sliding' , 'equipo/_pag.phtml'
);
?>
