<h2> <?= $this->translate( 'Equipment' ) ?>:</h2>

<table border="1" class="listado">
    <thead>
        <tr>
            <th><?= $this->translate( 'Name' ) ?></th>
            <th><?= $this->translate( 'Name' ) ?></th>
            <th><?= $this->translate( 'Name' ) ?></th>
            <th><?= $this->translate( 'Name' ) ?></th>
            <th><?= $this->translate( 'Name' ) ?></th>
            <th><?= $this->translate( 'Name' ) ?></th>
            <th><?= $this->translate( 'Name' ) ?></th>
            <th><?= $this->translate( 'Operations' ) ?></th>

        </tr>
    </thead>
    <tbody>
        <?php foreach ( $this->equipos as $equipos ): ?>
            <?php $id = $equipos->id; ?>
            <tr class="<?= $equipos->active
                            ? 'activo' : 'inactivo' ?>">

                <td><?= $this->escape( $equipos->nombre ) ?></td>
                <td>

                    <?php
                    $link = $this->url(
                            array(
                                'module' => 'admin' ,
                                'controller' => 'equipo' ,
                                'action' => 'editar' ,
                                'id' => $id ) )
                    ?>
                    <a href="<?= $link ?>">[Editar]</a>

                    <?php
                    $link = $this->url(
                            array(
                                'module' => 'admin' ,
                                'controller' => 'equipo' ,
                                'action' => 'borrar' ,
                                'id' => $id )
                            )
                    ?>
                    <a href="<?= $link ?>" onclick="return confirm('¿Estás seguro?')">[Borrar]</a>

                    <?php if ( $equipos->active ): ?>
                        <?php $link = $this->url( array( 'module' => 'admin' , 'controller' => 'equipo' , 'action' => 'desactivar' , 'id' => $id ) ) ?>
                        <a href="<?= $link ?>">[Desactivar]</a>
                    <?php else: ?>
                        <?php $link = $this->url( array( 'module' => 'admin' , 'controller' => 'equipo' , 'action' => 'activar' , 'id' => $id ) ) ?>
                        <a href="<?= $link ?>">[Activar]</a>
    <?php endif; ?>

                </td>
            </tr>
<?php endforeach; ?>
    </tbody>
</table>
<br />

<a href="<?=
$this->url(
        array(
    'module' => 'admin' ,
    'controller' => 'equipo' ,
    'action' => 'nuevo' ) , null , true
 )
?>">Nuevo</a>

