<h2>Reservas</h2>
<table border="1" class="listado">
    <thead>
        <tr>
            <th><?= $this->translate('id') ?></th>
            <th><?= $this->translate('nombre') ?></th>
            <th><?= $this->translate('usuario') ?></th>
            <th><?= $this->translate('precio') ?></th>
            <th><?= $this->translate('categoria') ?></th>
            <th><?= $this->translate('estado del equipo') ?></th>
            <th><?= $this->translate('fabricante') ?></th>
            <th><?= $this->translate('calidad') ?></th>
            <th><?= $this->translate('acciones') ?></th>
        </tr>
    </thead>
    <tbody>
        <?php foreach ($this->equipos as $equipo): ?>

            <tr class="<?= $equipo->active ? 'activo' : 'inactivo' ?>">
                <td>
                    <?= $this->escape($equipo->id) ?>
                </td>

                <td>
                    <?= $this->escape($equipo->equipo) ?>
                </td>
                <td>
                    <?php $usuario = $equipo->nombre . " " . $equipo->apellido; ?>
                    <?= $this->escape($usuario) ?>
                </td>
                <td>
                    <?= $this->escape($equipo->precio) ?>
                </td>
                <td>
                    <?= $this->escape($equipo->categoria) ?>
                </td>
                <td>
                    <?= $this->escape($equipo->estadoequipo) ?>
                </td>
                <td>
                    <?= $this->escape($equipo->fabricante) ?>
                </td>
                <td>
                    <?= $this->escape($equipo->calidad) ?>
                </td>
                <td>
                    <?php
                    $link =
                            $this->url(
                            array(
                        'slug' => $equipo->slug
                            ), 'slugEquipment', true)
                    ?>

                    <a href="<?= $link ?>" 
                       title="<?= $this->translate('ver equipo') ?>" >
                        <img class ="imagen-see">
                    </a>
                </td>

            </tr>
        <?php endforeach; ?>
    </tbody>
</table>