<div id="section-bottom-country-chile" class="bottom-country">
    <h4>Oficinas Chile:</h4>
    <p>MedTechTrade Chile</p>
    <p>Monte Carmelo 37</p>
    <p>Providencia</p>
    <p>Santiago, Chile</p>
    <p>Fono: +56-2 710 5560</p>
    <p>contact-chile@medtechtrade.com</p>
</div>
<div id="section-bottom-country-peru" class="bottom-country">
    <h4>Oficinas Per&uacute;:</h4>
    <p>MedTechTrade Per&uacute; S.A.C.</p>
    <p>Calle Juan Fanning 219</p>
    <p>Miraflores (Lima)</p>
    <p>Per&uacute;</p>
    <p>Tel: +51-1 446 6807</p>
    <p>contact-peru@medtechtrade.com</p>
</div>
<div id="section-bottom-country-switzerland" class="bottom-country">
    <h4>Office Schweiz:</h4>
    <p>MedTechTrade AG</p>
    <p>Bankstrasse 4</p>
    <p>CH-8610 Uster</p>
    <p>Switzerland</p>
    <p>Phone +41 43 399 01 11</p>
    <p>Fax: +41 44 905 19 29</p>
    <p>contact@medtechtrade.com</p>
</div>
<div id="section-bottom-country-poland" class="bottom-country">
    <h4>Nasz adres w Polsce:</h4>
    <p>MedTechTrade AG</p>
    <p>ul. Złota 61</p>
    <p>00-819 Warszawa</p>
    <p>contact-poland@medtechtrade.com</p>
</div>