<div id="logo-top">
    <a href ="
    <?=
    $this->url(
            array( 'module' => 'default' ,
        'controller' => 'index' ,
        'action' => 'index' ) , 'default' , true
    )
    ?>
       ">
        <img src="/theme/default/image/logo-top.png">
    </a>

</div>
<div id="dataUser">
    <div id="userData">
        <? if ( Zend_Auth::getInstance()->hasIdentity() ): ?>
            <?= $this->translate( 'Bienvenido' ) . ' ' . $this->authUser ?>
            <a href="<?=
        $this->url( array(
            'module' => 'default' ,
            'controller' => 'usuario' ,
            'action' => 'logout' ) , 'default' , true )
            ?>">
                <?= $this->translate( 'logout' ) ?>
            </a>
           <? endif; ?>
    </div>
    <div id="formIdioma">
        <? $form = new Mtt_Form_IdiomaPais(); ?>
        <div id="pais">
            <?= $form->pais; ?>
        </div>
        <div id="idioma">
            <?= $form->idioma; ?>
        </div>
        <div id="recordar">
            <?= $form->recordar; ?>
        </div>
        <div id="button">
            <?= $form->submit; ?>
        </div>
    </div>


</div>

