<ul>
    <?
    $objcategorias = new Mtt_Models_Bussines_Categoria();
    foreach ( $objcategorias->listar() as $categoria )
        {
        ?>
        <li>
            <a href="
            <?=
            $this->url(
                    array(
                'slug' => $categoria->slug
                    )
                    , 'slugCategory' , true
            )
            ?>">
                <span>
                    <?= $this->escape( $categoria->title ) ?>
                </span>

            </a>
        </li>
        <?
        }
    ?>
</ul>