<div id="sections-buttons-top">
    <ul>
        <li class="selected">
            <span>
                <a href="
                <?= $this->url( array( 'controller' => 'index' ,
                    'action' => 'index' ) , null , true ) ?>">

                    <?= $this->translate( 'Home' ); ?>
                </a>  
            </span>
        </li>
        <li>
            <span>

                <a href="
                <?= $this->url( array( 'controller' => 'equipo' ,
                    'action' => 'index' ) , null , true ) ?>">

                    <?= $this->translate( 'Buy equipment' ); ?>
                </a>  
            </span>

        </li>
        <li>
            <span>

                <a href="
                <?= $this->url( array( 'controller' => 'vender' ,
                    'action' => 'index' ) , null , true ) ?>">
                       <?= $this->translate( 'Sell/trade-in Equipment' ); ?>

                </a>  
            </span>

        </li>
        
        <li>
            <span>
                <a href="
                <?= $this->url( array( 'controller' => 'contactus' ,
                    'action' => 'index' ) , null , true ) ?>">
                       <?= $this->translate( 'Contact us' ); ?>

                </a>  
            </span>
        </li>
        <li>
            <span>
                <a href="
                <?= $this->url( array( 'controller' => 'usuario' ,
                    'action' => 'index' ) , null , true ) ?>">
                       <?= $this->translate( 'my account' ); ?>

                </a> 
            </span>
        </li>
    </ul> 

</div>