<!doctype html>
<html lang="en">

    <head>

        <meta charset="utf-8" />

        <?= $this->headTitle() ?> 
        <link href="/images/favicon.ico" rel="shortcut icon" type="image/x-icon" />
        <meta name="viewport" content="width=device-width, initial-scale=1.0" />
        <!-- 1140px Grid styles for IE -->
        <!--[if lte IE 9]>
        <link rel="stylesheet" href="/theme/admin/css/ie.css" type="text/css" media="screen" />
        <![endif]-->
        <?
        $this->headLink()->appendStylesheet( '/theme/admin/css/1140.css' )
                ->appendStylesheet( '/theme/admin/css/styles.css' );
        ?>
        <?= $this->headLink() ?>        
        <?= $this->jQuery() ?>  
        <?= $this->headScript()
                ->appendFile( '/theme/admin/js/css3-mediaqueries.js' ); ?> 


        <!--Delete embedded styles, just for example.-->
        <style type="text/css">

            body {
                font-family: "Helvetica Neue", Helvetica, Arial, sans-serif;
            }

            .container p {
                color: #fff;
                line-height: 100px;
                background: #000;
                text-align: center;
                margin: 20px 0 0 0;
            }

        </style>

    </head>


    <body>

        <div class="container header">
            <?= $this->render( '_header.phtml' ) ?>
        </div>

        <div class="container nav">
            <div class="row">
                <div id="dolphincontainer">
                    <div id="dolphinnav">
                        <?= $this->render( '_navegacion.phtml' ); ?>
                    </div>
                </div>
            </div>
        </div>

        <div class="container body">
            <div class="row">


                <div class="eightcol">
                    <?=
                    $this->render( '_messages.phtml' );
                    ?>

                    <?=
                    $this->layout()->content
                    ?>
                </div>


                <div class="fourcol last">
                    Funciones de Mas solicitados
                </div>

            </div>
        </div>

        <div class="container footer">
            <div class="row">
                <?= $this->render( '_footer.phtml' ); ?>
            </div>
        </div>

    </body>

</html>

