<span class="breadcrumb">
    <a href="#">Buy Equipment</a> >
    <a href="#">Microscopes</a> >
    <a href="#">Ultra-Low Temperaure Upright Freezers</a>
</span>
<h2>Manufacturer: Thermo Fisher Scientific</h2>
<div id="device-foto-galery">
    <!--Producto -->

    <img src="/media/catalog/product/device-03-00.png" alt="">
    <!--Producto-->
    <!--\media\catalog\product\thumb-->
    <img src="/media/catalog/product/thumb/device-03-01.png" alt="">
    <img src="/media/catalog/product/thumb/device-03-02.png" alt="">
    <img src="/media/catalog/product/thumb/device-03-03.png" alt="">
    <img src="/media/catalog/product/thumb/device-03-04.png" alt="">
    <!-- Fin de imagenes -->
    <a href="#"><img src="/images/arrow-left.png" alt=""></a>
    <a href="#"><img src="/images/arrow-right.png" alt=""></a>
</div>
<div id="device-description">
    <a href="#"><span class="advanced-search-tab">Advanced Search</span></a>
    <span class="device-description-field">Product name</span>
    <span>Ultra-Low Temperaure Upright Freezers</span>
    <span class="device-description-field">Model</span>
    <span>ULT2586-10-V</span>
    <span class="device-description-field">Origin</span>
    <span>Switzerland</span>
    <span class="device-description-field">Article ID</span>
    <span>236</span>
    <span class="device-description-field">Date/Year of manufacture</span>
    <span>2008-12-01</span>
    <span class="device-description-field">Estimated weight (KG)</span>
    <span>Not Available</span>
    <span class="device-description-field">Quality/Condition</span>
    <span>Excelent</span>
    <span class="device-description-field">Mode Amount of equipment</span>
    <span>1</span>
    <span class="device-description-field">Description</span>
    <span>
        Thermo Scientifig Revco. Ultima Plus<br/>
        Placing out of operation: March 2010
    </span>
    <span class="device-description-field">Specifications</span>
    <span>
        Temperature Range: from -50&deg; until 86&deg;<br/>
        Capacity Cu.: 691 (L)<br/>
        Electrical Amps/Breaker 230V/60 Hz 1&empty;<br/>
        Interior dimensions: HxWxD (mm) (1283 x  876 x 616)<br/>
        Exterior dimensions: HxWxD (mm) (1283 x  876 x 616)<br/>
        Shipping weight: 376 Kg.<br/>
        Power Tension 230v freq. 50 Phase: 1<br/>
        Amps: 12A
    </span>
</div>
<div id="device-actions">
    <a href="#"><span class="device-action-pdf">Download PDF</span></a>
    <a href="#"><span class="device-action-print">Print</span></a>
    <a href="#"><span class="device-action-question">Ask a Question</span></a>
    <a href="#"><span class="device-action-help">I Need Help</span></a>
    <a href="#"><span class="device-action-friend">Tell a Friend</span></a>
</div>