<span class="breadcrumb">
    <a href="
    <?=
    $this->url( array( 'module' => 'default' ,
        'controller' => 'producto' ,
        'action' => 'index' ) , null , true )

    ?>">
           <?= $this->translate( 'Buy Equipment' ) ?>
    </a>
    <a href="#">Microscopes</a> >
    <a href="#"><?= $this->producto->nombre ?></a>
</span>

<h2>Manufacturer: <?= $this->producto->fabricante ?></h2>
<div id="device-foto-galery">
    <!--Producto -->

    <img src="/media/catalog/product/device-03-00.png" alt="">
    <!--Producto-->
    <!--\media\catalog\product\thumb-->
    <img src="/media/catalog/product/thumb/device-03-01.png" alt="">
    <img src="/media/catalog/product/thumb/device-03-02.png" alt="">
    <img src="/media/catalog/product/thumb/device-03-03.png" alt="">
    <img src="/media/catalog/product/thumb/device-03-04.png" alt="">
    <!-- Fin de imagenes -->
    <a href="#"><img src="/images/arrow-left.png" alt=""></a>
    <a href="#"><img src="/images/arrow-right.png" alt=""></a>
</div>
<div id="device-description">
    <a href="#">
        <span class="advanced-search-tab">
            <?= $this->translate( 'Advanced Search' ) ?>
        </span>
    </a>
    <span class="device-description-field"><?= $this->translate( 'Product name' ) ?></span>
    <span>
        <?= $this->producto->nombre ?>
    </span>
    <span class="device-description-field"><?= $this->translate( 'Model' ) ?></span>
    <span>
        <?= $this->producto->modelo ?>
    </span>
    <span class="device-description-field"><?= $this->translate( 'Origin' ) ?></span>
    <span>
        <?= $this->producto->pais ?>
    </span>
    <span class="device-description-field"><?= $this->translate( 'Article ID' ) ?></span>
    <span>
        <?= $this->producto->id ?>
    </span>
    <span class="device-description-field"><?= $this->translate( 'Date/Year of manufacture' ) ?></span>
    <span>
        <?= $this->producto->fechafabricacion ?>
    </span>
    <span class="device-description-field"><?= $this->translate( 'Estimated weight (KG)' ) ?></span>
    <span>
        <?= $this->producto->pesoEstimado ?>
    </span>
    <span class="device-description-field"><?= $this->translate( 'Quality/Condition' ) ?></span>
    <span>
        <?= $this->producto->calidad ?>
    </span>
    <span class="device-description-field"><?= $this->translate( 'Mode Amount of equipment' ) ?></span>
    <span>
        <?= $this->producto->cantidad ?>
    </span>
    <span class="device-description-field"><?= $this->translate( 'Description' ) ?></span>
    <span>
        Thermo Scientifig Revco. Ultima Plus<br/>
        Placing out of operation: March 2010
    </span>
    <span class="device-description-field"><?= $this->translate( 'Specifications' ) ?></span>
    <span>
        <?= $this->translate( 'Temperature Range' ) ?>: from -50&deg; until 86&deg;<br/>
        <?= $this->translate( 'Capacity Cu.' ) ?>: 691 (L)<br/>
        Electrical Amps/Breaker 230V/60 Hz 1&empty;<br/>
        <?= $this->translate( 'Interior dimensions' ) ?>: HxWxD (mm) (1283 x  876 x 616)<br/>
        <?= $this->translate( 'Exterior dimensions' ) ?>: HxWxD (mm) (1283 x  876 x 616)<br/>
        <?= $this->translate( 'Shipping weight' ) ?>: 376 Kg.<br/>
        Power Tension 230v freq. 50 Phase: 1<br/>
        <?= $this->translate( 'Amps' ) ?>: 12A
    </span>
</div>
<div id="device-actions">
    <a href="#"><span class="device-action-pdf"><?= $this->translate( 'Download PDF' ) ?></span></a>
    <a href="#"><span class="device-action-print"><?= $this->translate( 'Print' ) ?></span></a>
    <a href="#"><span class="device-action-question"><?= $this->translate( 'Ask a Question' ) ?></span></a>
    <a href="#"><span class="device-action-help"><?= $this->translate( 'I Need Help' ) ?></span></a>
    <a href="#"><span class="device-action-friend"><?= $this->translate( 'Tell a Friend' ) ?></span></a>
</div>