
    <h3>Contacto</h3>
    <p class="Suiza">
        <strong>Office Schweiz:</strong>
        <br> 
        <strong>MedTechTrade</strong> 
        <strong>AG</strong>
        <br> 
        Bankstrasse 4
        <br> CH-8610 Uster<br> Switzerland<br> Phone +41 43 399 01 11<br> Fax: +41 44 905 19 29<br>
        <script type="text/javascript">// <![CDATA[
            var prefix = '&#109;a' + 'i&#108;' + '&#116;o';
            var path = 'hr' + 'ef' + '=';
            var addy91457 = 'contact' + '&#64;';
            addy91457 = addy91457 + 'm&#101;dt&#101;chtr&#97;d&#101;' + '&#46;' + 'c&#111;m';
            document.write( '<a ' + path + '\'' + prefix + ':' + addy91457 + '\'>' );
            document.write( addy91457 );
            document.write( '<\/a>' );
            // ]]></script><a href="mailto:contact@medtechtrade.com" title="[GMCP] Compose a new mail to contact@medtechtrade.com" onclick="window.open('https://mail.google.com/mail/?view=cm&amp;fs=1&amp;tf=1&amp;to=contact@medtechtrade.com','Compose new message','width=640,height=480');return false" rel="noreferrer">contact@medtechtrade.com</a>
    </p>
    
    <p class="Peru">
        <strong>Oficinas Perú:</strong><br> <strong>MedTechTrade Perú</strong><strong> S.A.C.</strong><br> Calle Juan Fanning 219<br> Miraflores (Lima)<br> Perú<br> Tel: +51-1 446 6807<br>
        <script type="text/javascript">// <![CDATA[
            var prefix = '&#109;a' + 'i&#108;' + '&#116;o';
            var path = 'hr' + 'ef' + '=';
            var addy91457 = 'contact-peru' + '&#64;';
            addy91457 = addy91457 + 'm&#101;dt&#101;chtr&#97;d&#101;' + '&#46;' + 'c&#111;m';
            document.write( '<a ' + path + '\'' + prefix + ':' + addy91457 + '\'>' );
            document.write( addy91457 );
            document.write( '<\/a>' );
            // ]]></script><a href="mailto:contact-peru@medtechtrade.com" title="[GMCP] Compose a new mail to contact-peru@medtechtrade.com" onclick="window.open('https://mail.google.com/mail/?view=cm&amp;fs=1&amp;tf=1&amp;to=contact-peru@medtechtrade.com','Compose new message','width=640,height=480');return false" rel="noreferrer">contact-peru@medtechtrade.com</a>
    </p>
    <p class="Chile"><strong>Oficinas Chile:</strong><br> <strong>MedTechTrade Chile</strong><br> Monte Carmelo 37<br> Providencia<br> Santiago, Chile<br> Fono: +56-2 710 5560<br>
        <script type="text/javascript">// <![CDATA[
            var prefix = '&#109;a' + 'i&#108;' + '&#116;o';
            var path = 'hr' + 'ef' + '=';
            var addy91457 = 'contact-chile' + '&#64;';
            addy91457 = addy91457 + 'm&#101;dt&#101;chtr&#97;d&#101;' + '&#46;' + 'c&#111;m';
            document.write( '<a ' + path + '\'' + prefix + ':' + addy91457 + '\'>' );
            document.write( addy91457 );
            document.write( '<\/a>' );
            // ]]></script><a href="mailto:contact-chile@medtechtrade.com" title="[GMCP] Compose a new mail to contact-chile@medtechtrade.com" onclick="window.open('https://mail.google.com/mail/?view=cm&amp;fs=1&amp;tf=1&amp;to=contact-chile@medtechtrade.com','Compose new message','width=640,height=480');return false" rel="noreferrer">contact-chile@medtechtrade.com</a>
    </p>		</div>