<div id="sections-buttons-top">
    <ul>
        <li class="selected">
            <span>
                <a href="
                <?= $this->url( array( 'controller' => 'index' ,
                    'action' => 'index' ) , null , true ) ?>">

                    Inicio
                </a>  
            </span>


        </li>
        <li>
             <span>

                <a href="
                <?= $this->url( array( 'controller' => 'producto' ,
                    'action' => 'index' ) , null , true ) ?>">

                    Comprar Equipos
                </a>  
            </span>
            
           
        </li>
        <li>
            <span>

                <a href="
                <?= $this->url( array( 'controller' => 'vender' ,
                    'action' => 'index' ) , null , true ) ?>">

                    Vender/Comerciar Equipos
                </a>  
            </span>

        </li>
        <li>
            <span>
                <a href="
                <?= $this->url( array( 'controller' => 'Servicios' ,
                    'action' => 'index' ) , null , true ) ?>">
                    Servicios
                </a>  
            </span>


        </li>
        <li>
            <span>
                <a href="
                <?= $this->url( array( 'controller' => 'contacto' ,
                    'action' => 'index' ) , null , true ) ?>">

                    Contactenos
                </a>  
            </span>
        </li>
        <li>
            <span>
                <a href="
                <?= $this->url( array( 'controller' => 'usuario' ,
                    'action' => 'index' ) , null , true ) ?>">

                    Mi Cuenta
                </a> 
            </span>
        </li>
    </ul> 
    
</div>