<?php 
    $r= $_REQUEST;
?>
<h1>Category [Add]</h1>
<br /><br /><br />
<?php if(isset($this->errors)):?>
    <?php $e = $this->errors;?>
<div id="errors">
    Please correct the errors. 
</div>
<?php endif;?>
<form method="post" action="admin/blog/add-category">
    <div class="field">
    	<label>Label</label>
    	<input type="text" name="name" value="<?php echo (isset($r['name']))? $r['name'] : ""?>" />
    	<span class="explanation"></span>
    </div>
    <div class="field">
    	<label>Description</label>
    	<input type="text" name="description" value="<?php echo (isset($r['description']))? $r['description'] : ""?>" />
    	<span class="explanation"></span>
    </div>
    <input type="submit" name="save" value="Save" />
</form>
