<?php
    $arrow_up = '<img class="arrow" src="images/arrow_up.png" alt="ASC" title="ASC"/>';
    $arrow_down = '<img class="arrow" src="images/arrow_down.png" alt="DESC" title="DESC"/>';
?>
<h1>Categories for Blog Articles</h1>
<a href="admin/blog/add-category" class="button">Add New</a>
<br /><br /><br />
<div class="clear"></div>
<form>
<?php 
if(!empty($this->categories)) : 
$count = count($this->categories);
$page= @$_REQUEST['p'];
$size=8;
$pages = $count/$size + ($count%$size>0?1:0);
if (!$page || $page>$pages) $page=1;
$aux = array_chunk($this->categories,$size);
$this->categories = $aux[$page-1];
?>
<br />
<a href="admin/blog/categories/?p=all">Reset Filters</a>&nbsp;
<?php for($i=1;$i<=$pages;$i++): if ($i!=$page):?>
<a href="admin/blog/categories/?p=<?php echo $i?>&amp;f=<?php echo isset($_REQUEST['f'])?$_REQUEST['f']:"creation_date";?>&amp;o=<?php echo isset($_REQUEST['o'])?$_REQUEST['o']:"ASC";?>"><?php echo $i?></a> &nbsp;
<?php else:?>
<b><?php echo $i?></b> &nbsp;
<?php endif;endfor;?>
<br /><br />
<?php endif;?>
<table>
    <tr class="gray">
        <td>
            Label
            <span class="links">
            <a href="admin/blog/categories/?p=1&f=name&o=asc"><?php echo $arrow_up;?></a>
            <a href="admin/blog/categories/?p=1&f=name&o=desc"><?php echo $arrow_down;?></a>
            </span>
        </td>
        <td>
            Description
            <span class="links">
            <a href="admin/blog/categories/?p=1&f=description&o=asc"><?php echo $arrow_up;?></a>
            <a href="admin/blog/categories/?p=1&f=description&o=desc"><?php echo $arrow_down;?></a>
            </span>
        </td>
        <td>
            Added on
            <span class="links">
            <a href="admin/blog/categories/?p=1&f=creation_date&o=asc"><?php echo $arrow_up;?></a>
            <a href="admin/blog/categories/?p=1&f=creation_date&o=desc"><?php echo $arrow_down;?></a>
            </span>
        </td>
        <td></td>
    </tr>
    <?php foreach ($this->categories as $category):?>
    <tr>
        <td><?php echo $category['name'];?></td>
        <td><?php echo $category['description'];?></td>
        <td><?php echo $category['creation_date'];?></td>
        <td><a href="admin/blog/edit-category/?id=<?php echo $category['id'];?>">Edit</a></td>
    </tr>
    <?php endforeach;?>
    <tr class="gray">
        <td>Label</td>
        <td>Description</td>
        <td>Added on</td>
        <td></td>
    </tr>
</table>
</form>
