<?php 
    $r=isset($_REQUEST['save']) ? $_REQUEST : $this->article;
?>
<h1>Blog Article [Edit]</h1>
<br /><br /><br />
<?php if(isset($this->errors)):?>
    <?php $e = $this->errors;?>
<div id="errors">
    Please correct the errors. 
</div>
<?php endif;?>
<form method="post" action="admin/blog/edit-article">
    <input type="hidden" name="id" value="<?php echo $r['id'];?>" />
    <div class="field">
    	<label>Title</label>
    	<input type="text" name="title" value="<?php echo (isset($r['title']))? $r['title'] : ""?>" />
    	<span class="explanation"></span>
    </div>
    <div class="field">
    	<label>Author</label>
    	<select name="author_id">
            <option value="0">Select One...</option>
            <?php foreach ($this->authors as $key=>$author):?>
            <option value="<?php echo $key;?>" <?php if(isset($r['account_id']) && $key==$r['account_id']) echo 'selected="selected"';?>><?php echo $author;?></option>
            <?php endforeach;?>
        </select>
    	<span class="explanation"></span>
    </div>
    <div class="field">
    	<label>Category</label>
    	<select name="category_id">
            <option value="0">Select One...</option>
            <?php foreach ($this->categories as $key=>$category):?>
            <option value="<?php echo $key;?>" <?php if(isset($r['category_id']) && $key==$r['category_id']) echo 'selected="selected"';?>><?php echo $category;?></option>
            <?php endforeach;?>
        </select>
    	<span class="explanation"></span>
    </div>
    <div class="field">
    	<label>Creation Date</label>
    	<input type="text" name="creation_date" value="<?php echo $r['creation_date']?>" readonly="readonly"/>
    	<span class="explanation"></span>
    </div>
    
    	<label>Summary</label>
    	<textarea name="summary" rows="5" cols="40"><?php echo $r['summary']?></textarea>
    	<span class="explanation"></span>
    
    	<label>Content</label>
    	<textarea name="content" rows="5" cols="40"><?php echo $r['content']?></textarea>
    	<span class="explanation"></span>
    
    <input type="submit" name="save" value="Save" />
</form>
<script type="text/javascript">
		CKEDITOR.replace('summary');
        CKEDITOR.replace('content');
</script>