<?php 
    $r=isset($_REQUEST['save']) ? $_REQUEST : $this->category;
?>
<h1>Category [Edit]</h1>
<br /><br /><br />
<?php if(isset($this->errors)):?>
    <?php $e = $this->errors;?>
<div id="errors">
    Please correct the errors. 
</div>
<?php endif;?>
<form method="post" action="admin/blog/edit-category">
    <input type="hidden" name="id" value="<?php echo $r['id'];?>" />
    <div class="field">
    	<label>Label</label>
    	<input type="text" name="name" value="<?php echo (isset($r['name']))? $r['name'] : ""?>" />
    	<span class="explanation"></span>
    </div>
    <div class="field">
    	<label>Description</label>
    	<input type="text" name="description" value="<?php echo (isset($r['description']))? $r['description'] : ""?>" />
    	<span class="explanation"></span>
    </div>
    <div class="field">
    	<label>Creation Date</label>
    	<input type="text" name="creation_date" value="<?php echo $r['creation_date']?>" readonly="readonly"/>
    	<span class="explanation"></span>
    </div>
    <input type="submit" name="save" value="Save" />
</form>
