<?php 
    if(isset($_REQUEST['search'])) $s = $_REQUEST;
    else if (isset($this->session->search_comment)) {$s=$this->session->search_comment;}
    $arrow_up = '<img class="arrow" src="images/arrow_up.png" alt="ASC" title="ASC"/>';
    $arrow_down = '<img class="arrow" src="images/arrow_down.png" alt="DESC" title="DESC"/>';
?>
<h1>Comments Manager</h1>
<br /><br /><br />
<form method="post" action="admin/blog/manage-comments">
    <input type="hidden" name="id" value="<?php echo $this->id;?>" />
    <div class="field">
    	<label>Search Term</label>
    	<input type="text" name="search_term" value="<?php echo (isset($s['search_term']))? $s['search_term'] : ""?>" />
    	<span class="explanation"></span>
    </div>
    <div class="field">
    	<label>Author</label>
    	<select name="author_id">
            <option value="0">Select One...</option>
            <?php foreach ($this->authors as $key=>$author):?>
            <option value="<?php echo $key;?>" <?php if(isset($s['author_id']) && $key==$s['author_id']) echo 'selected="selected"';?>><?php echo $author;?></option>
            <?php endforeach;?>
        </select>
    	<span class="explanation"></span>
    </div>
    <div class="field">
    	<label>Visibility</label>
    	<select name="hidden">
            <option value="0" <?php if(isset($s['hidden']) && $s['hidden']==0) echo 'selected="selected"';?>>Published</option>
            <option value="1" <?php if(isset($s['hidden']) && $s['hidden']==1) echo 'selected="selected"';?>>Hidden</option>
        </select>
    	<span class="explanation"></span>
    </div>
    <div class="field">
    	<label>Deletion Status</label>
    	<select name="deleted">
            <option value="0" <?php if(isset($s['deleted']) && $s['deleted']==0) echo 'selected="selected"';?>>Not deleted</option>
            <option value="1" <?php if(isset($s['deleted']) && $s['deleted']==1) echo 'selected="selected"';?>>Deleted</option>
        </select>
        <span class="explanation"></span>
    </div>
    <div class="field">
    	<label>Start Date</label>
    	<input type="text" class="date-picker" name="date_from" value="<?php echo (isset($s['date_from']))? $s['date_from'] : ""?>" />
    	<span class="explanation"></span>
    </div>
    <div class="clear"></div>
    <div class="field">
    	<label>End Date</label>
    	<input type="text" class="date-picker" name="date_to" value="<?php echo (isset($s['date_to']))? $s['date_to'] : ""?>" />
    	<span class="explanation"></span>
    </div>
    <div class="clear"></div>
    <input type="submit" name="search" value="Search"/>
</form>
<?php if (isset($this->errors)):?>
    <div id="errors">
        <ul>
        <?php foreach ($this->errors as $error):?>
            <li><?php echo $error;?></li>
        <?php endforeach?>
        </ul>
    </div>
<?php endif;?>

<form method="post" action="admin/blog/manage-comments">
<input type="hidden" name="id" value="<?php echo $this->id;?>" />
<select name="hidden">
    <option value="0">Show</option>
    <option value="1">Hide</option>
</select>
<select name="deleted">
    <option value="0">Undelete</option>
    <option value="1">Delete</option>
</select>
<input type="submit" name="apply" value="Apply" class="small_button"/>
<?php 
if(!empty($this->comments)) : 
$count = count($this->comments);
$page= @$_REQUEST['p'];
$size=8;
$pages = $count/$size + ($count%$size>0?1:0);
if (!$page || $page>$pages) $page=1;
$aux = array_chunk($this->comments,$size);
$this->comments = $aux[$page-1];
?>
<br />
<a href="admin/blog/manage-comments/?id=<?php echo $this->id;?>&amp;p=all">Reset Filters</a>&nbsp;
<?php for($i=1;$i<=$pages;$i++): if ($i!=$page):?>
<a href="admin/blog/manage-comments/?id=<?php echo $this->id;?>&amp;p=<?php echo $i?>&amp;f=<?php echo isset($_REQUEST['f'])?$_REQUEST['f']:"creation_date";?>&amp;o=<?php echo isset($_REQUEST['o'])?$_REQUEST['o']:"ASC";?>"><?php echo $i?></a> &nbsp;
<?php else:?>
<b><?php echo $i?></b> &nbsp;
<?php endif;endfor;?>
<br /><br />
<?php endif;?>
<table>
    <thead>
    <tr class="gray">
        <td class="check"><input type="checkbox" id="all" /></td>
        <td>
            Author
            <span class="links">
            <a href="admin/blog/manage-comments/?id=<?php echo $this->id;?>&amp;p=1&f=author&o=asc"><?php echo $arrow_up;?></a>
            <a href="admin/blog/manage-comments/?id=<?php echo $this->id;?>&amp;p=1&f=author&o=desc"><?php echo $arrow_down;?></a>
            </span>
        </td>
        <td>
            Creation Date
            <span class="links">
            <a href="admin/blog/manage-comments/?id=<?php echo $this->id;?>&amp;p=1&f=creation_date&o=asc"><?php echo $arrow_up;?></a>
            <a href="admin/blog/manage-comments/?id=<?php echo $this->id;?>&amp;p=1&f=creation_date&o=desc"><?php echo $arrow_down;?></a>
            </span>
        </td>
        <td>
            Content
        </td>
        <td>Status</td>
        <td>Operations</td>
    </tr>
    </thead>
    <tbody>
    <?php foreach($this->comments as $a):?>
    <tr>
        <td class="check"><input type="checkbox" name="comments[]" value="<?php echo $a['id'];?>" /></td>
        <td><?php echo $a['author'];?></td>
        <td><?php echo $a['creation_date'];?></td>
        <td><?php echo $a['text']?></td>
        <td>
            <?php
                if($a['deleted'] && $a['hidden']) $status = "Pending"; 
                else if($a['deleted']) $status = "Deleted";
                else if($a['hidden']) $status = "Hidden";
                else $status = "Published";
                echo $status;
            ;?>
        </td>
        <td>
            <a href="admin/blog/switch-comment/?id=<?php echo $a['id'];?>"><?php echo ($a['deleted'])?"Undelete":"Delete";?></a><br />
            <a href="admin/blog/switch-comment-public-status/?id=<?php echo $a['id'];?>"><?php echo ($a['hidden'])?"Publish":"Hide";?></a><br />
        </td>
    </tr>
    <?php endforeach;?>
    </tbody>
    <tr class="gray">
        <td class="check"><input type="checkbox" id="all_bottom" /></td>
        <td>Author</td>
        <td>Creation date</td>
        <td>Text</td>
        <td>Status</td>
        <td>Operations</td>
    </tr>
</table>
<br />
<?php if(!empty($this->comments)):?>
<a href="admin/blog/manage-comments/?id=<?php echo $this->id;?>&amp;p=all">Reset Filters</a>&nbsp;
<?php for($i=1;$i<=$pages;$i++): if ($i!=$page):?>
<a href="admin/blog/manage-comments/?id=<?php echo $this->id;?>&amp;p=<?php echo $i?>&amp;f=<?php echo isset($_REQUEST['f'])?$_REQUEST['f']:"creation_date";?>&amp;o=<?php echo isset($_REQUEST['o'])?$_REQUEST['o']:"ASC";?>"><?php echo $i?></a> &nbsp;
<?php else:?>
<b><?php echo $i?></b> &nbsp;
<?php endif;endfor;?>
<br /><br />
<?php endif;?>
</form>
