<h1>FAQ Patient</h1>

<form method="post" id="first">
	<div class="field">
 	<label>Title</label>
 	<input type="text" name="en_title" value="<?php echo (isset($_REQUEST['en_title']))?$_REQUEST['en_title']:$this->en_title;?>" />
 	<span class="explanation"></span>
 </div>	
	<label>Content</label>		
    <textarea name="en_content"><?php echo (isset($_REQUEST['en_content']))?$_REQUEST['en_content']:$this->en_content;?></textarea>
    <script type="text/javascript">
		CKEDITOR.replace( 'en_content' );
	</script>
	<input type="submit" name="save" value="Save Changes"/>
</form>