<h2><?= $this->translate('resultados de la busqueda') ?></h2>
<?php foreach ($this->resultados as $result): ?>

    <div>
        <?php
        $url = (is_null($result->image)) ?
                '/theme/default/image/no_images.png' :
                '/media/catalog/product/' . $result->image
        ?>
        <img src="<?= $url ?>" 
             alt="<?= $result->equipo ?>"
             width="24px" height="24px">
    </div>
    <div>
        <table border="1">
            <tbody>
                <tr>
                    <td>
                        <?= $this->escape($result->equipo) ?>
                    </td>
                </tr>
                <tr>
                    <td>
                        <?= $this->escape($result->fabricante) ?>
                    </td>
                </tr>
                <tr>
                    <td>
                        <?= $this->escape($result->categoria) ?>
                    </td>
                </tr>
                <tr>
                    <td>
                        <?= $this->escape($result->equipo) ?>
                    </td>
                </tr>
                <tr>
                    <td>
                        <?= $this->escape($result->modelo) ?>
                    </td>
                </tr>
                <tr>
                    <td>
                        <?= $this->escape($result->fechafabricacion) ?>
                    </td>
                </tr>
                <tr>
                    <td>
                        <?php
                        $link =
                                $this->url(
                                array(
                            'slug' => $result->slug
                                ), 'slugEquipment', true)
                        ?>

                        <a href="<?= $link ?>">
                            <?= $this->translate('ver detalles') ?>
                        </a>
                    </td>

                </tr>
            </tbody>
        </table>
    </div>
<?php endforeach; ?>

<?=
$this->paginationControl(
        $this->resultados, 'Sliding', 'busqueda/_pag.phtml'
);
?>
