<header>
    <h2>
        <?= $this->translate( 'Welcome' ) ?>
    </h2>

<?=$this->formOrder ?>

    <br/>

    <h3>
        <?= $this->categoria->title ?>
    </h3>
</header>

<span class="see-more">
    <a href="#">
        <?=
        $this->translate( 'Click to see all' )
        ?>
    </a>
</span>
<div class="device-horizontal-list">
    <?php foreach ( $this->productos as $producto ): ?>

        <div>
            <img src="/media/catalog/product/device-00.png" 
                 alt="<?= $producto->nombre ?>">

            <span class="manufacturer">
                <?= $this->translate( 'Manufacturer' ) ?> : 
                <?= $producto->fabricante ?>
            </span>
            <span class="name">
                <?= $this->translate( 'Product name' ) ?>: 
                <?= $producto->nombre ?>
            </span>

            <a href="
            <?=
            $this->url( array( 'module' => 'default' ,
                'controller' => 'equipo' ,
                'action' => 'ver' ,
                'id' => $producto->id ) , null , true )
            ?>
               ">
                <span>
                    <?= $this->translate( 'View details' ) ?>
                </span>
            </a>
        </div>

    <?php endforeach; ?>
</div>
<br/>

<br/>
<h3>
    <?= $this->translate( 'Top Seller in' ) ?> 
    <?= $this->categoria->title ?>
</h3>
<span class="see-more">
    <a href="#">
        <?=
        $this->translate( 'Click to see all' )
        ?></a>
</span>

<div class="device-horizontal-list">
    <div>
        <img src="/media/catalog/product/device-00.png" alt="Device 00">
        <span class="manufacturer">Manufacturer: Zeiss</span>
        <span class="name">Product name: Microscop</span>
        <a href="#"><span>View details</span></a>
    </div>
    <div>
        <img src="/media/catalog/product/device-01.png" alt="Device 01">
        <span class="manufacturer">Manufacturer: Zeiss</span>
        <span class="name">Product name: Microscop</span>
        <a href="#"><span>View details</span></a>
    </div>
    <div>
        <img src="/media/catalog/product/device-00.png" alt="Device 00">
        <span class="manufacturer">Manufacturer: Zeiss</span>
        <span class="name">Product name: Microscop</span>
        <a href="#"><span>View details</span></a>
    </div>
    <div>
        <img src="/media/catalog/product/device-01.png" alt="Device 01">
        <span class="manufacturer">Manufacturer: Zeiss</span>
        <span class="name">Product name: Microscop</span>
        <a href="#"><span>View details</span></a>
    </div>


</div>