<header>
    <h2>
        <?= $this->translate( 'Welcome' ) ?>
    </h2>

    <?= $this->formOrder ?>

    <br/>

    <h3>
        <?= $this->categoria->title ?>
    </h3>
</header>

<span class="see-more">
    <a href="<?=
        $this->url(
                array(
            'module' => 'default' ,
            'controller' => 'equipo' ,
            'action' => 'index' )
                , 'default' , true
        )
        ?>">
           <?=
           $this->translate( 'Click to see all' )
           ?>
    </a>
</span>
<div class="device-horizontal-list">
    <?php foreach ( $this->productos as $producto ): ?>

        <div>

            <a href="
            <?=
            $this->url( array(
                'slug' => $producto->slug ) , 'slugEquipment' , true )
            ?>
               ">

                <img src="/media/catalog/product/device-00.png" 


                     alt="<?= $producto->nombre ?>">
            </a>

            <span class="manufacturer">
                <?= $this->translate( 'Manufacturer' ) ?> : 
                <?= $producto->fabricante ?>
            </span>
            <span class="name">
                <?= $this->translate( 'Product name' ) ?>: 
                <?= $producto->nombre ?>
            </span>

            <a href="
            <?=
            $this->url( array(
                'slug' => $producto->slug ) , 'slugEquipment' , true )
            ?>
               ">
                <span>
                    <?= $this->translate( 'View details' ) ?>
                </span>
            </a>
        </div>

    <?php endforeach; ?>
</div>
<br/>

<br/>
<h3>
    <?= $this->translate( 'Top Seller in' ) ?> 
    <?= $this->categoria->title ?>
</h3>
<span class="see-more">
    <a href="#">
        <?=
        $this->translate( 'Click to see all' )
        ?></a>
</span>

<div class="device-horizontal-list">

    <?php foreach ( $this->equipoOfert as $producto ): ?>
        <div>

            <a href="
            <?=
            $this->url( array(
                'slug' => $producto->slug ) , 'slugEquipment' , true )
            ?>
               ">
                <img src="/media/catalog/product/device-00.png" 
                     alt="<?= $producto->nombre ?>">
            </a>

            <span class="manufacturer">
                <?= $this->translate( 'Manufacturer' ) ?>
                : <?= $producto->fabricante ?>
            </span>
            <span class="name">
                <?= $this->translate( 'Product name' ) ?>
                : 
                <?= $producto->nombre ?>
            </span>
            <a href="
            <?=
            $this->url( array(
                'slug' => $producto->slug ) , 'slugEquipment' , true )
            ?>
               ">
                <span>
                    <?= $this->translate( 'View details' ) ?>
                </span>
            </a>
        </div>
    <?php endforeach; ?>


</div>