<header>
    <h2>
        <?= $this->categoria->title ?>
    </h2>

    <?= $this->formOrder ?>

    <br/>

    <h3>
        <?= $this->translate('equipos nuevos') ?>
    </h3>
</header>

<span class="see-more">
      <a href="
            <?=
            $this->url( array(
                'slug' =>$this->categoria->slug ) , 'slugCategoryAllEquip' , true )
            ?>">
           <?=
           $this->translate( 'click para ver todos' )
           ?>
    </a>
</span>
<div class="device-horizontal-list">
    <?php foreach ( $this->productos as $producto ): ?>

        <div>

            <a href="
            <?=
            $this->url( array(
                'slug' => $producto->slug ) , 'slugEquipment' , true )
            ?>
               ">

                <img src="/media/catalog/product/device-00.png" 


                     alt="<?= $producto->nombre ?>">
            </a>

            <span class="manufacturer">
                <?= $this->translate( 'Manufacturer' ) ?> : 
                <?= $producto->fabricante ?>
            </span>
            <?php $nombre = (strlen($producto->nombre)>13)? 
                    substr($producto->nombre,0,11). '..': $producto->nombre ?>
            <span class="name" title="<?= $producto->nombre ?>">
                <?= $this->translate( 'Product name' ) ?>: 
                <?= $nombre ?>
            </span>

            <a href="
            <?=
            $this->url( array(
                'slug' => $producto->slug ) , 'slugEquipment' , true )
            ?>
               ">
                <span>
                    <?= $this->translate( 'View details' ) ?>
                </span>
            </a>
        </div>

    <?php endforeach; ?>
</div>
<br/>

<br/>
<h3>
    <?= $this->translate( 'equipos mas solicitados' ) ?> 
</h3>
<span class="see-more">
    <a href="#">
        <?=
        $this->translate( 'Click to see all' )
        ?></a>
</span>

<div class="device-horizontal-list">

    <?php foreach ( $this->equipoOfert as $producto ): ?>
        <div>

            <a href="
            <?=
            $this->url( array(
                'slug' => $producto->slug ) , 'slugEquipment' , true )
            ?>
               ">
                <img src="/media/catalog/product/device-00.png" 
                     alt="<?= $producto->nombre ?>">
            </a>

            <span class="manufacturer">
                <?= $this->translate( 'Manufacturer' ) ?>
                : <?= $producto->fabricante ?>
            </span>
            <span class="name">
                <?= $this->translate( 'Product name' ) ?>
                : 
                <?= $producto->nombre ?>
            </span>
            <a href="
            <?=
            $this->url( array(
                'slug' => $producto->slug ) , 'slugEquipment' , true )
            ?>
               ">
                <span>
                    <?= $this->translate( 'View details' ) ?>
                </span>
            </a>
        </div>
    <?php endforeach; ?>


</div>
