<?php 
    $arrow_up = '<img class="arrow" src="images/arrow_up.png" alt="ASC" title="ASC"/>';
    $arrow_down = '<img class="arrow" src="images/arrow_down.png" alt="DESC" title="DESC"/>';
?>
<h1>Administrators</h1>
<a href="admin/users/add-administrator" class="button">Add New</a>
<br /><br /><br />
<?php if (isset($this->errors)):?>
    <div id="errors">
        <ul>
        <?php foreach ($this->errors as $error):?>
            <li><?php echo $error;?></li>
        <?php endforeach?>
        </ul>
    </div>
<?php endif;?>
<form method="post" id="search" action="admin/users/administrators">
    <div class="field">
    	<label></label>
    	<input type="text" name="text" value="<?php if (isset($this->session->search_admin)) echo $this->session->search_admin;?>" />
    	<span class="explanation"></span>
    </div>
    <input type="submit" name="search" value="Search Administrators" />
</form>

<form method="post" action="admin/users/administrators">
<select name="status">
    <option value="0">Activate</option>
    <option value="1">Inactivate</option>
</select>
<input type="submit" name="apply" value="Apply" class="small_button"/>
<?php 
if(!empty($this->administrators)) : 
$count = count($this->administrators);
$page= @$_REQUEST['p'];
$size=8;
$pages = $count/$size + ($count%$size>0?1:0);
if (!$page || $page>$pages) $page=1;
$aux = array_chunk($this->administrators,$size);
$this->administrators = $aux[$page-1];
?>
<br />
<a href="admin/users/administrators/?p=all">Reset Filters</a>&nbsp;
<?php for($i=1;$i<=$pages;$i++): if ($i!=$page):?>
<a href="admin/users/administrators/?p=<?php echo $i?>&amp;f=<?php echo isset($_REQUEST['f'])?$_REQUEST['f']:"creation_date";?>&amp;o=<?php echo isset($_REQUEST['o'])?$_REQUEST['o']:"ASC";?>"><?php echo $i?></a> &nbsp;
<?php else:?>
<b><?php echo $i?></b> &nbsp;
<?php endif;endfor;?>
<br /><br />
<?php endif;?>
<table>
    <thead>
    <tr class="gray">
        <td class="check"><input type="checkbox" id="all" /></td>
        <td>
            Username
            <span class="links">
            <a href="admin/users/administrators/?p=1&f=username&o=asc"><?php echo $arrow_up;?></a>
            <a href="admin/users/administrators/?p=1&f=username&o=desc"><?php echo $arrow_down;?></a>
            </span>
        </td>
        <td>
            First Name
            <span class="links">
            <a href="admin/users/administrators/?p=1&f=first_name&o=asc"><?php echo $arrow_up;?></a>
            <a href="admin/users/administrators/?p=1&f=first_name&o=desc"><?php echo $arrow_down;?></a>
            </span>
        </td>
        <td>
            Last Name
            <span class="links">
            <a href="admin/users/administrators/?p=1&f=last_name&o=asc"><?php echo $arrow_up;?></a>
            <a href="admin/users/administrators/?p=1&f=last_name&o=desc"><?php echo $arrow_down;?></a>
            </span>
        </td>
        <td>
            Email Address
            <span class="links">
            <a href="admin/users/administrators/?p=1&f=email&o=asc"><?php echo $arrow_up;?></a>
            <a href="admin/users/administrators/?p=1&f=email&o=desc"><?php echo $arrow_down;?></a>
            </span>
        </td>
        <td>Status</td>
    </tr>
    </thead>
    <tbody>
    <?php foreach($this->administrators as $a):?>
    <tr>
        <td class="check">
            <?php if (!$a['superadmin']):?>
            <input type="checkbox" name="admins[]" value="<?php echo $a['id'];?>" />
            <?php endif;?>
        </td>
        <td>
            <img src="images/avatar.jpg" alt=""/><?php echo $a['username']?><br />
            <a href="admin/users/edit-administrator?id=<?php echo $a['id'];?>">Edit</a>|<a href="admin/users/switch-admin?id=<?php echo $a['id'];?>"><?php echo ($a['hidden'])?"Activate":"Inactivate";?></a>
        </td>
        <td><?php echo $a['first_name']?></td>
        <td><?php echo $a['last_name']?></td>
        <td><?php echo $a['email']?></td>
        <td><?php echo ($a['hidden']) ? "Inactive" : "Active";?></td>
    </tr>
    <?php endforeach;?>
    </tbody>
    <tr class="gray">
        <td class="check"><input type="checkbox" id="all_bottom" /></td>
        <td>Username</td>
        <td>First Name</td>
        <td>Last Name</td>
        <td>Email Address</td>
        <td>Status</td>
    </tr>
</table>
<br />
<?php if (!empty($this->administrators)):?>
<a href="admin/users/administrators/?p=all">Reset Filters</a>&nbsp;
<?php for($i=1;$i<=$pages;$i++): if ($i!=$page):?>
<a href="admin/users/administrators/?p=<?php echo $i?>&amp;f=<?php echo isset($_REQUEST['f'])?$_REQUEST['f']:"creation_date";?>&amp;o=<?php echo isset($_REQUEST['o'])?$_REQUEST['o']:"ASC";?>"><?php echo $i?></a> &nbsp;
<?php else:?>
<b><?php echo $i?></b> &nbsp;
<?php endif;endfor;?>
<?php endif;?>
</form>