<?php 
    $arrow_up = '<img class="arrow" src="images/arrow_up.png" alt="ASC" title="ASC"/>';
    $arrow_down = '<img class="arrow" src="images/arrow_down.png" alt="DESC" title="DESC"/>';
?>
<h1>Dentists</h1>
<a href="admin/users/add-dentist" class="button">Add New</a>
<br /><br /><br />
<?php if (isset($this->errors)):?>
    <div id="errors">
        <ul>
        <?php foreach ($this->errors as $error):?>
            <li><?php echo $error;?></li>
        <?php endforeach?>
        </ul>
    </div>
<?php endif;?>
<form method="post" id="search" action="admin/users/dentists">
    <div class="field">
    	<label></label>
    	<input type="text" name="text" value="<?php if (isset($this->session->search_dentist)) echo $this->session->search_dentist;?>" />
    	<span class="explanation"></span>
    </div>
    <input type="submit" name="search" value="Search Dentists" />
</form>

<form method="post" action="admin/users/dentists">
<select name="status">
    <option value="0">Activate</option>
    <option value="1">Inactivate</option>
</select>
<input type="submit" name="apply" value="Apply" class="small_button"/>

<a href="admin/users/dentists/?view=all">View All</a> | <a href="admin/users/dentists/?view=pending">View Pending</a>
<?php 
if(!empty($this->dentists)) : 
$count = count($this->dentists);
$page= @$_REQUEST['p'];
$size=8;
$pages = $count/$size + ($count%$size>0?1:0);
if (!$page || $page>$pages) $page=1;
$aux = array_chunk($this->dentists,$size);
$this->dentists = $aux[$page-1];
?>
<br />
<a href="admin/users/dentists/?p=all">Reset Filters</a>&nbsp;
<?php for($i=1;$i<=$pages;$i++): if ($i!=$page):?>
<a href="admin/users/dentists/?p=<?php echo $i?>&amp;f=<?php echo isset($_REQUEST['f'])?$_REQUEST['f']:"creation_date";?>&amp;o=<?php echo isset($_REQUEST['o'])?$_REQUEST['o']:"ASC";?>"><?php echo $i?></a> &nbsp;
<?php else:?>
<b><?php echo $i?></b> &nbsp;
<?php endif;endfor;?>
<br /><br />
<?php endif;?>
<table>
    <tr class="gray">
        <td class="check"><input type="checkbox" id="all" /></td>
        <td>
            Username
            <span class="links">
            <a href="admin/users/dentists/?p=1&f=username&o=asc"><?php echo $arrow_up;?></a>
            <a href="admin/users/dentists/?p=1&f=username&o=desc"><?php echo $arrow_down;?></a>
            </span>
        </td>
        <td>
            First Name
            <span class="links">
            <a href="admin/users/dentists/?p=1&f=first_name&o=asc"><?php echo $arrow_up;?></a>
            <a href="admin/users/dentists/?p=1&f=first_name&o=desc"><?php echo $arrow_down;?></a>
            </span>
        </td>
        <td>
            Last Name
            <span class="links">
            <a href="admin/users/dentists/?p=1&f=last_name&o=asc"><?php echo $arrow_up;?></a>
            <a href="admin/users/dentists/?p=1&f=last_name&o=desc"><?php echo $arrow_down;?></a>
            </span>
        </td>
        <td>
            Membership plan
            <span class="links">
            <a href="admin/users/dentists/?p=1&f=membership_plan&o=asc"><?php echo $arrow_up;?></a>
            <a href="admin/users/dentists/?p=1&f=membership_plan&o=desc"><?php echo $arrow_down;?></a>
            </span>
        </td>
        <td>
            Email Address
            <span class="links">
            <a href="admin/users/dentists/?p=1&f=email&o=asc"><?php echo $arrow_up;?></a>
            <a href="admin/users/dentists/?p=1&f=email&o=desc"><?php echo $arrow_down;?></a>
            </span>
        </td>
        <td>
            Status
            <span class="links">
            <a href="admin/users/dentists/?p=1&f=hidden&o=asc"><?php echo $arrow_up;?></a>
            <a href="admin/users/dentists/?p=1&f=hidden&o=desc"><?php echo $arrow_down;?></a>
            </span>
        </td>
        <td>Pending Images</td>
    </tr>
    <?php foreach($this->dentists as $d):?>
    <tr>
        <td class="check"><input type="checkbox" name="dentists[]" value="<?php echo $d['id'];?>" /></td>
        <td>
            <?php 
                $hs = $this->headshots[$d['id']];
                $avatar = 'images/dentists/'.$hs['id'].'/'.$hs['image'];
                if(!file_exists($avatar)||!$hs['enabled_headshot']) $avatar = 'images/empty_image.png';
            ?>
            <img src="<?php echo $avatar;?>" alt=""/><?php echo $d['username']?><br />
            <a href="admin/users/edit-dentist?id=<?php echo $d['id'];?>">Edit</a>|<a href="admin/users/switch-dentist?id=<?php echo $d['id'];?>"><?php echo ($d['hidden'])?"Activate":"Inactivate";?></a>
        </td>
        <td><?php echo $d['first_name']?></td>
        <td><?php echo $d['last_name']?></td>
        <td><?php echo $this->membership_names[$d['membership_plan']];?></td>
        <td><?php echo $d['email']?></td>
        <td><?php echo ($d['hidden']) ? "Inactive" : "Active";?></td>
        <td><?php echo empty($this->pending_images[$d['id']])? "No" : "Yes";?></td>
    </tr>
    <?php endforeach;?>
    <tr class="gray">
        <td class="check"><input type="checkbox" id="all_bottom" /></td>
        <td>Username</td>
        <td>First Name</td>
        <td>Last Name</td>
        <td>Membership plan</td>
        <td>Email Address</td>
        <td>Status</td>
        <td>Pending Images</td>
    </tr>
</table>
<br />
<?php if (!empty($this->dentists)):?>
<a href="admin/users/dentists/?p=all">Reset Filters</a>&nbsp;
<?php for($i=1;$i<=$pages;$i++): if ($i!=$page):?>
<a href="admin/users/dentists/?p=<?php echo $i?>&amp;f=<?php echo isset($_REQUEST['f'])?$_REQUEST['f']:"creation_date";?>&amp;o=<?php echo isset($_REQUEST['o'])?$_REQUEST['o']:"ASC";?>"><?php echo $i?></a> &nbsp;
<?php else:?>
<b><?php echo $i?></b> &nbsp;
<?php endif;endfor;?>
<?php endif;?>
</form>