<?php
    $st = $this->section_titles;
    $q  = $this->questions;
    $l  = $this->labels;
    $pr = $this->price_ranges;
    $e  = $this->errors;
    $r  = isset($_REQUEST['save']) ? $_REQUEST : $this->patient; 
?>

    <h1>Patient [Edit]</h1>
    <br /><br /><br />
    <?php if (isset($this->errors)):?>
        <div id="errors">
            Please correct all the errors:
        </div>
    <?php endif;?><form method="post" action="admin/users/edit-patient">
        <input type="hidden" name="id" value="<?php echo $r['id'];?>" />
        <!--Section 01-->
        <fieldset>
            <legend><?php echo strip_tags($st['register_section_01_title']);?></legend>
            <div>
            <div class="field">
                <label><?php echo $l['label_username'];?>(*)</label>
                <input type="text" name="username" value="<?php echo isset($r['username'])?$r['username']:"";?>"/>
                <span class="explanation"><?php echo(isset($e['username']))? $e['username']:"";?></span>
            </div>
            <div class="clear"></div>
            <div class="field">
                <label><?php echo $l['label_email'];?>(*)</label>
                <input type="text" name="email" value="<?php echo isset($r['email'])?$r['email']:"";?>"/>
                <span class="explanation"><?php echo(isset($e['email']))? $e['email']:"";?></span>
            </div>
            <div class="field">
                <label><?php echo $l['label_password'];?>(*)</label>
                <input type="password" name="password" value="" maxlength="20"/>
                <span class="explanation"><?php echo(isset($e['password']))? $e['password']:"(Max. 20 Characters.)";?> </span>
            </div>
            <div class="field">
                <label><?php echo $l['label_retype_password'];?>(*)</label>
                <input type="password" name="retype_password" value="" maxlength="20"/>
                <span class="explanation"><?php echo(isset($e['retype_password']))? $e['retype_password']:"(re-enter your password)";?> </span>
            </div>
            </div>
            <div class="clear"></div>
        </fieldset>
        <!--Section 02-->
        <fieldset>
            <legend><?php echo strip_tags($st['register_section_02_title']);?></legend>
            <div class="field">
                <label><?php echo $l['label_firstname'];?>(*)</label>
                <input type="text" name="first_name" value="<?php echo isset($r['first_name'])?$r['first_name']:"";?>"/>
                <span class="explanation"><?php echo(isset($e['first_name']))? $e['first_name']:"";?></span>
            </div>
            <div class="field">
                <label><?php echo $l['label_lastname'];?>(*)</label>
                <input type="text" name="last_name" value="<?php echo isset($r['last_name'])?$r['last_name']:"";?>"/>
                <span class="explanation"><?php echo(isset($e['last_name']))? $e['last_name']:"";?></span>
            </div>
            <div class="field">
                <label><?php echo $l['label_district_city'];?>(*)</label>
                <input type="text" name="city" value="<?php echo isset($r['city'])?$r['city']:"";?>"/>
                <span class="explanation"><?php echo(isset($e['city']))? $e['city']:"";?></span>
            </div>
            <div class="field">
                <label><?php echo $l['label_province_state'];?>(*)</label>
                <input type="text" name="state" value="<?php echo isset($r['state'])?$r['state']:"";?>"/>
                <span class="explanation"><?php echo(isset($e['state']))? $e['state']:"";?></span>
            </div>
            <div class="field">
                <label><?php echo $l['label_country'];?>(*)</label>
                <input type="text" name="country" value="<?php echo isset($r['country'])?$r['country']:"";?>"/>
                <span class="explanation"><?php echo(isset($e['country']))? $e['country']:"";?></span>
            </div>
            <div class="field">
                <label><?php echo $l['label_phone'];?>(*)</label>
                <input type="text" name="phone_number" value="<?php echo isset($r['phone_number'])?$r['phone_number']:"";?>"/>
                <span class="explanation"><?php echo(isset($e['phone_number']))? $e['phone_number']:"";?></span>
            </div>         
            <div class="clear"></div>
        </fieldset>
        <input type="submit" name="save" value="Save" />
    </form>