<ul>
    <li>
        <a href="
        <?=
        $this->url(array(
            'module' => 'admin',
            'controller' => 'cms',
            'action' => 'index'), null, true)
        ?>">
               <?= $this->translate('List of Page') ?>
        </a>
    </li>
    <li>
        <a href="
        <?=
        $this->url(array(
            'module' => 'admin',
            'controller' => 'cms',
            'action' => 'new'), null, true)
        ?>">
               <?= $this->translate('Creation of Page') ?>
        </a>
    </li>


</ul>
