<ul>
    <li>
        <a href="
        <?=
        $this->url(array(
            'module' => 'admin',
            'controller' => 'moneda',
            'action' => 'index'), null, true)
        ?>">
               <?= $this->translate('Tipo de Monedas') ?>
        </a>
    </li>
    <li>
        <a href="
        <?=
        $this->url(array(
            'module' => 'admin',
            'controller' => 'fabricante',
            'action' => 'index'), null, true)
        ?>">
               <?= $this->translate('Manufacturer') ?>
        </a>
    </li>
    <li>
        <a href="
        <?=
        $this->url(array(
            'module' => 'admin',
            'controller' => 'categoria',
            'action' => 'index'), null, true)
        ?>">
               <?= $this->translate('Category') ?>
        </a>
    </li>
    <li>
        <a href="
        <?=
        $this->url(array(
            'module' => 'admin',
            'controller' => 'paises',
            'action' => 'index'), null, true)
        ?>">
               <?= $this->translate('paises') ?>
        </a>
    </li>
    <li>
        <a href="
        <?=
        $this->url(array(
            'module' => 'admin',
            'controller' => 'idiomas',
            'action' => 'index'), null, true)
        ?>">
               <?= $this->translate('idiomas') ?>
        </a>
    </li>
    


</ul>
