<ul>
    <li>
        <a href="
        <?=
        $this->url(array(
            'module' => 'admin',
            'controller' => 'user',
            'action' => 'activausuarios'), null, true)
        ?>">
               <?= $this->translate('usuarios pendientes') ?>
        </a>
    </li>
    <li>
        <a href="
        <?=
        $this->url(array(
            'module' => 'admin',
            'controller' => 'equipo',
            'action' => 'activaequipos'), null, true)
        ?>">
               <?= $this->translate('equipos pendientes') ?>
        </a>
    </li>
    <li>
        <a href="
        <?=
        $this->url(array(
            'module' => 'admin',
            'controller' => 'pregunta',
            'action' => 'questionunresolved'), null, true)
        ?>">
               <?= $this->translate('preguntas por responder') ?>
        </a>
    </li>
    <li>
        <a href="
        <?=
        $this->url(array(
            'module' => 'admin',
            'controller' => 'index',
            'action' => 'index'), null, true)
        ?>">
               <?= $this->translate('Nuevas ventas realizadas') ?>
        </a>
    </li>
    <li>
        <a href="
        <?=
        $this->url(array(
            'module' => 'admin',
            'controller' => 'reserva',
            'action' => 'equiposreservados'), null, true)
        ?>">
               <?= $this->translate('Equipos reservados') ?>
        </a>
    </li>

</ul>

