<ul class="subnav">
    <li>
        <a href="
        <?=
        $this->url(array(
            'module' => 'admin',
            'controller' => 'user',
            'action' => 'activausuarios'), null, true)
        ?>">
               <?= $this->translate('Activation pending users') ?>
        </a>
    </li>
    <li>
        <a href="
        <?=
        $this->url(array(
            'module' => 'admin',
            'controller' => 'index',
            'action' => 'index'), null, true)
        ?>">
               <?= $this->translate('yet approved equipment') ?>
        </a>
    </li>
    <li>
        <a href="
        <?=
        $this->url(array(
            'module' => 'admin',
            'controller' => 'index',
            'action' => 'index'), null, true)
        ?>">
               <?= $this->translate('Questions to answer') ?>
        </a>
    </li>
    <li>
        <a href="
        <?=
        $this->url(array(
            'module' => 'admin',
            'controller' => 'index',
            'action' => 'index'), null, true)
        ?>">
               <?= $this->translate('Nuevas ventas realizadas') ?>
        </a>
    </li>
    <li>
        <a href="
        <?=
        $this->url(array(
            'module' => 'admin',
            'controller' => 'reserva',
            'action' => 'equiposreservados'), null, true)
        ?>">
               <?= $this->translate('Equipos reservados') ?>
        </a>
    </li>

</ul>
