<div class="sub" style="width: 600px; opacity: 0; display: none; ">
    <ul>
        <li>
            <h2>
                <a href="#">
                    <?= $this->translate( 'Configuration' ); ?>
                </a>
            </h2>
        </li>
        <li>
            <a href="
            <?=
            $this->url( array(
                'module' => 'admin' ,
                'controller' => 'tipousuario' ,
                'action' => 'index' ) , null , true )
            ?>">
                   <?= $this->translate( 'Activation pending users' ) ?>
            </a>
        </li>
        <li>
            <a href="
            <?=
            $this->url( array(
                'module' => 'admin' ,
                'controller' => 'index' ,
                'action' => 'index' ) , null , true )
            ?>">
                   <?= $this->translate( 'yet approved equipment' ) ?>
            </a>
        </li>
        <li>
            <a href="
            <?=
            $this->url( array(
                'module' => 'admin' ,
                'controller' => 'index' ,
                'action' => 'index' ) , null , true )
            ?>">
                   <?= $this->translate( 'Questions to answer' ) ?>
            </a>
        </li>
        <li>
            <a href="
            <?=
            $this->url( array(
                'module' => 'admin' ,
                'controller' => 'index' ,
                'action' => 'index' ) , null , true )
            ?>">
                   <?= $this->translate( 'Nuevas ventas realizadas' ) ?>
            </a>
        </li>
        <li>
            <a href="
            <?=
            $this->url( array(
                'module' => 'admin' ,
                'controller' => 'index' ,
                'action' => 'index' ) , null , true )
            ?>">
                   <?= $this->translate( 'Equipos reservados' ) ?>
            </a>
        </li>

    </ul>

</div>