<?
if (
        !is_null( $this->producto->modelo )
 ):
    ?>
    <span class="device-description-field">
        <?= $this->translate( 'Model' ) ?>
    </span>
    <span>
        <?= $this->producto->modelo ?>
    </span>
<? endif; ?>

<?
if (
        !is_null(
                $this->producto->pais
        )
 ):
    ?>

    <span class="device-description-field">
        <?= $this->translate( 'Origin' ) ?>
    </span>
    <span>
        <?= $this->producto->pais ?>
    </span>
<? endif; ?>

<?
if (
        !is_null(
                $this->producto->id
        )
 ):
    ?>
    <span class="device-description-field">
        <?= $this->translate( 'Article ID' ) ?>
    </span>
    <span>
        <?= $this->producto->id ?>
    </span>
<? endif; ?>

<?
if (
        !is_null(
                $this->producto->fechafabricacion
        )
 ):
    ?>
    <span class="device-description-field">
        <?= $this->translate( 'Date/Year of manufacture' ) ?>
    </span>
    <span>
        <?= $this->producto->fechafabricacion ?>
    </span>
<? endif; ?>

<?
if (
        !is_null(
                $this->producto->pesoEstimado
        )
 ):
    ?>
    <span class="device-description-field">
        <?= $this->translate( 'Estimated weight (KG)' ) ?>
    </span>
    <span>
        <?= $this->producto->pesoEstimado ?>
    </span>
<? endif; ?>

<?
if (
        !is_null(
                $this->producto->calidad
        )
 ):
    ?>
    <span class="device-description-field">
        <?= $this->translate( 'Quality/Condition' ) ?>
    </span>
    <span>
        <?= $this->producto->calidad ?>
    </span>
<? endif; ?>

<?
if (
        !is_null(
                $this->producto->cantidad
        )
 ):
    ?>
    <span class="device-description-field">
        <?= $this->translate( 'Mode Amount of equipment' ) ?>
    </span>
    <span>
        <?= $this->producto->cantidad ?>
    </span>
<? endif; ?>
<?
if (
        !is_null(
                $this->producto->pais
        )
 ):
    ?>
    <span class="device-description-field">
        <?= $this->translate( 'Description' ) ?>
    </span>
    <span>
        Thermo Scientifig Revco. Ultima Plus<br/>
        Placing out of operation: March 2010
    </span>
<? endif; ?>
<?
if (
        !is_null(
                $this->producto->pais
        )
 ):
    ?>
    <span class="device-description-field">
        <?= $this->translate( 'Specifications' ) ?>
    </span>
    <span>
        <?= $this->translate( 'Temperature Range' ) ?>: from -50&deg; until 86&deg;<br/>
        <?= $this->translate( 'Capacity Cu.' ) ?>: 691 (L)<br/>
        Electrical Amps/Breaker 230V/60 Hz 1&empty;<br/>
        <?= $this->translate( 'Interior dimensions' ) ?>: HxWxD (mm) (1283 x  876 x 616)<br/>
        <?= $this->translate( 'Exterior dimensions' ) ?>: HxWxD (mm) (1283 x  876 x 616)<br/>
        <?= $this->translate( 'Shipping weight' ) ?>: 376 Kg.<br/>
        Power Tension 230v freq. 50 Phase: 1<br/>
        <?= $this->translate( 'Amps' ) ?>: 12A
    </span>
<? endif; ?>
