<?
if (
        !is_null( $this->producto->modelo )
 ):
    ?>
    <span class="device-description-field">
        <?= $this->translate( 'Model' ) ?>
    </span>
    <span>
        <?= $this->producto->modelo ?>
    </span>
<? endif; ?>

<?
if (
        !is_null(
                $this->producto->pais
        )
 ):
    ?>

    <span class="device-description-field">
        <?= $this->translate( 'Origin' ) ?>
    </span>
    <span>
        <?= $this->producto->pais ?>
    </span>
<? endif; ?>

<?
if (
        !is_null(
                $this->producto->id
        )
 ):
    ?>
    <span class="device-description-field">
        <?= $this->translate( 'Article ID' ) ?>
    </span>
    <span>
        <?= $this->producto->id ?>
    </span>
<? endif; ?>

<?
if (
        !is_null(
                $this->producto->fechafabricacion
        )
 ):
    ?>
    <span class="device-description-field">
        <?= $this->translate( 'Date/Year of manufacture' ) ?>
    </span>
    <span>
        <?= $this->producto->fechafabricacion ?>
    </span>
<? endif; ?>

<?
if (
        !is_null(
                $this->producto->pesoEstimado
        )
 ):
    ?>
    <span class="device-description-field">
        <?= $this->translate( 'Estimated weight (KG)' ) ?>
    </span>
    <span>
        <?= $this->producto->pesoEstimado ?>
    </span>
<? endif; ?>

<? if ( !is_null( $this->producto->size ) ): ?>
    <span class="device-description-field">
        <?= $this->translate( 'tamaño' ) ?>
    </span>
    <span>
        <?= $this->producto->size ?>
    </span>
<? endif; ?>

<? if ( !is_null( $this->producto->ancho ) ): ?>
    <span class="device-description-field">
        <?= $this->translate( 'ancho' ) ?>
    </span>
    <span>
        <?= $this->producto->ancho ?>
    </span>
<? endif; ?>

<? if ( !is_null( $this->producto->alto ) ): ?>
    <span class="device-description-field">
        <?= $this->translate( 'alto' ) ?>
    </span>
    <span>
        <?= $this->producto->alto ?>
    </span>
<? endif; ?>

<? if ( !is_null( $this->producto->sizeCaja ) ): ?>
    <span class="device-description-field">
        <?= $this->translate( 'tamaño de la caja' ) ?>
    </span>
    <span>
        <?= $this->producto->sizeCaja ?>
    </span>
<? endif; ?>


<?
if (
        !is_null(
                $this->producto->calidad
        )
 ):
    ?>
    <span class="device-description-field">
        <?= $this->translate( 'Quality/Condition' ) ?>
    </span>
    <span>
        <?= $this->producto->calidad ?>
    </span>
<? endif; ?>

<?
if (
        !is_null(
                $this->producto->cantidad
        )
 ):
    ?>
    <span class="device-description-field">
        <?= $this->translate( 'Mode Amount of equipment' ) ?>
    </span>
    <span>
        <?= $this->producto->cantidad ?>
    </span>
<? endif; ?>
<?
if (
        !is_null(
                $this->producto->pais
        )
 ):
    ?>
    <span class="device-description-field">
        <?= $this->translate( 'Description' ) ?>
    </span>
    <span>
        <?= $this->producto->pais ?>
    </span>
<? endif; ?>
