<div id="logo-top">
    <img src="/images/logo-top.png">
</div>
<div id="lang-selection-top">
    <!-- Get by PHP function -->
    <a href="#">English</a> |
    <a href="#">Espa&ntilde;ol</a> |
    <a href="#">Deutsch</a>
</div>
<div>
    Bienvenido <?= Zend_Auth::getInstance()->hasIdentity()
                    ? $this->authUser : 'Visitante' ?>

    <? if( Zend_Auth::getInstance()->hasIdentity() ): ?>
        <a href="<?=
    $this->url( array( 'action' => 'logout' , 'controller' => 'test' ) , null ,
                true )

        ?>">Logout</a>
       <?php else: ?>
        <a href="<?=
       $this->url( array( 'action' => 'index' , 'controller' => 'usuario' ) ,
                   null , true )

           ?>">Login</a> |
       <? endif; ?>
</div>