<ul id="topnav">
    <li>
        <a class="current" href="
           <?=
           $this->url( array(
               'module' => 'admin' ,
               'controller' => 'index' ,
               'action' => 'index' ) , null , true )
           ?>">
            <span>

                <?= $this->translate( 'Config' ); ?>

            </span>

        </a>
        <?= $this->render( 'navegacion/_config.phtml' ); ?>

    </li>
    <li>
        <a  href="
        <?=
        $this->url( array(
            'module' => 'admin' ,
            'controller' => 'equipo' ,
            'action' => 'index' ) , null , true )
        ?>">
            <span>

                <?= $this->translate( 'Equipment' ); ?>

            </span>

        </a>
        <?= $this->render( 'navegacion/_equipment.phtml' ); ?>
    </li>
    <li>
        <a href="
        <?=
        $this->url( array(
            'module' => 'admin' ,
            'controller' => 'fabricante' ,
            'action' => 'index' ) , null , true )
        ?>">
            <span>

                <?= $this->translate( 'Manufacturers' ); ?>

            </span>

        </a>
    </li>
    <li>
        <a  href="
        <?=
        $this->url( array(
            'module' => 'admin' ,
            'controller' => 'categoria' ,
            'action' => 'index' ) , null , true )
        ?>">
            <span>

                <?= $this->translate( 'Category' ); ?>

            </span>

        </a>
    </li>
    <li>
        <a href="
        <?=
        $this->url( array(
            'module' => 'admin' ,
            'controller' => 'moneda' ,
            'action' => 'index' ) , null , true )
        ?>">
            <span>

                <?= $this->translate( 'Currency' ); ?>

            </span>

        </a>
    </li>
    <li>
        <a  href="
        <?=
        $this->url( array(
            'module' => 'admin' ,
            'controller' => 'user' ,
            'action' => 'index' ) , null , true )
        ?>">
            <span>

                <?= $this->translate( 'User' ); ?>

            </span>

        </a>
    </li>

</ul>

