<ul id="topnav">
    <li>
        <a class="current" href="
           <?=
           $this->url( array(
               'module' => 'admin' ,
               'controller' => 'index' ,
               'action' => 'index' ) , null , true )
           ?>">
            <span>

                <?= $this->translate( 'Desk' ); ?>

            </span>

        </a>
        <?= $this->render( 'navegacion/_desk.phtml' ); ?>

    </li>
    <li>
        <a  href="
        <?=
        $this->url( array(
            'module' => 'admin' ,
            'controller' => 'user' ,
            'action' => 'index' ) , null , true )
        ?>">
            <span>

                <?= $this->translate( 'Users' ); ?>

            </span>

        </a>

    </li>
    <li>
        <a href="
        <?=
        $this->url( array(
            'module' => 'admin' ,
            'controller' => 'equipo' ,
            'action' => 'index' ) , null , true )
        ?>">
            <span>

                <?= $this->translate( 'Equipment' ); ?>

            </span>

        </a>
    </li>
    <li>
        <a  href="
        <?=
        $this->url( array(
            'module' => 'admin' ,
            'controller' => 'equipo' ,
            'action' => 'index' ) , null , true )
        ?>">
            <span>

                <?= $this->translate( 'Questions' ); ?>

            </span>

        </a>
    </li>
    <li>
        <a href="
        <?=
        $this->url( array(
            'module' => 'admin' ,
            'controller' => 'operacion' ,
            'action' => 'index' ) , null , true )
        ?>">
            <span>

                <?= $this->translate( 'Operations' ); ?>

            </span>

        </a>
    </li>
    <li>
        <a>
            <span>

                <?= $this->translate( 'Statistics' ); ?>

            </span>

        </a>
        <?= $this->render( 'navegacion/_statistics.phtml' ); ?>
    </li>
    <li>
        <a >
            <span>

                <?= $this->translate( 'Configuration' ); ?>

            </span>

        </a>
        <?= $this->render( 'navegacion/_configuration.phtml' ); ?>
    </li>

</ul>

