<div id="backNav">

    <div id="nav" class="container_16">

        <div  class="grid_14 alpha">
            <ul id="jsddm">
                <li>
                    <a id ="desk-admin" 
                       onclick="fnSelectedItem(this.id)">
                        <span>
                            <?= $this->translate('DESK'); ?>
                        </span>

                    </a>
                    <?= $this->render( 'navegacion/_desk.phtml' ); ?>
                </li>


                <li>
                    <a id ="users-admin" onclick="fnSelectedItem(this.id)"  
                       href="
                       <?=
                       $this->url(array(
                           'module' => 'admin',
                           'controller' => 'user',
                           'action' => 'index'), null, true)
                       ?>">
                        <span>
                            <?= $this->translate('USER'); ?>
                        </span>
                    </a>
                </li>
                <li>
                    <a id ="equipment-admin" onclick="fnSelectedItem(this.id)" href="
                    <?=
                    $this->url(array(
                        'module' => 'admin',
                        'controller' => 'equipo',
                        'action' => 'index'), null, true)
                    ?>">
                        <span>
                            <?= $this->translate('EQUIPMENT'); ?>
                        </span>
                    </a>
                </li>
                <li>
                    <a id ="questions-admin" 
                       onclick="fnSelectedItem(this.id)" href="
                       <?=
                       $this->url(array(
                           'module' => 'admin',
                           'controller' => 'pregunta',
                           'action' => 'index'), null, true)
                       ?>">
                        <span>
                            <?= $this->translate('QUESTIONS'); ?> 
                        </span>
                    </a>
                </li>
                <li>
                    <a id ="operations-admin" 
                       onclick="fnSelectedItem(this.id)" href="
                       <?=
                       $this->url(array(
                           'module' => 'admin',
                           'controller' => 'operacion',
                           'action' => 'index'), null, true)
                       ?>">
                        <span>

                            <?= $this->translate('OPERATIONS'); ?>

                        </span> 
                    </a>
                </li>
                <li>
                    <a id ="stadistics-admin" 
                       onclick="fnSelectedItem(this.id)">
                        <span>

                            <?= $this->translate('STATISTICS '); ?>

                        </span>
                    </a>
                    <?= $this->render('navegacion/_statistics.phtml'); ?>
                </li>
                <li>
                    <a id ="configuration-admin" 
                       onclick="fnSelectedItem(this.id)">
                        <span>

                            <?= $this->translate('CONFIGURATION'); ?>

                        </span> 
                    </a>
                </li>
                <li>
                    <a id ="cms-admin" onclick="fnSelectedItem(this.id)">
                        <span>

                            <?= $this->translate('CMS'); ?>

                        </span> 
                    </a>
                    <?= $this->render('navegacion/_cms.phtml'); ?>
                </li>

            </ul>
        </div>
        <div class="grid_2 omega">
            <span id="help">
                <?= $this->translate('obtener ayuda') ?> 
            </span>
        </div>
        <div class="clear">

        </div>
    </div>
</div>
