<!doctype html>
<html lang="en">

    <head>

        <meta charset="utf-8" />

        <?= $this->headTitle() ?> 
        <link href="/images/favicon.ico" rel="shortcut icon" type="image/x-icon" />
        <meta name="viewport" content="width=device-width, initial-scale=1.0" />
        <!-- 1140px Grid styles for IE -->
        <!--[if lte IE 9]>
        <link rel="stylesheet" href="/theme/admin/css/ie.css" type="text/css" media="screen" />
        <![endif]-->
        <?
        $this->headLink()->appendStylesheet( '/theme/admin/css/1140.css' )
                ->appendStylesheet( '/theme/admin/css/styles.css' )
                ->appendStylesheet( '/theme/admin/css/style.css' )
//                ->appendStylesheet(
//                        '/theme/admin/css/redmond/jquery-ui-1.8.16.custom.css'
//                )
        ;
        ?>
        <?= $this->headLink() ?>        
        <?= $this->jQuery() ?>  
        <?=
        $this->headScript()
                ->appendFile( '/theme/admin/js/css3-mediaqueries.js' )
                ->appendFile( '/theme/admin/js/jquery.hoverIntent.minified.js' )
                ->appendFile( '/theme/admin/js/menu.js' )
        ;
        ?> 


        <!--Delete embedded styles, just for example.-->
        <style type="text/css">

            body {
                font-family: "Helvetica Neue", Helvetica, Arial, sans-serif;
            }

            .container p {
                color: #fff;
                line-height: 100px;
                background: #000;
                text-align: center;
                margin: 20px 0 0 0;
            }

        </style>

    </head>


    <body>
        <header>
            <div class="container header">
                <?= $this->render( '_header.phtml' ) ?>
            </div>

            <nav>
                <div class="container nav">
                    <!--            <div class="row">-->
                    <div id="dolphincontainer">
                        <div id="dolphinnav">
                            <?= $this->render( '_navegacion.phtml' ); ?>
                        </div>
                    </div>
                    <!--            </div>-->
                </div>

            </nav>
        </header>


        <section>
            <div class="container body">
                <div class="row">


                    <div class="eightcol">
                        <?=
                        $this->render( '_messages.phtml' );
                        ?>

                        <?=
                        $this->layout()->content
                        ?>
                    </div>


                    <div class="fourcol last">
                        Funciones de Mas solicitados
                    </div>

                </div>
            </div>
        </section>

        <footer>
            <div class="container footer">
                <div class="row">
                    <?= $this->render( '_footer.phtml' ); ?>
                </div>
            </div>
        </footer>


    </body>

</html>

