<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml" xml:lang="en">
    <head>
        <meta http-equiv="Content-Type" content="text/html;charset=UTF-8" />

        <?= $this->headTitle() ?> 
        <link href="/images/favicon.ico" rel="shortcut icon" type="image/x-icon" />
        <?=
        $this->headLink()
                ->appendStylesheet( '/css/grid-960/styles/reset.css' )
                ->appendStylesheet( '/css/grid-960/styles/text.css' )
                ->appendStylesheet( '/css/grid-960/styles/960.css' )
                ->appendStylesheet( '/theme/admin/css/styleNew.css' )
                ->appendStylesheet( '/theme/admin/css/form.css' )
                ->appendStylesheet( '/css/style-menu.css' )
        ;
        ?>

        <?=
        $this->jQuery()->setVersion( '1.4.2' )
                ->setUiVersion( '1.8.16' )
                ->addStylesheet(
                        '/theme/admin/css/redmond/jquery-ui-1.8.16.custom.css'
                )
                ->enable()
                ->uiEnable();
        ?>      

        <?=
        $this->headScript()
                ->appendFile(
                        '/js/ckeditor/ckeditor.js'
                )
                ->appendFile(
                        '/theme/admin/js/css3-mediaqueries.js'
                )
                ->appendFile(
                        '/theme/admin/js/jquery.hoverIntent.minified.js'
                )
                ->appendFile(
                        '/theme/admin/js/menu.js'
                )
                ->appendFile(
                        '/theme/default/js/accionmenuadmin.js'
                )
                ->appendFile(
                        '/js/CookieJS.js'
                )
                ->appendFile(
                        '/theme/admin/js/menuNew.js'
                )
        ;
        ?> 
    </head>
    <body>
        <div id="main">
            <div id="backHeader">
                <div id="header" class="container_16">

                    <div id="logo" class="grid_8 alpha">
                        <img id="imgLogo" src="/theme/admin/images/logo-admin.png" />
                    </div>

                    <div id="welcome" class="grid_8 omega">
                        bienvenido Luis Alberto Mayta
                    </div>
                    <div class="clear">

                    </div>

                </div>
                <div id="backNav">


                    <div id="nav" class="container_16">

                        <div class="grid_14 alpha">
                            <ul id="jsddm">
                                <?= $this->render( '_navegacion.phtml' ); ?>
                            </ul>
                        </div>
                        <div class="grid_2 omega">
                            <span id="help">
                                <?= $this->translate( 'obtener ayuda' ) ?> 
                            </span>
                        </div>
                        <div class="clear">

                        </div>
                    </div>
                </div>
            </div>
            <div id="headcontent" class="container_16">
                <div id="titulo" class="grid_12 alpha">
                    <h2>
                        <?= $this->translate( 'dashboard' ) ?>

                    </h2>
                </div>
                <div id="messages" class="grid_4 omega">
                    <?= $this->render( '_messages.phtml' ); ?>
                </div>
                <div class="clear">

                </div>

            </div>
            <div id="content" class="container_16">
                <div id="contentDetails" class="grid_16">

                    <?= $this->layout()->content ?>
                </div>
                <div class="clear">

                </div>
            </div>

            <div id="backFooter">

                <div id="footer" class="container_16">
                    <div id="footerDetails" class="grid_16">


                    </div>
                    <div class="clear">

                    </div>
                </div>
            </div>
        </div>
    </body>
</html>


