
<img id="img-logo" 
     src="/theme/default/image/middle-header.png" 
     alt="MedTechTrade"/>
<h1>
    <?= $this->translate('Welcome to Medtechtrade'); ?>
</h1>
<p>
    <?= $this->translate('home-welcome-txt-p1') ?>
</p>

<p>
    <?= $this->translate('home-welcome-txt-p2') ?>
</p>

<header>
    <h3><?= $this->translate('Top Offers') ?></h3>
</header>
<div class="device-horizontal-list">
    <?php foreach ($this->oferEquipo as $producto): ?>
        <div>
            <a href="
            <?=
            $this->url(
                    array(
                'slug' => $producto->slug), 'slugEquipment', true
            )
            ?>
               " title="<?= $producto->slug ?>">
                   <?php
                   $url = (is_null($producto->imagen)) ?
                           '/media/catalog/product/avatar/no_image.png' :
                           '/media/catalog/product/avatar/' . $producto->imagen
                   ?>
                <img src="<?= $url ?>" 
                     alt="<?= $producto->nombre ?>"
                     />
              
            </a>
            <span class="manufacturer">
                <?= $this->translate('Manufacturer') ?>
                : <?= $producto->fabricante ?>
            </span>
            <span class="name">
                <?= $this->translate('Product name') ?>
                : 
                <?= $producto->nombre ?>
            </span>
            <a href="
            <?=
            $this->url(
                    array(
                'slug' => $producto->slug
                    ), 'slugEquipment', true
            )
            ?>
               " title="<?= $producto->slug ?>">
                <span>
                    <?= $this->translate('View details') ?>
                </span>
            </a>
        </div>
    <?php endforeach; ?>

</div>

<!--Agregando Datos-->

<!-- "previous page" action -->
<!--<a class="prev browse left"></a>-->

<!-- root element for scrollable -->
<!--<div class="scrollable">   -->

<!-- root element for the items -->
<!--    <div class="items">-->

<!-- 1-5 -->
<!--        <div>
            <img src="http://farm1.static.flickr.com/143/321464099_a7cfcb95cf_t.jpg" />
            <img src="http://farm4.static.flickr.com/3089/2796719087_c3ee89a730_t.jpg" />
            <img src="http://farm1.static.flickr.com/79/244441862_08ec9b6b49_t.jpg" />
            <img src="http://farm1.static.flickr.com/28/66523124_b468cf4978_t.jpg" />
        </div>-->

<!-- 5-10 -->
<!--        <div>
            <img src="http://farm1.static.flickr.com/163/399223609_db47d35b7c_t.jpg" />
            <img src="http://farm1.static.flickr.com/135/321464104_c010dbf34c_t.jpg" />
            <img src="http://farm1.static.flickr.com/40/117346184_9760f3aabc_t.jpg" />
            <img src="http://farm1.static.flickr.com/153/399232237_6928a527c1_t.jpg" />
        </div>-->

<!-- 10-15 -->
<!--        <div>
            <img src="http://farm4.static.flickr.com/3629/3323896446_3b87a8bf75_t.jpg" />
            <img src="http://farm4.static.flickr.com/3023/3323897466_e61624f6de_t.jpg" />
            <img src="http://farm4.static.flickr.com/3650/3323058611_d35c894fab_t.jpg" />
            <img src="http://farm4.static.flickr.com/3635/3323893254_3183671257_t.jpg" />
        </div>-->

<!--    </div>-->

<!--</div>-->

<!-- "next page" action -->
<!--<a class="next browse right"></a>-->
<!--fin de Datos-->