<div><img src="images/stories/frontpage-peru.png" border="0" alt="MedTechTrade" style="border: 0pt none;" /></div>
<div class="contentheading" style="margin-bottom:10px;"><br />Bienvenido a MedTechTrade Perú</div>
<p>MedTechTrade es su especialista suizo en la compra y venta a nivel mundial de equipamiento médico usado y reacondicionado.</p>
<p> </p>
<h3>Equipos medicos suizos a su alcanze</h3>
<p><strong><img src="/images/flags/16/flag_CH.png" border="0" alt="flag ch" style="border: 0pt none;" /> MedTechTrade</strong> es una empresa suiza, dedicada a la venta de de equipamento medico reacondicionado de marcas líderes en el mercado mundial.</p>
<p><strong><img src="/images/flags/16/flag_CH.png" border="0" alt="flag ch" style="border: 0pt none;" /> </strong><strong>MedTechTrade</strong> contribuye con equipamiento médico proveniente de Suiza, Alemania y Austria que responde a las exigencias de nuestros clientes, aplicando especial cuidado para que distintos parámetros como calidad, confiabilidad, precisión, flexibilidad y ahorro en costos de mantención, se cumplan.</p>
<p> </p>
<h2><strong>Nuestras top-3 ofertas destacadas: </strong></h2>
<p> </p>
<table border="0">
    <tbody>
        <tr>
            <td><img src="/uploads/361a_t.jpg" border="0" alt="Microscopio Zeiss" width="76" height="100" />..</td>
            <td><strong>Fabricante</strong>: Zeiss<br /><strong>Modelo</strong>: Standard 14<br /><strong>Descripción</strong>: Microscopio Zeiss<br /><a href="es/microscopios/156/microscop/287">Link...</a></td>
        </tr>
        <tr>
            <td></td>
            <td>.</td>
        </tr>
        <tr>
            <td><img src="/uploads/179a.jpg" border="0" alt="Monitor de pacientes" width="77" height="100" />..</td>
            <td><strong>Fabricante</strong>: Marquette<br /><strong>Modelo</strong>: Solar 8000/Tram250sl <br /><strong>Descripción</strong>: Equipo de monitoreo de pacientes<br /><a href="es/equipos-de-monitoreo/159/critical-care-monitoring/179">Link...</a></td>
        </tr>
        <tr>
            <td></td>
            <td>.</td>
        </tr>
        <tr>
            <td><img src="/uploads/228c.jpg" border="0" alt="Set cirugia de oido" width="53" height="100" />..</td>
            <td><strong>Fabricante</strong>: Karl Storz<br /><strong>Descripción</strong>: Instrumetal Quirúrgico para cirugía de oido<br /><a href="es/instrumental-quirurgico/158/ear-surgery-set/228">Link...</a></td>
        </tr>
        <tr>
            <td></td>
            <td><br /><strong> </strong></td>
        </tr>
    </tbody>
</table>