<header>
    <img src="/theme/default/image/middle-header.png" alt="MedTechTrade"/>
    <h1>
        <?= $this->translate( 'Welcome to Medtechtrade' ); ?>
    </h1>
</header>

<p>MedTechTrade is a global trade association for technology manufacturers,
    research institutions, allied professional services and development organizations
    with shared interests in collaborative developing technologies, products and services
    for the global medical products marketplace.
</p>

<p>Our goal is to enable and accelerate trading of medical devices
    for companies and institutional organisation.</p>

<header>

    <h3><?= $this->translate( 'Top Offers' ) ?></h3>
</header>
<p>Our goal is to enable and accelerate trading of medical devices
    form companies and institutional organisation</p>
<div class="device-horizontal-list">
    <?php foreach ( $this->oferEquipo as $producto ): ?>
        <div>
            <img src="/media/catalog/product/device-00.png" alt="Device 00">
            <span class="manufacturer">
                <?= $this->translate( 'Manufacturer' ) ?>
                : <?= $producto->fabricante ?>
            </span>
            <span class="name">
                <?= $this->translate( 'Product name' ) ?>
                : 
                <?= $producto->nombre ?>
            </span>
            <a href="
            <?=
            $this->url(
                    array(
                'controller' => 'equipo' ,
                'action' => 'ver' , 'id' => $producto->id
                    ) , null , true
            )
            ?>">
                <span>
                    <?= $this->translate( 'View details' ) ?>
                </span>
            </a>
        </div>
    <?php endforeach; ?>

</div>

<a class="prev browse left">
</a>

<div class="scrollable">
    <div class="items">
        <?
        for (
        $i = 0; $i < 9; $i + 3
        ):
            ?>

            <div>
                <?
                foreach (
                $this->items->getItems(
                        $i , 3
                ) as $item ):
                    ?>
                    <span 
                        style="font-family:verdana,Lucida,arial;font-size: 4.1em;">
                            <?= $item ?>
                    </span>
                <? endforeach; ?>
            </div>

        <? endfor; ?>

    </div>
</div>
<a class="prev browse right">
</a>
