<?php 
    $r=isset($_REQUEST['save']) ? $_REQUEST : $this->forum;
?>
<h1>Forum [Edit]</h1>
<br /><br /><br />
<?php if(isset($this->errors)):?>
    <?php $e = $this->errors;?>
<div id="errors">
    Please correct the errors. 
</div>
<?php endif;?>
<form method="post" action="admin/forum/edit-forum">
    <input type="hidden" name="id" value="<?php echo $r['id'];?>" />
    <div class="field">
    	<label>Title</label>
    	<input type="text" name="title" value="<?php echo (isset($r['title']))? $r['title'] : ""?>" />
    	<span class="explanation"></span>
    </div>
    <div class="field">
    	<label>Owner</label>
    	<select name="account_id">
            <option value="0">Select One...</option>
            <?php foreach ($this->authors as $key=>$author):?>
            <option value="<?php echo $key;?>" <?php if(isset($r['account_id']) && $key==$r['account_id']) echo 'selected="selected"';?>><?php echo $author;?></option>
            <?php endforeach;?>
        </select>
    	<span class="explanation"></span>
    </div>
    <div class="field">
    	<label>Description</label>
    	<input type="text" name="description" value="<?php echo (isset($r['description']))? $r['description'] : ""?>"" />
    	<span class="explanation"></span>
    </div>
    <div class="field">
    	<label>Creation Date</label>
    	<input type="text" name="creation_date" value="<?php echo $r['creation_date']?>" readonly="readonly"/>
    	<span class="explanation"></span>
    </div>
    <input type="submit" name="save" value="Save" />
</form>