<?php 
    if(isset($_REQUEST['search'])) $s = $_REQUEST;
    else if (isset($this->session->search_post)) {$s=$this->session->search_post;}
    $arrow_up = '<img class="arrow" src="images/arrow_up.png" alt="ASC" title="ASC"/>';
    $arrow_down = '<img class="arrow" src="images/arrow_down.png" alt="DESC" title="DESC"/>';
?>
<h1>Posts Manager</h1>
<br /><br /><br />
<form method="post" action="admin/forum/posts">
    <div class="field">
    	<label>Search Term</label>
    	<input type="text" name="search_term" value="<?php echo (isset($s['search_term']))? $s['search_term'] : ""?>" />
    	<span class="explanation"></span>
    </div>
    <div class="field">
    	<label>Thread</label>
    	<select name="thread_id">
            <option value="0">Select One...</option>
            <?php foreach ($this->threads as $key=>$thread):?>
            <option value="<?php echo $key;?>" <?php if(isset($s['thread_id']) && $key==$s['thread_id']) echo 'selected="selected"';?>><?php echo $thread;?></option>
            <?php endforeach;?>
        </select>
    	<span class="explanation"></span>
    </div>
    <div class="field">
    	<label>Posted By</label>
    	<select name="account_id">
            <option value="0">Select One...</option>
            <?php foreach ($this->authors as $key=>$author):?>
            <option value="<?php echo $key;?>" <?php if(isset($s['account_id']) && $key==$s['account_id']) echo 'selected="selected"';?>><?php echo $author;?></option>
            <?php endforeach;?>
        </select>
    	<span class="explanation"></span>
    </div>
    <div class="field">
    	<label>Approval status</label>
    	<select name="hidden">
            <option value="-1">Select a status...</option>
            <option value="0" <?php if(isset($s['hidden']) && $s['hidden']==0) echo 'selected="selected"';?>>Approved</option>
            <option value="1" <?php if(isset($s['hidden']) && $s['hidden']==1) echo 'selected="selected"';?>>Not approved</option>
        </select>
    	<span class="explanation"></span>
    </div>
    <div class="field">
    	<label>Start Date</label>
    	<input type="text" class="date-picker" name="date_from" value="<?php echo (isset($s['date_from']))? $s['date_from'] : ""?>" />
    	<span class="explanation"></span>
    </div>
    <div class="clear"></div>
    <div class="field">
    	<label>End Date</label>
    	<input type="text" class="date-picker" name="date_to" value="<?php echo (isset($s['date_to']))? $s['date_to'] : ""?>" />
    	<span class="explanation"></span>
    </div>
    <div class="clear"></div>
    <input type="submit" name="search" value="Search"/>
</form>

<?php if (isset($this->errors)):?>
    <div id="errors">
        <ul>
        <?php foreach ($this->errors as $error):?>
            <li><?php echo $error;?></li>
        <?php endforeach?>
        </ul>
    </div>
<?php endif;?>

<form method="post" action="admin/forum/posts">
<select name="hidden">
    <option value="0">Approve</option>
    <option value="1">Reject</option>
</select>
<input type="submit" name="apply" value="Apply" class="small_button"/>
<?php 
if(!empty($this->posts)) : 
$count = count($this->posts);
$page= @$_REQUEST['p'];
$size=8;
$pages = $count/$size + ($count%$size>0?1:0);
if (!$page || $page>$pages) $page=1;
$aux = array_chunk($this->posts,$size);
$this->posts = $aux[$page-1];
?>
<br />
<a href="admin/forum/posts/?p=all">Reset Filters</a>&nbsp;
<?php for($i=1;$i<=$pages;$i++): if ($i!=$page):?>
<a href="admin/forum/posts/?p=<?php echo $i?>&amp;f=<?php echo isset($_REQUEST['f'])?$_REQUEST['f']:"creation_date";?>&amp;o=<?php echo isset($_REQUEST['o'])?$_REQUEST['o']:"ASC";?>"><?php echo $i?></a> &nbsp;
<?php else:?>
<b><?php echo $i?></b> &nbsp;
<?php endif;endfor;?>
<br /><br />
<?php endif;?>
<table>
    <thead>
    <tr class="gray">
        <td class="check"><input type="checkbox" id="all" /></td>
        <td>
            Content
            <span class="links">
            <a href="admin/forum/posts/?p=1&f=title&o=asc"><?php echo $arrow_up;?></a>
            <a href="admin/forum/posts/?p=1&f=title&o=desc"><?php echo $arrow_down;?></a>
            </span>
        </td>
        <td>
            Posted by
            <span class="links">
            <a href="admin/forum/posts/?p=1&f=author&o=asc"><?php echo $arrow_up;?></a>
            <a href="admin/forum/posts/?p=1&f=author&o=desc"><?php echo $arrow_down;?></a>
            </span>
        </td>
        <td>
            Posted in
            <span class="links">
            <a href="admin/forum/posts/?p=1&f=thread&o=asc"><?php echo $arrow_up;?></a>
            <a href="admin/forum/posts/?p=1&f=thread&o=desc"><?php echo $arrow_down;?></a>
            </span>
        </td>
        <td>
            Post Date
            <span class="links">
            <a href="admin/forum/posts/?p=1&f=creation_date&o=asc"><?php echo $arrow_up;?></a>
            <a href="admin/forum/posts/?p=1&f=creation_date&o=desc"><?php echo $arrow_down;?></a>
            </span>
        </td>
        <td>Status</td>
        <td></td>
    </tr>
    </thead>
    <tbody>
    <?php foreach($this->posts as $a):?>
    <tr>
        <td class="check"><input type="checkbox" name="posts[]" value="<?php echo $a['id'];?>" /></td>
        <td><?php echo strip_tags($a['content'])?></td>
        <td><?php echo $a['author'];?></td>
        <td><?php echo $a['thread'];?></td>
        <td><?php echo $a['creation_date'];?></td>
        <td>
            <?php 
                if($a['hidden']) $status = "Not approved";
                else $status = "Approved";
                echo $status;
            ;?>
        </td>
        <td>          
            <a href="admin/forum/switch-post-status/?id=<?php echo $a['id'];?>"><?php echo ($a['hidden'])?"Approve":"Reject";?></a>
        </td>
    </tr>
    <?php endforeach;?>
    </tbody>
    <tr class="gray">
        <td class="check"><input type="checkbox" id="all_bottom" /></td>
        <td>Content</td>
        <td>Posted by</td>
        <td>Posted in</td>
        <td>Post date</td>
        <td>Status</td>
        <td></td>
    </tr>
</table>
<br />
<?php if(!empty($this->posts)):?>
<a href="admin/forum/posts/?p=all">Reset Filters</a>&nbsp;
<?php for($i=1;$i<=$pages;$i++): if ($i!=$page):?>
<a href="admin/forum/posts/?p=<?php echo $i?>&amp;f=<?php echo isset($_REQUEST['f'])?$_REQUEST['f']:"creation_date";?>&amp;o=<?php echo isset($_REQUEST['o'])?$_REQUEST['o']:"ASC";?>"><?php echo $i?></a> &nbsp;
<?php else:?>
<b><?php echo $i?></b> &nbsp;
<?php endif;endfor;?>
<br /><br />
<?php endif;?>
</form>