<div id="footer" class="container_16">
    <div id="menu" class="grid_5 alpha">
        <ul>
            <li>
                <a href="#">
                    Home
                </a>
            </li>
            <li><a href="#">
                    GTC
                </a>
            </li>
            <li>
                <a href="#">
                    About Us
                </a>
            </li>
        </ul>
    </div>
    <div class="grid_11 omega">
        © 2011 MedTechTrade AG, <?= $this->translate( 'All Rights Reserved' ) ?>, 
        <a href="http://www.stockergroup.com" target="blank">Powered by Stocker Group S.A.</a>
    </div>
    <div class="clear"></div>

</div>
