<div id="navegacion" class="container_16"> 
    <ul id="mainlevel">
        <li>
            <a href="
            <?= $this->url( array( 'controller' => 'index' ,
                'action' => 'index' ) , null , true ) ?>">

                Home
            </a>    

        </li>
        <li>
            <a href="#">Buy Equipment</a>
        </li>
        <li>

            <a href="
            <?= $this->url( array( 'controller' => 'vender' ,
                'action' => 'index' ) , null , true ) ?>">

                Vender/Comerciar Equipos
            </a>    

        </li>
        <li>
            <a href="
            <?= $this->url( array( 'controller' => 'Servicios' ,
                'action' => 'index' ) , null , true ) ?>">
                Servicios
            </a>  


        </li>
        <li>
            <a href="
            <?= $this->url( array( 'controller' => 'contacto' ,
                'action' => 'index' ) , null , true ) ?>">

                Contact Us
            </a>    
        </li>
        <li>
            <a href="
            <?= $this->url( array( 'controller' => 'usuario' ,
                'action' => 'index' ) , null , true ) ?>">

                Mi Cuenta
            </a>    
        </li>
    </ul> 
</div> 