<?= $this->doctype(); ?>
<html>
    <head>
        <?= $this->headMeta() ?>        
        <?= $this->headTitle() ?>        
        <?= $this->headLink() ?>        
        <?= $this->jQuery() ?>        
        <?= $this->headScript() ?>        
    </head>
    <body>
        <?= $this->render( '_header.phtml' ); ?>
        <?= $this->render( '_navegacion.phtml' ); ?>

        <div id="content" class="container_16" style="padding: 0px 0px 0px;">
            <div id="details-left" class="grid_4 alpha">
                <?= $this->render( '_menucategories.phtml' ); ?>
                <?= $this->layout()->detailsleft ?>


            </div>
            <div id="contenido" class="grid_8 omega">

                <?= $this->render( '_messages.phtml' ); ?>

                <?= $this->layout()->content ?>


            </div>
            <div id="details-right" class="grid_4 omega" style="padding: 0px 0px 0px;">

                <?= $this->layout()->detailsright ?>
                <?= $this->render( '_contact.phtml' ); ?>

            </div>
            <div class="clear">  
            </div>

        </div>

        <?= $this->render( '_footer.phtml' ); ?>

    </body>
</html>