<h2>Favoritos</h2>
<?php $i = 0; ?>
<div class="caja">
    <?php foreach ( $this->favoritos as $favorito ): ?>
    
    
    
    
        <?php $i++; ?>
        <div 
            class="<?=
    ($i % 2 == 0) ? 'fichaproducto-derecha' :
                    "fichaproducto-izquierda"
        ?> ">

            <div id="gallery1" class="item1">
                <a href="<?=
            $this->url(
                    array( 'module' => 'user' , 'controller' => 'reserva' ,
                'action' => 'borrarfavorito' ,
                'id' => $favorito->id ) , null , true
            )
            ?>" title="<?= $this->translate( 'Delete' ) ?>">
                    <span></span>
                    <img src="/media/catalog/product/device-00.png" 
                         alt="<?= $favorito->equipo ?>">
                </a>
            </div>
       
            <p><a href="<?=
            $this->url(
                    array( 'module' => 'user' , 'controller' => 'equipo' ,
                'action' => 'ver' ,
                'id' => $favorito->equipo_id ) , null , true
            )
            ?>"><?= $this->escape( $favorito->equipo ) ?></a></p>
            <p><?= $this->escape( $favorito->precio ) ?></p>
            <p><?= $this->escape( $favorito->categoria ) ?></p>
            <p><?= $this->escape( $favorito->estadoequipo ) ?></p>
            <p><?= $this->escape( $favorito->fabricante ) ?></p>
            <p><?= $this->escape( $favorito->calidad ) ?></p>
           
        </div>

<?php endforeach; ?>

</div>    
<div  style="clear:both"></div>
<?=
$this->paginationControl(
        $this->favoritos , 'Sliding' , 'reserva/_pag.phtml'
);
?>
