<h2>Favoritos</h2>
<div class="caja">
    <?php foreach ( $this->favoritos as $favorito ): ?>
        <div class="col3">
            <p>
                <img src="/media/catalog/product/device-00.png" 
                     alt="<?= $favorito->equipo ?>">
            </p>
            <p><?= $this->escape( $favorito->equipo ) ?></p>
            <p><?= $this->escape( $favorito->precio ) ?></p>
            <p><?= $this->escape( $favorito->categoria ) ?></p>
            <p><?= $this->escape( $favorito->estadoequipo ) ?></p>
            <p><?= $this->escape( $favorito->fabricante ) ?></p>
            <p><?= $this->escape( $favorito->calidad ) ?></p>
            <p><?= $this->escape( $favorito->imageNombre ) ?></p>
        </div>
                       
        <?php endforeach; ?>
       
    </div>    