<h2>Favoritos</h2>
<table border="1" class="listado">
    <tbody>
        <?php foreach ( $this->favoritos as $favorito ): ?>

            <tr class="<?= $favorito->active
                            ? 'activo' : 'inactivo' ?>">
                <td >
                    <img src="/media/catalog/product/device-00.png" 
                    alt="<?= $favorito->equipo ?>">
                </td>
                <td>
                    <table>
                        <tr>
                            <td>
                                <?= $this->escape( $favorito->equipo ) ?>
                            </td>
                        </tr>
                        <tr>
                            <td>
                                <?= $this->escape( $favorito->preciocompra ) ?>
                            </td>
                        </tr>
                        <tr>
                            <td>
                                <?= $this->escape( $favorito->categoria ) ?>
                            </td>
                        </tr>
                        <tr>
                            <td>
                                <?= $this->escape( $favorito->estadoequipo ) ?>
                            </td>
                        </tr>
                        <tr>
                            <td>
                                <?= $this->escape( $favorito->fabricante ) ?>
                            </td>
                        </tr>
                        <tr>
                            <td>
                                <?= $this->escape( $favorito->calidad ) ?>
                            </td>
                        </tr>
                        <tr>
                            <td>
                                <?= $this->escape( $favorito->imageNombre ) ?>
                            </td>
                        </tr>
                    </table>
                </td>
               
            </tr>
        <?php endforeach; ?>
    </tbody>
</table>