<h2>
    <?= $this->translate( 'equipo reservados' ) ?>
</h2>
<table border="1" class="listado">
    <thead>
    <th>
        <?= $this->translate( 'imagen' ) ?>
    </th>
    <th>
        <?= $this->translate( 'equipo' ) ?>
    </th>
    <th>
        <?= $this->translate( 'precio' ) ?>
    </th>
    <th>
        <?= $this->translate( 'categoria' ) ?>
    </th>
    <th>
        <?= $this->translate( 'estado equipo' ) ?>
    </th>
    <th>
        <?= $this->translate( 'fabricante' ) ?>
    </th>
    <th>
        <?= $this->translate( 'calidad' ) ?>
    </th>
    <th>
        <?= $this->translate( 'acciones' ) ?>
        
    </th>
</thead>
<tbody>
    <?php foreach ( $this->favoritos as $favorito ): ?>

        <tr class="<?= $favorito->active
                        ? 'activo' : 'inactivo' ?>">
            <td >
                <img src="/media/catalog/product/device-00.png" 
                     alt="<?= $favorito->equipo ?>"
                     width="24px" height="24px">
            </td>


            <td>
                <?= $this->escape( $favorito->equipo ) ?>
            </td>


            <td>
                <?= $this->escape( $favorito->precio ) ?>
            </td>

            <td>
                <?= $this->escape( $favorito->categoria ) ?>
            </td>

            <td>
                <?= $this->escape( $favorito->estadoequipo ) ?>
            </td>

            <td>
                <?= $this->escape( $favorito->fabricante ) ?>
            </td>

            <td>
                <?= $this->escape( $favorito->calidad ) ?>
            </td>

            <td>
                <?= $this->escape( $favorito->imageNombre ) ?>
            </td>

        </tr>
    <?php endforeach; ?>
</tbody>
</table>