<h1>Querido usuario</h1>
<p>

    MedTechTrade permite a los usarios registrados vender sus dispositivos médicos 
    usados mediante
    esta plataforma. Si es un nuevo usuario,

    <a href="
    <?=
    $this->url
            ( array(
        'module' => 'default' ,
        'controller' => 'usuario' ,
        'action' => 'registro' ) , 'default' , true )
    ?>">

        <?= $this->translate( 'haga click aqui' ); ?>
    </a>  

</p>
<p>
    y nuestros administradores le enviarán los datos de acceso a la brevedad.  
</p>
<p>
    Si ya está inscrito puede acceder a través de la pestaña "Mi Cuenta".
</p>
<p>
    Para cualquie pregunta, comuníquese con nuestro equipo haciendo clic en la pestaña "Contacto". 
</p>

