<h1>Querido usuario</h1>
<p>


    MedTechTrade permite a los usarios registrados vender sus dispositivos médicos usados mediante
    esta plataforma. Si es un nuevo usuario, <span style="text-decoration: underline;">
        <a href="/index.php?option=com_chronocontact&amp;chronoformname=registration&amp;lang=es">
            haga click aqui
        </a>


    </span>
</p>
<p>
    y nuestros administradores le enviarán los datos de acceso a la brevedad.  
</p>
<p>
    Si ya está inscrito puede acceder a través de la pestaña "Mi Cuenta".
</p>
<p>
    Para cualquie pregunta, comuníquese con nuestro equipo haciendo clic en la pestaña "Contacto". 
</p>

