<h1>
    Hello <?= $this->usuario; ?>,
</h1>

<h2>
    <?= $this->translate( 'welcome to ' ) ?> Medtechtrade.com
</h2>

<p style="color: #F00; font-weight: bold; text-align: center">
    <?= $this->translate( 'thanks for signing in' ) ?>  MedTechTrade.com.<br/>
    <?= $this->translate( 'his account was created and must 
        be activated by the administrator' ) ?><br/>
    <?= $this->translate( 'before they can use it. We will 
        send you a confirmation email soon' ) ?><br/>
</p>
<h3>
    <?= $this->translate( 'after activating your 
        account may be accessed using the following information' ) ?>
    : 
</h3>
<p>
    <?= $this->translate( 'username' ) ?>  - <?= $this->login; ?>
</p>
<p>
    <?= $this->translate( 'password' ) ?>  - <?= $this->password; ?>
</p>

<p>
    <?= $this->translate( 'ingresar a este url para poder validar su correo' ); ?>
</p>
<p>
    <a href="http://medtechtrade.zend.local/emailcheck/<?= $this->enlace ?>" >
        <?= $this->translate('validar Email') ?>
    </a>
</p>


