<h2>
    <?= $this->translate('enlace recomendado por un amigo') ?>
</h2>

<p style="color: #071e4a; font-weight: bold; ">
    <?= $this->translate( 'hola' ) ?>, <?= $this->nombre; ?>, 
    <?= $this->translate('tu amigo')?>, 
    <?= $this->translate('recomienda que ingreses al sitio') ?>:<br/>
    <?= $this->url; ?>
    <?= $this->translate('para visualizar las caracteristicas del equipo')?>
</p>
<p>
    <?= $this->translate('aqui podras encontrar gran cantidad de 
        articulos a precios interesantes')?>
</p> 
<p>
    <?= $this->translate('muchas gracias por recomendarnos') ?>
</p>