<h2><?= $this->translate('fabricantes') ?>
<a href="<?=
$this->url(array(
    'module' => 'admin',
    'controller' => 'fabricante',
    'action' => 'nuevo'
        ), null, true)
?>"
title="<?= $this->translate('nuevo')?>">
<img class ="imagen-new" />
</a>
</h2>
<table border="1" class="listado">
    <thead>
        <tr>
            <th><?= $this->translate('nombre') ?></th>
            <th><?= $this->translate('acciones') ?></th>
        </tr>
    </thead>
    <tbody>
        <?php foreach ($this->fabricantes as $fabricante): ?>
            <?php $id = $fabricante->id; ?>
            <tr class="<?= $fabricante->active ? 'activo' : 'inactivo' ?>">

                <td><?= $this->escape($fabricante->nombre) ?></td>
                <td>

                    <?php
                    $link = $this->url(
                            array('module' => 'admin'
                                , 'controller' => 'fabricante'
                                , 'action' => 'editar'
                                , 'id' => $id))
                    ?>
                    <a href="<?= $link ?>"
                       title="<?= $this->translate('editar') ?>">
                        <img class ="imagen-edit" /></a>

                    <?php
                    $link = $this->url(array('module' => 'admin'
                        , 'controller' => 'fabricante'
                        , 'action' => 'borrar'
                        , 'id' => $id))
                    ?>
                    <a href="<?= $link ?>" 
                       title="<?= $this->translate('eliminar') ?>"
                       onclick="return 
                           confirm(<?= $this->translate('¿Estás seguro?') ?>)">
                        <img class ="imagen-delete" />
                    </a>

                    <?php if ($fabricante->active): ?>
                        <?php
                        $link = $this->url(
                                array('module' => 'admin'
                                    , 'controller' => 'fabricante'
                                    , 'action' => 'desactivar'
                                    , 'id' => $id))
                        ?>
                        <a href="<?= $link ?>" 
                           title="<?= $this->translate('desactivar') ?>" 
                           ><img class ="imagen-desactivar" /></a>

                    <?php else: ?>
                        <?php
                        $link = $this->url(
                                array('module' => 'admin'
                                    , 'controller' => 'fabricante'
                                    , 'action' => 'activar'
                                    , 'id' => $id))
                        ?>

                        <a href="<?= $link ?>" 
                           title="<?= $this->translate('activar') ?>" 
                           ><img class ="imagen-activar" /></a>
    <?php endif; ?>

                </td>
            </tr>
<?php endforeach; ?>
    </tbody>
</table>
<br />
<?=
$this->paginationControl(
        $this->fabricantes, 'Sliding', 'fabricante/_pag.phtml'
);?>


