<?php 
    $this->headScript(Zend_View_Helper_HeadScript::FILE,'scripts/ajaxupload.js');
    $this->headScript(Zend_View_Helper_HeadScript::FILE,'scripts/flag_upload.js');
?>
<h1>Country [Edit]</h1>
<?php 
    $r=isset($_REQUEST['save']) ? $_REQUEST : $this->country;
?>
<br /><br /><br />
<?php if(isset($this->errors)):?>
    <?php $e = $this->errors;?>
<div id="errors">
    Please correct the errors. 
</div>
<?php endif;?>
<form method="post" action="admin/country/edit-country" enctype="multipart/form-data">
    <input type="hidden" name="id" value="<?php echo $r['id'];?>" />
    <fieldset>
    <legend>Basic Information</legend>
    <div class="field">
    	<label>Region</label>
    	<select name="region">
            <option value="0">Select a region...</option>
            <option value="Central America" <?php if(isset($r['region']) && $r['region']=="Central America") echo 'selected="selected"';?>>Central America</option>
            <option value="Caribbean" <?php if(isset($r['region']) && $r['region']=="Caribbean") echo 'selected="selected"';?>>Caribbean</option>
			 <option value="South America" <?php if(isset($r['region']) && $r['region']=="South America") echo 'selected="selected"';?>>South America</option>
        </select>
    	<span class="explanation"><?php echo isset($e['region'])? $e['region']:"";?></span>
    </div>
    <div class="field">
    	<label>Country Name</label>
    	<input type="text" name="country" value="<?php echo isset($r['country'])?$r['country']:"";?>" />
    	<span class="explanation"><?php echo isset($e['country'])? $e['country']:"";?></span>
    </div>
    </fieldset>
    <fieldset>
    <legend>Upload Flag Images</legend>
    <div class="field" id="flag_upload">
    	<label>Select Flag Image</label>
        <img id="flag" src="images/countries/<?php echo isset($this->session->flag)? $this->session->flag:$r['id'].'/'.$r['flag'];?>" alt="" title=""/>
    </div>
    <div class="field" id="logo1_upload">
    	<label>Select Image Logo 1</label>
        <object id="logo1" width="500" height="80">
            <param name="movie" value="images/countries/<?php echo isset($this->session->logo1)? $this->session->logo1:$r['id'].'/'.$r['logo1'];?>"/>
            <param name="wmode" value="transparent"/>
            <embed id="movie" src="images/countries/<?php echo isset($this->session->logo1)? $this->session->logo1:$r['id'].'/'.$r['logo1'];?>" width="500" height="80" wmode="transparent"></embed>
        </object>       
    </div>
    <div class="field" id="logo2_upload">
    	<label>Select Image Logo 2</label>
        <img id="logo2" src="images/countries/<?php echo isset($this->session->logo2)? $this->session->logo2:$r['id'].'/'.$r['logo2'];?>" alt="Tooth with door (e.g.: login)" title="Tooth with door (e.g.: login)" />
    </div>
    <div class="field" id="logo3_upload">
    	<label>Select Image Logo 3</label>
        <img id="logo3" src="images/countries/<?php echo isset($this->session->logo3)? $this->session->logo3:$r['id'].'/'.$r['logo3'];?>" alt="Tooth with binoculars (e.g.: search)" title="Tooth with binoculars (e.g.: search)" />
    </div>
    <div class="field">
    	<label>Enable country</label>
    	<input type="checkbox" name="hidden" value="0" <?php if(isset($r['hidden'])) echo 'checked="checked"'?>/>
    	<span class="explanation"></span>
    </div>
    </fieldset>
    <input type="submit" name="save" value="Save" />
</form>