<script>
    $(function() {
        $( "#tabs" ).tabs();
    });
</script>
<div id="tabs">
    <ul>
        <li><a href="#fragment-1"><span>Datos</span></a></li>
        <li><a href="#fragment-2"><span>Equipos</span></a></li>
        <li><a href="#fragment-3"><span>Preguntas</span></a></li>
        <li><a href="#fragment-4"><span>Reservas</span></a></li>
        <li><a href="#fragment-5"><span>Operaciones</span></a></li>
        <li><a href="#fragment-6"><span>Estadisticas</span></a></li>
        <li><a href="#fragment-7"><span>Acciones</span></a></li>
    </ul>
    <div id="fragment-1">
        <p><?= $this->form ?></p>

    </div>
    <div id="fragment-2">
        <?= $this->render('user/detalle/equipos.phtml'); ?>

    </div>
    <div id="fragment-3">
        <?= $this->render('user/detalle/preguntas.phtml'); ?>    

    </div>
    <div id="fragment-4">
        <?= $this->render('user/detalle/reservas.phtml'); ?>

    </div>
    <div id="fragment-5">
        <?= $this->render('user/detalle/operaciones.phtml'); ?>

    </div>
    <div id="fragment-6">
        <p>First tab is active by default:</p>

    </div>
    <div id="fragment-7">
        <p>First tab is active by default:</p>

    </div>
</div>