<h2>Usuario:</h2>


<table border="1" class="listado">
    <thead>
        <tr>
            <th>Nombre</th>
            <th>Operaciones</th>
        </tr>
    </thead>
    <tbody>
        <?php foreach ( $this->fabricantes as $fabricante ): ?>
            <?php $id = $fabricante->id; ?>
            <tr class="<?= $fabricante->active ? 'activo' : 'inactivo' ?>">
                
                <td><?= $this->escape( $fabricante->nombre ) ?></td>
                <td>

                    <?php $link = $this->url( array( 'module' => 'admin' ,'controller' => 'fabricante' ,'action' => 'editar' , 'id' => $id ) ) ?>
                    <a href="<?= $link ?>">[Editar]</a>

                    <?php $link = $this->url( array( 'module' => 'admin' ,'controller' => 'fabricante' ,'action' => 'borrar' , 'id' => $id ) ) ?>
                    <a href="<?= $link ?>" onclick="return confirm('¿Estás seguro?')">[Borrar]</a>

                    <?php if ( $fabricante->active ): ?>
                        <?php $link = $this->url( array('module' => 'admin' ,'controller' => 'fabricante' , 'action' => 'desactivar' , 'id' => $id ) ) ?>
                        <a href="<?= $link ?>">[Desactivar]</a>
                    <?php else: ?>
                        <?php $link = $this->url( array('module' => 'admin' ,'controller' => 'fabricante' , 'action' => 'activar' , 'id' => $id ) ) ?>
                        <a href="<?= $link ?>">[Activar]</a>
                    <?php endif; ?>

                </td>
            </tr>
        <?php endforeach; ?>
    </tbody>
</table>
<br />

<a href="<?= $this->url( array('module' => 'admin' ,'controller' => 'fabricante' , 'action' => 'nuevo' , 'controller' => 'fabricante' ) , null , true ) ?>">Nuevo</a>
