<h2><?= $this->translate('Usuario') ?></h2>

<script>
    function prueba(id){
        $.get('/admin/user/detalle/id/'+id, {}, 
        function(data,textStatus) { 
            $('#dialog_text').html(data); 
            $( "#dialog" ).dialog({
                height: 386,
                width: 732,
                modal: true
            });
            $('#dialog').fadeIn('l'); 
        }, 'html'); return false

    }
</script>


<div id="dialog" title="<?= $this->translate('ver detalles') ?>">
    <div id="dialog_text"></div>
</div>

<table border="1" class="listado">
    <thead>
        <tr>
            <th>
                <?= $this->translate('Nombre') ?>
            </th>
            <th>
                <?= $this->translate('Apellido') ?>
            </th>
            <th>
                <?= $this->translate('Email') ?>
            </th>
            <th>
                <?= $this->translate('Login') ?>
            </th>
            <th>
                <?= $this->translate('Rol') ?>
            </th>
            <th>
                <?= $this->translate('Fecha De Registro') ?>
            </th>
            <th>
                <?= $this->translate('Ciudad') ?>
            </th>
            <th>
                <?= $this->translate('Cod. Postal') ?>
            </th>
            <th>
                <?= $this->translate('Pais') ?>
            </th>
            <th>
                <?= $this->translate('Operaciones') ?>
            </th>
        </tr>
    </thead>
    <tbody>
        <?php foreach ($this->usuarios as $usuario):
            ?>
            <?php $id = $usuario->id; ?>
            <tr class="<?= $usuario->active ? 'activo' : 'inactivo' ?>">

                <td>
                    <?php
                    $link = $this->url(array('module' => 'admin',
                        'controller' => 'user',
                        'action' => 'detalle',
                        'id' => $usuario->id))
                    ?>
                    <a href="#" 
                       onclick="prueba(<?= $this->escape($usuario->id) ?>)">
                           <?= $this->escape($usuario->nombre) ?>
                    </a>

                </td>
                <td><?= $this->escape($usuario->apellido) ?></td>
                <td><?= $this->escape($usuario->email) ?></td>
                <td><?= $this->escape($usuario->login) ?></td>
                <td><?= $this->escape($usuario->rol) ?></td>
                <td><?= $this->escape($usuario->fecharegistro) ?></td>
                <td><?= $this->escape($usuario->ciudad) ?></td>
                <td><?= $this->escape($usuario->codpostal) ?></td>
                <td><?= $this->escape($usuario->pais) ?></td>

                <!--Operaciones -->
                <td>
                    <!--Operaciones -->
                    <?php
                    $link = $this->url(array('module' => 'admin',
                        'controller' => 'user',
                        'action' => 'operation',
                        'id' => $id))
                    ?>
                    <a href="<?= $link ?>" 
                       title="<?= $this->translate('operaciones') ?>" >
                        <img class ="imagen-transacciones">
                    </a>
                    <!--End operaciones -->

                    <!--Operaciones -->
                    <?php
                    $link = $this->url(array('module' => 'admin',
                        'controller' => 'user',
                        'action' => 'equipment',
                        'id' => $id))
                    ?>
                    <a href="<?= $link ?>" 
                       title="<?= $this->translate('equipos') ?>" >
                        <img class ="imagen-equipos">
                    </a>

                    <!--End Equipos -->


                    <?php
                    $link = $this->url(array('module' => 'admin',
                        'controller' => 'user',
                        'action' => 'editar',
                        'id' => $id))
                    ?>
                    <a href="<?= $link ?>" 
                       title="<?= $this->translate('editar') ?>" >
                        <img class ="imagen-edit">
                    </a>

                    <?php
                    $link = $this->url(array('module' => 'admin',
                        'controller' => 'user',
                        'action' => 'borrar',
                        'id' => $id))
                    ?>

                    <?php if ($usuario->active): ?>
                        <?php
                        $link = $this->url(array('module' => 'admin',
                            'controller' => 'user',
                            'action' => 'desactivar',
                            'id' => $id))
                        ?>
                        <a href="<?= $link ?>" 
                           title="<?= $this->translate('desactivar') ?>" >
                            <img class ="imagen-desactivar">
                        </a>

                    <?php else: ?>
                        <?php
                        $link = $this->url(array('module' => 'admin',
                            'controller' => 'user',
                            'action' => 'activar',
                            'id' => $id))
                        ?>
                        <a href="<?= $link ?>" 
                           title="<?= $this->translate('activar') ?>" >
                            <img class ="imagen-activar">
                        </a>

                    <?php endif; ?>

                </td>
            </tr>
        <?php endforeach; ?>
    </tbody>
</table>
<br />
<?php 
    $link = $this->url(array('module' => 'admin',
            'controller' => 'user',
            'action' => 'nuevo'), null, true);
?>
<a href="<?= $link ?>" 
   title="<?= $this->translate('nuevo') ?>" >
    <img class ="imagen-new">
</a>

<?=
$this->paginationControl(
        $this->usuarios, 'Sliding', 'user/_pag.phtml'
);
?>


