CREATE TABLE ipligence (
	ip_from INT UNSIGNED ZEROFILL NOT NULL DEFAULT '0000000000',
	ip_to INT UNSIGNED ZEROFILL NOT NULL DEFAULT '0000000000',
	country_code VARCHAR(10) NOT NULL,
	country_name VARCHAR(255) NOT NULL,
	continent_code VARCHAR(10) NOT NULL,
	continent_name VARCHAR(255) NOT NULL,
	PRIMARY KEY( ip_to)
);